import assert from 'node:assert/strict';
import * as T from 'three';
import Sim from '../src/js/combat.js';
import {newProfile,rollNamed,makeNamedItem} from '../src/js/rpg.js';
import {currentStory} from '../src/js/story.js';
import {caravanState,CARAVAN_STORY,trackTraining,TRIALS} from '../src/js/caravan-story.js';
import {CARAVAN_GROUPS,CARAVAN_CHESTS,CARAVAN_PEOPLE} from '../src/js/chapter-two-data.js';
import {applyCommands} from '../src/js/commands.js';
import {addHazard,tickHazards,updateCaravanEnemy,shieldFactor} from '../src/js/caravan-combat.js';
import {createCreature,updateCreature,disposeCreature} from '../src/creature-rigs.js';
import {hubView,journeyView,futureView,trainingView,bestiaryView} from '../src/mobile-ui.js';
import {journalView} from '../src/story-ui.js';
const fresh=(sandbox=false)=>{const p=newProfile('caravan','Traveler','katana');p.level=8;p.story={version:2,stage:9,choice:'orchard',relationship:'courtship',journal:[],flags:{}};return new Sim('katana',{sandbox}).attachProfile(p,42,'c2');};
for(const route of ['family','furnace']){let s=fresh();assert(s.travel('caravan'));assert.equal(s.player.x,4650);for(let i=0;i<CARAVAN_STORY.length;i++){const q=currentStory(s.profile);assert.equal(q.chapter,2);assert.equal(q.stage,i);s.player.x=q.target.x;s.player.y=q.target.y;if(q.target.guards){assert(!s.storyAction(q.target.id));s.enemies.filter(e=>e.group===q.target.guards).forEach(e=>e.dead=true);}if(q.choices)assert(!s.storyAction(q.target.id,'wrong'));const cmd={op:'story',id:q.target.id,choice:i===4?route:i===8?'family':'continue'},replay=Sim.restore(s.exportState());applyCommands(s,[cmd]);applyCommands(replay,[cmd]);assert.deepEqual(s.exportState(),replay.exportState());assert.equal(s.profile.caravan.stage,i+1);s=Sim.restore(s.exportState());}assert.equal(currentStory(s.profile),null);assert(s.profile.caravan.fatherSafe&&s.profile.caravan.furnaceDisabled);assert(s.loot.some(l=>l.item?.signature==='wayfarer'));const before=s.gold;assert(!s.storyAction('c2-home','family'));assert.equal(before,s.gold);assert(journalView(s.profile).includes('CHAPTER TWO'));assert.equal((journalView(s.profile).match(/class="complete"/g)||[]).length,9);}
let s=fresh();s.profile.story.stage=8;assert(!s.travel('caravan'));s.profile.story.stage=9;const hp=s.player.hp;s.player.hp=100;assert(s.travel('caravan'));assert.equal(s.player.hp,100);const threat=s.addEnemy('raider',s.player.x+50,s.player.y);threat.active=true;assert(!s.travel('harbor'));
// Migration appends the new world exactly once without resetting old progress.
s=fresh();const old=s.exportState();delete old.caravanWorldVersion;old.enemies=old.enemies.filter(e=>!e.group?.startsWith('c2-'));old.groups=old.groups.filter(g=>!g.id.startsWith('c2-'));old.chests=old.chests.filter(c=>!c.id.startsWith('c2-'));old.profile.gold=777;old.profile.skillTree.nodes=['edge-s0'];old.chests[0].opened=true;const restored=Sim.restore(old);assert.equal(restored.enemies.length,98);assert.equal(restored.chests.length,11);assert.equal(restored.profile.gold,777);assert(restored.chests[0].opened);assert(restored.profile.skillTree.nodes.includes('edge-s0'));assert.deepEqual(restored.exportState(),Sim.restore(restored.exportState()).exportState());
// Hazards honor warning time, apply slow/damage, expire, and survive replay.
s=fresh(true);addHazard(s,0,0,100,'web',10,.5,1);const initial=s.player.hp;tickHazards(s,.2);assert.equal(s.player.hp,initial);tickHazards(s,.4);tickHazards(s,.01);assert(s.player.hp<initial);assert(s.player.surfaceSlow>0);for(let i=0;i<100;i++)tickHazards(s,.02);assert.equal(s.hazards.length,0);
// Scouts can be interrupted; reinforcement count is bounded per scout.
s=fresh(true);let e=s.addEnemy('scout',150,0,'c2-road');e.active=true;updateCaravanEnemy(s,e,1);e.stun=.2;updateCaravanEnemy(s,e,.2);assert.equal(e.callTime,0);e.stun=0;for(let i=0;i<5;i++)updateCaravanEnemy(s,e,1);assert.equal(s.enemies.length,3);assert(e.called);
// Shield skills open a flank window; ordinary front hits are reduced.
s=fresh(true);e=s.addEnemy('shieldguard',100,0);e.angle=Math.PI;assert.equal(shieldFactor(s,e,{kind:'normal'}),.35);assert.equal(shieldFactor(s,e,{kind:'skill'}),1);assert(e.shieldBroken>0);assert.equal(shieldFactor(s,e,{kind:'normal'}),1);
for(const type of ['spider','golem','ridgebeast','warden','matriarch','colossus']){s=fresh(true);e=s.addEnemy(type,150,0,'c2-colossus');e.cooldown=0;e.active=true;const baseline=s.exportState(),copy=Sim.restore(baseline);const cmds=Array.from({length:160},()=>({op:'step',dt:.02,x:0,y:0}));applyCommands(s,cmds);applyCommands(copy,cmds);assert.deepEqual(s.exportState(),copy.exportState());assert(e.attackNo>0,type+' attacks');assert(s.player.hp< s.player.maxHp||s.hazards.length>0,type+' threatens');}
// Each new species owns different geometry; idle, windup and death remain finite.
const scene=new T.Scene(),boxes=[];for(const type of ['spider','golem','ridgebeast','matriarch','colossus']){s=fresh(true);e=s.addEnemy(type,0,0);const rig=createCreature(scene,e);for(const state of ['walk','wind','death']){e.moving=state==='walk';e.wind=state==='wind'?.5:0;e.dead=state==='death';e.death=1;e.deathSide=1;updateCreature(rig,e,.02,s);assert(rig.root.position.toArray().every(Number.isFinite));}boxes.push(new T.Box3().setFromObject(rig.root).getSize(new T.Vector3()).toArray());disposeCreature(rig);}assert(new Set(boxes.map(JSON.stringify)).size===5);assert.equal(scene.children.length,0);
// Named effects apply only when equipped; the server supplies their source and identity.
s=fresh(true);const item=makeNamedItem(s,'glassfang',8);s.profile.inventory.push(item);assert(!s.build.keys.exploit);assert(s.equipItem(item.id));assert(s.build.keys.exploit);let count=0;for(let i=0;i<4000;i++)if(rollNamed(s,'matriarch'))count++;assert(count>850&&count<1150);assert(!rollNamed(s,'raider'));
// Training records one reward per evolution, with live evolution gating.
s=fresh();s.travel('caravan');s.profile.quests.captain.progress=1;s.player.x=5450;s.player.y=920;assert(s.evolutionAction('choose','duelist'));assert(s.trainingAction('start'));trackTraining(s,'marks',9);assert.equal(s.profile.caravan.training.progress,9);assert(s.trainingAction('claim'));assert(!s.trainingAction('claim'));assert(!s.trainingAction('start'));assert(s.loot.some(l=>l.item?.signature==='mentor'));assert(trainingView(s.profile).includes('COMPLETED'));
const ui=hubView(s.profile);assert(ui.includes('data-tab="shop"')&&ui.includes('data-tab="dungeons"'));assert(futureView('shop').includes('no purchases'));assert(futureView('dungeons').includes('not available'));assert(journeyView(s.profile).includes('Walk east from Willowbend into Saffron'));assert(bestiaryView().includes('Glassback Spider'));
console.log('PASS Chapter Two both routes, save/reward idempotence, travel safety, content migration, species AI/replay, hazard warning/expiry, scout interrupts, shield breaks, unique rigs, named loot, evolution training and menu destinations');
