import assert from 'node:assert/strict';
import Combat from '../src/js/combat.js';
import {newProfile} from '../src/js/rpg.js';
import {EVOLUTIONS,EVOLUTION_NODES,evolutionBudget,evolutionError} from '../src/js/evolutions.js';
import {routeTo,allocate,NODES,KEYSTONES} from '../src/js/skill-tree.js';
import {applyCommands} from '../src/js/commands.js';
import {modifyAttack,hitMultiplier} from '../src/js/build-effects.js';
import {prepareBuildAttack,grantBarrier,tickBuild} from '../src/js/evolution-combat.js';
const fresh=(c='katana',level=20)=>{const p=newProfile('evo','Tester',c);p.level=level;p.quests.captain.progress=1;return new Combat(c,{sandbox:true}).attachProfile(p,42,'evo');};
assert.equal(EVOLUTIONS.length,8);assert.equal(EVOLUTION_NODES.length,96);assert.equal(new Set(EVOLUTION_NODES.map(n=>n.id)).size,96);
for(const [l,points] of [[1,0],[6,2],[10,4],[15,6],[20,8]])assert.equal(evolutionBudget(fresh('katana',l).profile),points);
for(const evolution of EVOLUTIONS){const s=fresh(evolution.classId);assert(!s.evolutionAction('choose','__proto__'));assert(!s.evolutionAction('choose',{toString:3}));assert(!s.evolutionAction('learn',{}));assert(s.evolutionAction('choose',evolution.id));assert.equal(s.build.evolution,evolution.id);assert(!s.evolutionAction('learn',evolution.id+'-7'));for(let i=0;i<8;i++)assert(s.evolutionAction('learn',evolution.id+'-'+i));assert(!s.evolutionAction('learn',evolution.id+'-8'));assert(!s.evolutionAction('refund',evolution.id+'-0'));assert(s.evolutionAction('refund',evolution.id+'-7'));assert(s.evolutionAction('learn',evolution.id+'-7'));assert(s.build.traits[evolution.branches[0][1]]);assert(!s.input('ultimate'));assert(!s.input('heavy'));const b=Combat.restore(s.exportState());assert.deepEqual(b.exportState(),s.exportState());const commands=[{op:'act',action:'dash'},...Array.from({length:30},()=>({op:'step',dt:.02,x:0,y:0})),{op:'act',action:'skill0'},...Array.from({length:70},()=>({op:'step',dt:.02,x:0,y:0}))];applyCommands(s,commands);applyCommands(b,commands);assert.deepEqual(s.exportState(),b.exportState());}
let s=fresh();s.profile.level=5;assert(!s.evolutionAction('choose','duelist'));s.profile.level=20;s.profile.quests.captain.progress=0;assert.equal(evolutionBudget(s.profile),8);assert(!s.evolutionAction('choose','bulwark'));assert(s.evolutionAction('choose','duelist'));s.player.hp=100;assert(s.evolutionAction('learn','duelist-0'));assert(s.evolutionAction('choose','windblade'));assert.equal(s.player.hp,100);assert.deepEqual(s.profile.evolution.nodes,[]);assert.equal(s.profile.classId,'katana');s.addEnemy('raider',100,0);assert(!s.evolutionAction('choose','duelist'));
// Every distant terminal can be reached with the real budget and prerequisite validator.
for(const n of NODES.filter(n=>n.id.includes('-outer-')&&n.id.endsWith('-8'))){const c=KEYSTONES[n.key]?.weapon||'katana',s=fresh(c),route=routeTo(s.profile,n.id);assert(route.length>8&&route.length<40);for(const id of route)assert(allocate(s.profile,id),id);assert(s.profile.skillTree.nodes.includes(n.id));}
const target=s=>{const e=s.addEnemy('raider',70,0);e.hp=e.maxHp=100000;s.player.angle=0;return e;};
let serial=500;const hit=(s,e,kind='normal',extra={})=>{const hp=e.hp;s.strike({id:++serial,step:0,pulses:0,kind,def:{damage:100,reach:200,arc:7,...extra}});return hp-e.hp;};
s=fresh();s.evolutionAction('choose','duelist');for(let i=0;i<8;i++)s.evolutionAction('learn','duelist-'+i);let e=target(s);hit(s,e);hit(s,e);hit(s,e);assert.equal(s.player.marks,3);s.drainEvents();hit(s,e,'skill');assert.equal(s.player.marks,0);assert(s.drainEvents().some(x=>x.type==='hit'&&x.critical));
s=fresh('twins');s.evolutionAction('choose','strider');s.input('dash');s.player.dashTime=0;s.player.dashCooldown=0;s.input('dash');s.player.dashTime=0;assert.equal(s.player.momentum,2);s.input('skill0');assert.equal(s.player.attack.def.buildMultiplier,1.4);assert.equal(s.player.momentum,0);
s=fresh('pistols');s.evolutionAction('choose','sharpshooter');for(let i=0;i<8;i++)s.evolutionAction('learn','sharpshooter-'+i);tickBuild(s,1.5,{x:0,y:0});assert.equal(s.player.focus,1.5);s.input('attack');assert(s.player.attack.def.pierce>=3);assert.equal(s.player.attack.def.buildMultiplier,1.35);tickBuild(s,.02,{x:1,y:0});assert.equal(s.player.focus,0);
s=fresh('pistols');s.evolutionAction('choose','outrider');s.input('dash');s.player.dashTime=0;s.input('attack');assert.equal(s.player.attack.def.pellets,3);
s=fresh('greatsword');s.evolutionAction('choose','siege');e=target(s);hit(s,e,'skill');assert(e.exposedUntil>s.time);const boosted=hit(s,e);e.exposedUntil=0;const baseline=hit(s,e);assert(boosted>baseline);
s=fresh('greatsword');s.evolutionAction('choose','bulwark');let blocked=false;for(let i=0;i<100;i++){s.player.invulnerable=0;if(!s.damagePlayer(1,0,0)){blocked=true;break;}}assert(blocked);assert(s.player.barrier>0);
const def={duration:1,active:.3,reach:200,damage:100,arc:2,launch:100};let d=modifyAttack(def,'normal',{keys:{},evolution:'dancer',traits:{fullCircle:true}},false);assert.equal(d.shape,'spin');assert.equal(d.damage,90);assert(d.duration<1);d=modifyAttack(def,'skill',{keys:{},evolution:'windblade',traits:{updraft:true}},false);assert(d.launch>=310&&d.reach===260);d=modifyAttack({...def,slam:true},'skill',{keys:{},traits:{aftershock:true}},false);assert.equal(d.pulses,2);assert.equal(d.damage,70);d=modifyAttack(def,'skill',{keys:{volley:true,rail:true}},true);assert.equal(d.pierce,1);assert.equal(d.pulses,3);
s=fresh();s.build={keys:{reserve:true},barrier:.5};s.input('dash');assert.equal(s.player.barrier,s.player.maxHp*.15);s.build={keys:{rebound:true},regen:100};s.player.hp=100;tickBuild(s,1,{x:0,y:0});assert.equal(s.player.hp,100);
const context={kind:'normal',aerial:false,slam:false,enemyRatio:.5,distance:200,ranged:true,critical:false,counter:false,moving:true,combo:20,lifeRatio:.2};const mult=k=>hitMultiplier({keys:{[k]:true}},context);assert.equal(mult('close'),1.6);assert.equal(mult('pursuit'),1.3);assert.equal(mult('focus'),.85);assert.equal(mult('tenacity'),1.45);assert.equal(mult('opening'),.9);assert.equal(mult('pressure'),1.19);
console.log('PASS 8 evolutions / 96 nodes: unlocks, separate budget, switching, refunds, safety, four inputs, replay; outer atlas routes; marks, momentum, focus, exposure, block barriers, circular cuts, launch, aftershocks and volley precedence');
