import assert from 'node:assert/strict';import * as T from 'three';import {SurfaceFX,surfaceAt} from '../src/surface-fx.js';import {healthRatio,lootLabelIds,updateEnemyBars,clearEnemyBars} from '../src/combat-hud.js';import {makeItem,RARITIES,LOOT_TABLES,rollEquipment,newProfile} from '../src/js/rpg.js';import {gearMesh,disposeGear} from '../src/gear-visuals.js';import Combat from '../src/js/combat.js';
const surface=new SurfaceFX(new T.Scene(),[{x:1,z:0,seed:.2},{x:-1,z:0,seed:.3},{x:5,z:0,seed:.4}]);assert.equal(surface.cut({x:0,y:0,reach:200,arc:1.4,angle:0}).length,1);assert(surface.points[0].cut);assert(!surface.points[1].cut);assert.equal(surface.cut({x:0,y:0,reach:200,arc:1.4,angle:0}).length,0);assert.equal(surface.cut({x:0,y:0,reach:200,shape:'spin',angle:0}).length,1);surface.reset();assert(surface.points.every(p=>!p.cut));assert.equal(surfaceAt(8250,-2950),'snow');const p={x:8250,y:-2950,moving:true,angle:0};surface.update(1,p);assert.equal(surface.footSerial,1);surface.update(1.1,p);assert.equal(surface.footSerial,1);p.x+=50;surface.update(1.2,p);assert.equal(surface.footSerial,2);surface.update(58,{...p,moving:false});assert(surface.trackAges.every(t=>t<0));
console.log('PASS directional/radial grass cuts, no recutting, reset, alternating snow footprints and expiry');
const sim=new Combat('katana',{sandbox:true}).attachProfile(newProfile('x','Tester','katana'));for(let i=0;i<8;i++){const l=sim.drop(i*30,0,'equipment');l.item=makeItem('i'+i,'weapon',4,'legendary','katana','keep');}sim.player.lootTarget=sim.loot[7].id;const ids=lootLabelIds(sim);assert.equal(ids.size,3);assert(ids.has(sim.player.lootTarget));assert.equal(healthRatio({hp:-20,maxHp:100}),0);assert.equal(healthRatio({hp:150,maxHp:100}),1);
globalThis.document={createElement:()=>({style:{},append(){},remove(){this.removed=true;}})};const e=sim.addEnemy('raider',100,0);e.active=true;const renderer={width:960,height:540,labelLayer:{append(){}},screenPosition(){return{x:400,y:200};}};updateEnemyBars(renderer,sim,.016);e.hp-=30;updateEnemyBars(renderer,sim,.016);const bar=renderer.enemyBars.get(e.id);assert(parseFloat(bar.chip.style.width)>parseFloat(bar.fill.style.width));assert(bar.delay>0);for(let i=0;i<60;i++)updateEnemyBars(renderer,sim,.016);assert(Math.abs(parseFloat(bar.chip.style.width)-parseFloat(bar.fill.style.width))<.01);e.dead=true;updateEnemyBars(renderer,sim,.016);assert(!renderer.enemyBars.has(e.id));clearEnemyBars(renderer);
for(const rarity of RARITIES)for(const slot of ['weapon','chest','hands','feet']){const mesh=gearMesh(slot,makeItem('test',slot,7,rarity.id,'katana','keep'));assert(!new T.Box3().setFromObject(mesh).isEmpty());disposeGear(mesh);}for(const table of Object.values(LOOT_TABLES)){assert.equal(table.rarities.length,RARITIES.length);assert.equal(table.rarities.reduce((a,b)=>a+b),100);}let found=false;for(let i=0;i<500;i++)if(rollEquipment(sim,'commander','commander').some(i=>i.rarity==='legendary'))found=true;assert(found);
console.log('PASS three-label cap with selected priority, exact health/delayed damage/death cleanup, red legendary geometry and loot distribution');
// Skills buffered during a dodge actually start after the dodge ends.
const c=new Combat('katana',{sandbox:true});c.input('dash');c.input('skill1');for(let i=0;i<15;i++)c.update(.02);assert(c.player.skillCooldowns[1]>0);console.log('PASS dodge-to-skill input buffer');
