import {AdventureCamera} from '../src/camera-rig.js';import {buildAtmosphere} from '../src/landscape-atmosphere.js';
import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import Renderer from '../src/render3d.js';import Combat from '../src/js/combat.js';import Data from '../src/js/weapons.js';
const r=Object.create(Renderer.prototype);r.scene=new T.Scene();r.camera=new T.PerspectiveCamera();r.templates={};r.effects=[];for(const [key,name] of [['hero','shadow'],['enemy','guard']]){const b=fs.readFileSync(`public/models/${name}.glb`);r.templates[key]=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
r.environment();assert.equal(r.chestObjects.size,11);assert(r.gate);
for(const id of Object.keys(Data.weapons)){const s=new Combat(id,{sandbox:true}),a=r.createActor(s.player,true,s.weapon);for(const move of [...s.weapon.chain,s.weapon.heavy,s.weapon.finisher,s.weapon.slam,...s.weapon.skills,s.weapon.ultimate]){assert(a.actions[move.clip],move.clip);s.player.attack={id:Math.random(),def:move,elapsed:0,aimAngle:0,step:1,chained:true};for(let i=0;i<25;i++){s.player.attack.elapsed=i/25*move.duration;r.updateActor(a,s.player,true,s.weapon,1/60,s);assert(a.bones.every(b=>b.position.toArray().every(Number.isFinite)&&b.quaternion.toArray().every(Number.isFinite)));}}s.player.attack=null;s.player.dead=true;r.updateActor(a,s.player,true,s.weapon,.016,s);assert(a.root.rotation.toArray().slice(0,3).every(Number.isFinite));r.disposeActor(a);}
for(const type of Object.keys(Data.enemies)){const s=new Combat('katana',{sandbox:true}),e=s.addEnemy(type,0,0),a=r.createActor(e,false,s.weapon);for(const state of ['idle','wind','hit','dead']){e.wind=state==='wind'?.5:0;e.hit=state==='hit'?.15:0;e.dead=state==='dead';e.death=1;e.deathSide=1;r.updateActor(a,e,false,s.weapon,.016,s);}r.disposeActor(a);}
console.log('PASS fort geometry, chest/gate visuals, all 4 weapon rigs/attack clips and all 13 human/creature enemy rigs');
// Exercise new frame paths without a GPU; this catches integration errors, not visual quality.
globalThis.document={createElement:()=>({style:{},append(){},classList:{toggle(){}},remove(){},className:'',textContent:''})};r.renderer={getDrawingBufferSize(v){return v.set(960,540);}};r.labelLayer={append(){}};r.actors=new Map();r.labels=[];r.particles=[];r.effects=[];r.ghosts=[];r.time=0;r.shake=0;r.flash=0;r.loaded=true;r.budget={shadowSize:2048,postprocessing:true};r.width=960;r.height=540;r.focus=new T.Vector3();r.offset=new T.Vector3(12.7,19.5,17);r.cameraRig=new AdventureCamera(r.camera,r.focus,r.offset);r.cameraRig.configure({aspect:960/540});r.atmosphere=buildAtmosphere(r.scene);r.sun=new T.DirectionalLight();r.scene.add(r.sun,r.sun.target);r.composer={render(){}};r.makeParticleSystem();const s=new Combat('pistols');s.enemies=[];s.player.x=s.chests[0].x;s.player.y=s.chests[0].y;s.interact();s.input('attack');for(let i=0;i<90;i++){s.update(1/60,{x:1,y:0});r.receive(s.drainEvents());r.render(s,1/60);}assert(r.lootObjects.size>0);assert(r.chestObjects.get(s.chests[0].id).rotation.x<-1);assert(Number.isFinite(r.actors.get('hero').root.rotation.y));r.reset();assert.equal(r.lootObjects.size,0);console.log('PASS chest lid, loot labels, pistol effects, moving attack frame and reset integration');
