import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import {api,applyCommands} from '../worker/api.js';import Combat from '../src/js/combat.js';import {newProfile,rollEquipment,LOOT_TABLES,stats,QUESTS,makeItem} from '../src/js/rpg.js';
let n=0;function test(name,fn){fn();console.log('PASS',name);n++;}
const fresh=()=>new Combat('katana',{sandbox:true}).attachProfile(newProfile('char','Tester','katana'),42,'run');
test('loot tables normalize to 100% and seeded generation is reproducible',()=>{for(const t of Object.values(LOOT_TABLES))assert.equal(t.rarities.reduce((a,b)=>a+b),100);const a=fresh(),b=fresh();assert.deepEqual(Array.from({length:100},()=>rollEquipment(a,'commander','commander')),Array.from({length:100},()=>rollEquipment(b,'commander','commander')));});
test('boss gear respects regional item levels and guaranteed roll count',()=>{const s=fresh(),items=rollEquipment(s,'commander','commander');assert.equal(items.length,3);assert(items.every(i=>i.level>=5&&i.level<=7&&['uncommon','rare','epic','legendary'].includes(i.rarity)));});
test('inventory restrictions, swaps and armor affect combat',()=>{const s=fresh(),item=makeItem('a','chest',1,'rare','katana','approach');s.profile.inventory.push(item);assert(s.equipItem('a'));assert.equal(s.profile.inventory.length,0);assert(s.armor>0);const hp=s.player.hp;s.damagePlayer(50,0,0);assert(hp-s.player.hp<50);const after=s.player.hp;assert(s.unequipItem('chest'));assert(s.equipItem('a'));assert.equal(s.player.hp,Math.min(after,240));const wrong=makeItem('wrong','weapon',1,'epic','pistols','keep');s.profile.inventory.push(wrong);assert(!s.equipItem('wrong'));const high=makeItem('high','weapon',7,'rare','katana','keep');s.profile.inventory.push(high);assert(!s.equipItem('high'));});
test('full inventory leaves equipment on the ground',()=>{const s=fresh();s.profile.inventory=Array.from({length:30},(_,i)=>makeItem('i'+i,'head',1,'common','katana','approach'));const l=s.drop(0,0,'equipment');l.item=makeItem('drop','head',1,'rare','katana','approach');l.z=0;l.age=1;assert(!s.pickup());assert.equal(s.loot.length,1);});
test('XP levels up without quests; retired quest rewards stay disabled',()=>{const s=fresh(),before=structuredClone(s.profile.quests);s.questEvent('kill',{group:'commander',type:'commander'});assert.deepEqual(s.profile.quests,before);assert(!s.claimQuest('road'));s.xp(1000);assert(s.profile.level>1);assert(s.player.maxHp>240);});
test('only four combat inputs are allowed for a character',()=>{const s=fresh();assert(!s.input('heavy'));assert(!s.input('ultimate'));assert(s.input('attack'));assert(s.input('dash'));});
test('serialized combat replay stays deterministic',()=>{const a=fresh(),b=Combat.restore(a.exportState());const commands=[{op:'act',action:'attack'},...Array.from({length:30},()=>({op:'step',dt:1/60,x:1,y:0}))];applyCommands(a,commands);applyCommands(b,commands);assert.deepEqual(a.exportState(),b.exportState());});
const sql=new DatabaseSync(':memory:');sql.exec(fs.readFileSync('drizzle/0000_clumsy_black_tom.sql','utf8'));const env={DB:{prepare(query){const stmt=sql.prepare(query);return {bind(...args){return {
 async first(){return stmt.get(...args)||null;},
 async all(){return {results:stmt.all(...args)};},
 async run(){const result=stmt.run(...args);return {meta:{changes:Number(result.changes)}};}
 };}};}}};
async function call(path,body,user='alice',origin='https://game.test'){const headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'};if(body){headers.origin=origin;headers['Content-Type']='application/json';}const r=await api(new Request('https://game.test/api/'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined}),env);return{status:r.status,data:await r.json()};}
assert.equal((await api(new Request('https://game.test/api/account'),env)).status,401);assert.equal((await call('characters',{name:'Hero',classId:'katana'},'alice','https://evil.test')).status,403);assert.equal((await call('characters',{name:'Hero',classId:'constructor'})).status,400);const created=await call('characters',{name:'Hero',classId:'katana'});assert.equal(created.status,200);const id=created.data.profile.id;assert.equal((await call('run',{id},'bob')).status,404);const run=await call('run',{id});assert.equal(run.status,200);const batch={id,revision:run.data.revision,batchId:'batch-1',commands:[{op:'step',dt:.02,x:1,y:0}]};const saved=await call('batch',batch);assert.equal(saved.status,200);const retry=await call('batch',batch);assert.equal(retry.data.revision,saved.data.revision);assert.equal((await call('batch',{...batch,batchId:'stale'})).status,409);assert.equal((await call('batch',{...batch,revision:saved.data.revision,batchId:'forged',commands:[{op:'xp',amount:99999}]})).status,400);const loaded=await call('run',{id});assert(loaded.data.state.player.x>run.data.state.player.x);assert.equal(loaded.data.state.profile.level,1);assert.equal((await call('account',null,'bob')).data.characters.length,0);console.log('PASS authentication, CSRF, ownership, persistence, stale saves, idempotent retry and forged rewards');console.log(`${n} progression checks and API integration passed`);
