import Data from './weapons.js';
import {CARAVAN_GROUPS,CARAVAN_CHESTS} from './chapter-two-data.js';
export function installCaravan(sim){if(sim.caravanWorldVersion)return;sim.caravanWorldVersion=1;sim.hazards??=[];if(sim.sandbox)return;for(const g of CARAVAN_GROUPS){if(sim.groups.some(x=>x.id===g.id))continue;sim.groups.push({...g,alert:false,cleared:false});for(const [type,dx,dy] of g.units){const e=sim.addEnemy(type,g.x+dx,g.y+dy,g.id);e.level=['c2-fort','c2-colossus'].includes(g.id)?10:g.id==='c2-road'||g.id==='c2-wreck'||g.id==='c2-warden'?6:8;e.hp=Math.round(e.hp*(1+(e.level-1)*.1));e.maxHp=e.hp;}}for(const c of CARAVAN_CHESTS)if(!sim.chests.some(x=>x.id===c.id))sim.chests.push({...c,opened:false});}
export function shieldFactor(sim,e,a){if(!['shieldguard','warden'].includes(e.type))return 1;if(e.broken>0||e.shieldBroken>0)return 1;const angle=Math.atan2(sim.player.y-e.y,sim.player.x-e.x),front=Math.cos(angle-e.angle)>.25;if(!front)return 1;if(a.kind==='skill'||a.kind==='slam'){e.shieldBroken=2.5;sim.emit('guardBreak',{x:e.x,y:e.y});return 1;}return .35;}
export function addHazard(sim,x,y,radius,kind,damage,delay=.8,life=2.5){sim.hazards??=[];sim.hazards.push({id:++sim.serial,x,y,radius,kind,damage,delay,life,pulse:0});}
export function tickHazards(sim,dt){sim.hazards??=[];sim.player.surfaceSlow=Math.max(0,(sim.player.surfaceSlow||0)-dt);for(const h of sim.hazards){if(h.delay>0){h.delay-=dt;continue;}h.life-=dt;h.pulse-=dt;if(h.pulse<=0){h.pulse=.7;if(Math.hypot(sim.player.x-h.x,sim.player.y-h.y)<h.radius){if(h.kind==='web')sim.player.surfaceSlow=.9;sim.damagePlayer(h.damage,h.x,h.y);}}}sim.hazards=sim.hazards.filter(h=>h.life>0);}
// New species use committed windups. Telegraphs stay fixed so dodging is reliable.
export function updateCaravanEnemy(sim,e,dt){const d={...Data.enemies[e.type],damage:Data.enemies[e.type].damage*(e.damageScale||1)},p=sim.player,dist=Math.hypot(p.x-e.x,p.y-e.y);e.shieldBroken=Math.max(0,(e.shieldBroken||0)-dt);
 if(e.type==='shieldguard'){const archer=sim.enemies.find(a=>!a.dead&&a.type==='archer'&&a.group===e.group);if(archer&&dist>130&&e.wind<=0&&!e.stun){const len=Math.max(1,Math.hypot(p.x-archer.x,p.y-archer.y)),tx=archer.x+(p.x-archer.x)/len*150,ty=archer.y+(p.y-archer.y)/len*150,gap=Math.hypot(tx-e.x,ty-e.y);if(gap>30){e.x+=(tx-e.x)/gap*d.speed*dt;e.y+=(ty-e.y)/gap*d.speed*dt;e.angle=Math.atan2(p.y-e.y,p.x-e.x);e.moving=true;return true;}}return false;}
 if(e.type==='scout'){if(!e.called&&dist<650){if(e.stun>0){e.callTime=0;return false;}e.callTime=(e.callTime||0)+dt;e.wind=e.windMax=0;e.moving=false;if(!e.callWarned){e.callWarned=true;sim.emit('notice',{message:'SIGNAL SCOUT · INTERRUPT THE CALL'});}if(e.callTime>=2){e.called=true;for(let i=0;i<2;i++){const a=sim.addEnemy('raider',e.homeX+(i?95:-95),e.homeY+80,e.group);a.active=true;a.level=e.level||6;a.hp=Math.round(a.hp*1.4);a.maxHp=a.hp;}sim.emit('notice',{message:'REINFORCEMENTS ARRIVING'});}return true;}return false;}
 if(!d.creature&&e.type!=='warden')return false;if(e.stun>0||e.z>0||p.dead)return true;
 e.moving=false;if(e.boss&&e.phase===1&&e.hp<e.maxHp*.5){e.phase=2;sim.emit('bossPhase',{name:d.name});if(e.type==='matriarch'&&!e.broodCalled){e.broodCalled=true;for(const dx of [-130,130]){const a=sim.addEnemy('spider',e.homeX+dx,e.homeY,e.group);a.active=true;}}}
 if(e.charge>0){e.charge-=dt;e.x+=Math.cos(e.angle)*780*dt;e.y+=Math.sin(e.angle)*780*dt;if(dist<85)sim.damagePlayer(d.damage,e.x,e.y);if(e.charge<=0){e.cooldown=1.6;e.shieldBroken=1.6;e.recovery=1.6;}return true;}
 if(e.recovery>0&&e.wind<=0)return true;
 if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.attackAnim=.45;e.recovery=e.boss?1.25:d.creature==='golem'?1.1:.55;
  if(e.attackKind==='charge')e.charge=e.type==='ridgebeast'?.35:.5;
  else if(d.creature==='spider'){const offsets=e.boss?[-150,0,150]:[0];for(const offset of offsets)addHazard(sim,e.attackX+offset,e.attackY+Math.abs(offset)*.3,e.boss?105:85,'web',d.damage*.5,.5,3.2);sim.emit('enemyStrike',{x:e.attackX,y:e.attackY,reach:140});}
  else {const r=e.boss?270:200,damage=d.damage*(e.type==='colossus'&&sim.profile?.caravan?.furnaceDisabled?.7:1);sim.emit('enemyStrike',{x:e.x,y:e.y,reach:r});if(Math.hypot(p.x-e.x,p.y-e.y)<r)sim.damagePlayer(damage,e.x,e.y);if(d.creature==='golem'){addHazard(sim,e.x,e.y,r*.7,'heat',damage*.45,.3,2);if(e.boss)addHazard(sim,e.attackX,e.attackY,150,'heat',damage*.7,1.0,.12);if(e.boss&&e.phase===2)for(const side of [-1,1])addHazard(sim,e.x+side*250,e.y-120,100,'heat',damage*.5,.9,2.4);e.broken=1.8;}}
  e.cooldown=(e.boss?1.6:1.3)*(e.phase===2?.8:1);
 }return true;}
 const range=d.creature==='spider'?500:e.type==='ridgebeast'||e.type==='warden'?440:240;
 if(e.cooldown<=0&&dist<range){e.attackNo++;e.attackKind=e.type==='ridgebeast'||e.type==='warden'&&e.attackNo%2?'charge':d.creature==='spider'?'web':'sweep';e.windMax=d.wind;e.wind=e.windMax;e.attackX=p.x;e.attackY=p.y;e.angle=Math.atan2(p.y-e.y,p.x-e.x);return true;}
 const retreat=d.creature==='spider'&&dist<210,desired=d.creature==='spider'?360:120;if(dist>desired||retreat){const direction=retreat?-1:1;if(dist<1400){e.x+=(p.x-e.x)/Math.max(1,dist)*d.speed*dt*direction;e.y+=(p.y-e.y)/Math.max(1,dist)*d.speed*dt*direction;e.moving=true;e.angle=Math.atan2(p.y-e.y,p.x-e.x);}}
 return true;
}
