import {CARAVAN_PEOPLE,CARAVAN_START} from './chapter-two-data.js';
import {EVOLUTION_BY_ID} from './evolutions.js';
export const CARAVAN_STORY=[
 {who:'c2-lina',title:'The letters that stopped',goal:'Meet Lina at Saffron Caravanserai.',text:'Lina lays three letters on the table. The first describes her father’s supply caravan. The second mentions guards charging a new toll. The third contains only a pressed blue flower. “He sends these when he cannot speak freely. We restored the river, but someone is still deciding who gets to live beside it.”',reply:'We will follow his road together.'},
 {who:'c2-salma',title:'A debt written in hunger',goal:'Ask Salma about the missing wagons.',text:'Salma has paid for the same shipment twice. Each payment bought another promise, never a delivery. “Marshal Hadrik calls the roads unsafe. His own men escort every wagon that disappears.” She shows you a torn manifest. The missing cargo is medicine and grain—not weapons.',reply:'Show me where the escort last stopped.'},
 {who:'c2-wreck',title:'No bodies, no cargo',goal:'Clear the terrace ambush and search the broken caravan.',text:'The wagons were unloaded carefully before their wheels were broken. Small crystal spiders have nested beneath the empty beds. You find Yusuf’s tool roll, but no blood. Someone wanted this to look like an attack. Tracks lead to Hadrik’s checkpoint.',reply:'Follow the escort’s tracks.'},
 {who:'c2-orders',title:'The price of safe passage',goal:'Defeat Marshal Hadrik and examine his dispatch case.',text:'Hadrik’s orders name no enemy. They order the arrest of engineers who can reopen the old mountain road. His employer, Broker Vey, bought the only remaining freight route. As long as the villages believe the pass is lost, every meal must travel through his warehouses.',reply:'Find the surveyor named in the orders.'},
 {who:'c2-surveyor',title:'What the mountain remembers',goal:'Defeat the Glassweaver Matriarch and rescue Surveyor Idris.',text:'Idris shelters behind survey stakes while shattered crystal glitters across the ravine. “Yusuf repaired the old road. Vey took him to Whitewind before anyone could learn it was open. The fortress furnace powers a stone war engine; its feed valve lies in Cinderwash.” Both routes matter. Choose which danger to face first.',choices:[['family','Reach Yusuf first. No one is left behind.'],['furnace','Disable the furnace first. Make the rescue route safer.']]},
 {who:'first-route',title:'The first promise',goal:'Complete your chosen route.',reply:'The other route still needs us.'},
 {who:'second-route',title:'A road for everyone',goal:'Complete the remaining route.',reply:'Enter Brasswater and seize the ration ledger.'},
 {who:'c2-ledger',title:'The cost of silence',goal:'Defeat the Furnace Colossus and recover Vey’s ledger.',text:'The furnace falls silent. Behind its controls lie records of withheld medicine, invented shortages and payments to Hadrik. Vey has fled, leaving his hired guards unpaid. Yusuf asks you to take the ledger home. “A sword can open a gate. Evidence can keep it open.”',reply:'Bring the evidence and supplies to Saffron.'},
 {who:'c2-home',title:'A place at the table',goal:'Return to Lina and Yusuf at Saffron Caravanserai.',text:'The first recovered wagons arrive under the market awnings. Salma reads the ledger aloud to the caravan elders, who place the road under a shared watch. Lina’s father sets one more cup on the family table. The mountain is quiet tonight; the people who crossed it are not forgotten.',choices:[['family','Stay for a family meal and speak about the future.'],['friend','Celebrate with them as a trusted friend.']]}
];
export const TRIALS={
 duelist:{name:'A measured answer',event:'marks',goal:9,text:'Consume 9 Duelist marks with skill hits.'},windblade:{name:'Keep them aloft',event:'air',goal:12,text:'Land 12 hits on airborne enemies.'},
 strider:{name:'Travel with purpose',event:'momentum',goal:8,text:'Consume 8 Momentum stacks with skills.'},dancer:{name:'Never lose the rhythm',event:'rhythm',goal:12,text:'Land 12 basic hits while your combo is at least 10.'},
 bulwark:{name:'A guard that answers',event:'block',goal:6,text:'Block 6 enemy attacks.'},siege:{name:'Open the breach',event:'exposed',goal:12,text:'Land 12 hits on exposed enemies.'},
 sharpshooter:{name:'Choose your moment',event:'focus',goal:10,text:'Land 10 fully focused attack pulses.'},outrider:{name:'Fight on the road',event:'dashHit',goal:12,text:'Land 12 dodge-follow-up hits.'}
};
export function caravanState(p){return p?(p.caravan??={version:1,started:false,stage:0,route:null,journal:[],relationship:null,training:null,trainingDone:[]}):null;}
export function caravanCurrent(p){const s=caravanState(p);return null;const q=CARAVAN_STORY[s.stage];if(!q)return null;let who=q.who,text=q.text,goal=q.goal;
 if(s.stage===5||s.stage===6){const rescue=(s.route==='family')===(s.stage===5);who=rescue?'c2-rescued':'c2-forge';text=rescue?'Yusuf is tired, but his hands are steady. “Lina still measures twice before she cuts?” He smiles when you nod. He has already drawn a safe route back to camp. You give him supplies and clear the escort’s road. He will wait for you beside his daughter.':'You release the furnace pressure and break its locking gear. The orange glow fades from the feed pipes. The colossus can still move, but its heat bursts will strike with less force. Vey’s fortress is no longer invulnerable.';goal=rescue?'Clear the Whitewind guards and free Yusuf.':'Clear Cinderwash and disable the furnace feed.';}
 if(s.stage===8&&p.story?.relationship==='courtship')text+=' Lina sits beside her father. “If you still wish it, we can ask our families to discuss marriage. There is no need to hurry an honest promise.”';
 return {...q,text,goal,stage:s.stage,chapter:2,target:CARAVAN_PEOPLE.find(n=>n.id===who)};
}
export function trackTraining(sim,event,amount=1,token=null){const s=sim.profile?.caravan,t=s?.training;if(!t||t.claimed||sim.profile.evolution?.id!==t.id||TRIALS[t.id]?.event!==event)return;if(token&&t.tokens?.includes(token))return;if(token)t.tokens=[...(t.tokens||[]),token].slice(-100);t.progress=Math.min(TRIALS[t.id].goal,t.progress+amount);}
export function caravanAdvance(sim,id,choice){const p=sim.profile,s=caravanState(p),q=caravanCurrent(p);if(!q||q.target.id!==id||sim.player.dead||Math.hypot(sim.player.x-q.target.x,sim.player.y-q.target.y)>230||q.target.guards&&sim.enemies.some(e=>!e.dead&&e.group===q.target.guards))return false;if(q.choices&&!q.choices.some(c=>c[0]===choice))return false;if(q.stage===4)s.route=choice;if(id==='c2-forge')s.furnaceDisabled=true;if(id==='c2-rescued')s.fatherSafe=true;if(q.stage===8)s.relationship=choice;s.journal.push({title:q.title,text:q.text,choice:q.choices?.find(c=>c[0]===choice)?.[1]||null});s.stage++;if(q.stage===8)sim.dropNamed('wayfarer',10);p.gold+=q.stage===8?450:90;sim.xp(q.stage===8?900:180);sim.applyStats();sim.emit('notice',{message:q.stage===8?'THE BROKEN CARAVAN · COMPLETE':q.title+' · JOURNAL UPDATED'});return true;}
export function travel(sim,id){const p=sim.profile;if(!p||!sim.canEditTree())return false;const s=caravanState(p);let point;if(id==='caravan'){if((p.story?.stage||0)<9)return false;s.started=true;point=CARAVAN_START;}else if(id==='harbor')point={x:-2700,y:1450};else return false;Object.assign(sim.player,point,{z:0,vz:0,knockX:0,knockY:0,lootTarget:null});sim.emit('notice',{message:id==='caravan'?'SAFFRON CARAVANSERAI':'SEABELL HARBOR'});return true;}
export function trainingAction(sim,action){const p=sim.profile,s=caravanState(p),npc=CARAVAN_PEOPLE.find(n=>n.id==='c2-trainer');if(sim.player.dead||Math.hypot(npc.x-sim.player.x,npc.y-sim.player.y)>230||!sim.canEditTree())return false;const id=p.evolution?.id;if(action==='start'){if(!Object.hasOwn(TRIALS,id)||s.trainingDone.includes(id)||s.training&&!s.training.claimed)return false;s.training={id,progress:0,claimed:false,tokens:[]};sim.emit('notice',{message:TRIALS[id].name.toUpperCase()+' · STARTED'});return true;}if(action==='claim'){const t=s.training;if(!t||t.claimed||t.progress<TRIALS[t.id].goal)return false;t.claimed=true;s.trainingDone.push(t.id);p.gold+=250;sim.xp(500);sim.dropNamed('mentor',8);return true;}return false;}
