// Original martial specializations. Base weapon class and its four inputs never change.
const evo=(id,classId,name,role,text,stats,branches)=>({id,classId,name,role,text,stats,branches});
export const EVOLUTIONS=[
 evo('duelist','katana','Steel Duelist','Single-target setups','Basic hits mark one target for 4 seconds (maximum 3). A skill consumes its marks for 15% more damage per mark. Changing targets resets the marks.',[['crit',.025],['damage',.05],['attackSpeed',.03],['health',.04]],[['Measured Finish','perfectMeasure','Consuming three marks guarantees a critical skill hit, unless Resolute forbids critical strikes.'],['Returning Form','resetForm','Consuming marks restores 0.4 seconds of both skill cooldowns per mark.']]),
 evo('windblade','katana','Windblade','Aerial pursuit','Skills gain 30% reach and 25% launch height. Airborne hits deal 20% more damage; grounded hits deal 10% less.',[['aerial',.10],['launch',.10],['move',.04],['range',.04]],[['Upward Cut','updraft','Non-slam skills launch ordinary enemies. Groundbreaker still prevents all launches.'],['Aerial Guard','airGuard','An airborne hit grants a 6% maximum-life barrier for 3 seconds, once per attack pulse.']]),
 evo('strider','twins','Trail Strider','Dodge into burst','Dodges add Momentum, up to 3 stacks for 5 seconds. Your next skill consumes all stacks for 20% more damage per stack.',[['move',.04],['dashCooldown',.05],['dashDamage',.10],['health',.04]],[['Crosswind','crosswind','Each consumed Momentum stack also grants the skill 15% reach.'],['Quick Return','quickReturn','Kills remove 0.25 seconds from dodge cooldown.']]),
 evo('dancer','twins','Blade Dancer','Sweeping multihits','Basic attacks gain 40% wider arcs and 15% attack speed, but deal 10% less damage.',[['attackSpeed',.03],['range',.04],['crit',.025],['health',.04]],[['Full Circle','fullCircle','Basic attacks become circular sweeps with 15% less reach.'],['Encore','encore','Skills gain one additional pulse; each pulse deals 80% damage.']]),
 evo('bulwark','greatsword','Iron Bulwark','Block and retaliation','Gain 12% block chance. Blocking grants a 12% maximum-life barrier for 4 seconds. Deal 10% less hit damage.',[['armor',.10],['block',.02],['health',.05],['regen',.5]],[['Guarded Strike','guardedStrike','Deal 25% more skill damage while a barrier remains.'],['Hold the Line','holdLine','Take 15% less damage while standing still.']]),
 evo('siege','greatsword','Siegebreaker','Expose and crush','Skills expose targets for 4 seconds. Subsequent hits against exposed enemies deal 20% more damage.',[['skillDamage',.08],['knock',.10],['health',.05],['bossDamage',.08]],[['Breach','breach','Hits against exposed bosses generate twice as much guard-break pressure.'],['Aftershock','aftershock','Slam skills strike twice and have 25% greater reach; each pulse deals 70% damage.']]),
 evo('sharpshooter','pistols','Sharpshooter','Stationary precision','Standing still builds Focus over 1.5 seconds. Shots snapshot up to 35% more damage at full Focus. Moving or dodging resets Focus.',[['range',.06],['crit',.025],['critPower',.10],['bossDamage',.08]],[['Clean Line','cleanLine','At full Focus, shots pierce two additional enemies.'],['Patient Aim','patientAim','At full Focus, gain 15% additional critical chance.']]),
 evo('outrider','pistols','Outrider','Mobile close combat','Dodge-follow-up attacks fire two additional pellets with 25% less damage per pellet. Moving while attacking is unrestricted.',[['move',.04],['dashDamage',.10],['dashCooldown',.05],['health',.04]],[['Rolling Reload','rollingReload','Dodging restores 0.5 seconds of both skill cooldowns.'],['Close Quarters','closeQuarters','Hits within 300 distance deal 25% more damage; hits beyond 600 deal 15% less.']])
];
export const EVOLUTION_BY_ID=Object.fromEntries(EVOLUTIONS.map(e=>[e.id,e]));
export const EVOLUTION_NODES=EVOLUTIONS.flatMap(e=>Array.from({length:12},(_,i)=>{const branch=i<4?-1:i<8?0:1,depth=branch<0?i:(i-4)%4,[stat,v]=e.stats[(i+(branch===1?1:0))%4],signature=branch>=0&&depth===3;return {id:e.id+'-'+i,evolution:e.id,name:signature?e.branches[branch][0]:`${['Foundation','Discipline','Refinement','Mastery'][depth]} · ${['Core','Technique','Endurance'][branch+1]}`,requires:i===0?null:i<4?e.id+'-'+(i-1):depth===0?e.id+'-3':e.id+'-'+(i-1),level:i<4?6:signature?15:10,branch,depth,flag:signature?e.branches[branch][1]:null,text:signature?e.branches[branch][2]:null,effects:signature?{}:{[stat]:v*(depth===2?1.5:1)}};}));
export const EVOLUTION_NODE_BY_ID=Object.fromEntries(EVOLUTION_NODES.map(n=>[n.id,n]));
export function evolutionState(p){return p.evolution??={version:1,id:null,nodes:[]};}
export function evolutionUnlock(p){return p.level<6?'Reach level 6.':'';}
export function evolutionBudget(p){return evolutionUnlock(p)?0:2+(p.level>=10?2:0)+(p.level>=15?2:0)+(p.level>=20?2:0);}
export function evolutionError(p,id){if(typeof id!=='string')return 'Unknown evolution node.';const s=evolutionState(p),n=EVOLUTION_NODE_BY_ID[id];if(typeof id!=='string'||!Object.hasOwn(EVOLUTION_NODE_BY_ID,id)||n.evolution!==s.id)return 'Choose a node in your evolution.';if(evolutionUnlock(p))return evolutionUnlock(p);if(s.nodes.includes(id))return 'Already learned.';if(s.nodes.length>=evolutionBudget(p))return 'No evolution points available.';if(p.level<n.level)return 'Requires level '+n.level+'.';if(n.requires&&!s.nodes.includes(n.requires))return 'Learn the preceding node first.';return '';}
export function changeEvolution(p,action,id){if(!['choose','learn','refund','reset'].includes(action)||(action!=='reset'&&typeof id!=='string'))return false;const s=evolutionState(p);if(action==='choose'){const e=EVOLUTION_BY_ID[id];if(typeof id!=='string'||!Object.hasOwn(EVOLUTION_BY_ID,id)||e.classId!==p.classId||evolutionUnlock(p)||s.id===id)return false;s.id=id;s.nodes=[];return true;}if(action==='learn'){if(evolutionError(p,id))return false;s.nodes.push(id);return true;}if(action==='refund'){if(!s.nodes.includes(id)||s.nodes.some(x=>EVOLUTION_NODE_BY_ID[x]?.requires===id))return false;s.nodes=s.nodes.filter(x=>x!==id);return true;}if(action==='reset'&&s.nodes.length){s.nodes=[];return true;}return false;}
export function evolutionBonuses(p){const out={evolution:null,traits:{}};if(!p)return out;const s=evolutionState(p),e=EVOLUTION_BY_ID[s.id];if(!e||e.classId!==p.classId||evolutionUnlock(p))return out;out.evolution=e.id;for(const id of s.nodes){const n=EVOLUTION_NODE_BY_ID[id];if(!n||n.evolution!==e.id)continue;if(n.flag)out.traits[n.flag]=true;for(const [k,v] of Object.entries(n.effects))out[k]=(out[k]||0)+v;}return out;}
