import {HUNTS,HUNT_BY_ID,HUNT_KEEPER,HUNT_RATE,SIGNATURES,SIGNATURE_BY_ID,OUTFITS,DYES,TEMPERS,TEMPER_COST,FRAGMENT_COST,hunterState,rememberAppearance} from './hunt-data.js';
import {makeItem,random,gearScore} from './rpg.js';
import {salvageState} from './salvage.js';
import {allocate,treeState} from './skill-tree.js';
import {changeEvolution} from './evolutions.js';
import {clearBuildRuntime} from './evolution-combat.js';
const nearKeeper=sim=>Math.hypot(sim.player.x-HUNT_KEEPER.x,sim.player.y-HUNT_KEEPER.y)<230;
const safe=sim=>sim.canEditTree();
export function initHunters(sim){const p=sim.profile;if(!p)return;const s=hunterState(p);if(!s.version){for(const i of [...p.inventory,...Object.values(p.equipment)])rememberAppearance(p,i);s.version=1;}}
export function huntError(sim,id,tier='standard'){const h=HUNT_BY_ID[id],p=sim.profile;if(!Object.hasOwn(HUNT_BY_ID,id)||!p||!Object.hasOwn(HUNT_RATE,tier))return 'Unknown hunt or difficulty.';if(sim.huntRun&&!sim.huntRun.completed)return 'Finish or abandon your current hunt first.';if(Math.hypot(sim.player.x-h.entry.x,sim.player.y-h.entry.y)>230)return 'Walk to the marked boss lair.';if(sim.player.dead)return 'Revive before starting a dungeon.';return '';}
export function signatureItem(sim,id,level){const spec=SIGNATURE_BY_ID[id];if(!spec||spec.classId!==sim.profile.classId)return null;const h=HUNT_BY_ID[spec.hunt],item=makeItem(sim.profile.id+'-'+sim.runId+'-hunt-'+(++sim.itemSerial),'weapon',level||h.level,'legendary',spec.classId,'hunt-'+h.id);return {...item,name:spec.name,huntSignature:id,locked:true};}
function spawnStage(sim,index){const r=sim.huntRun,h=HUNT_BY_ID[r.id],point=h.stages[index],group='hunt-'+h.id+'-'+r.serial+'-'+index;r.stage=index;r.fighting=true;r.group=group;const units=index<2?[...h.packs[index]]:[h.boss,'spider',h.id==='convoy'?'archer':h.id==='cinder'?'golem':'spider'];if(r.tier==='veteran')units.push(index===2?'shieldguard':'ridgebeast');sim.groups.push({id:group,...point,aggro:600,alert:false,cleared:false});units.forEach((type,i)=>{const e=sim.addEnemy(type,point.x+(i%3-1)*115,point.y+Math.floor(i/3)*115,group);e.huntId=r.id;e.level=h.level+(r.tier==='veteran'?4:0);e.hp=Math.round(e.hp*(1+e.level*.12)*(r.tier==='veteran'?1.8:1)*(e.boss?.85:1));e.maxHp=e.hp;e.damageScale=r.tier==='veteran'?1.35:1;e.huntVeteran=r.tier==='veteran';if(e.boss)e.displayName=h.bossName;});sim.emit('notice',{message:index===2?h.bossName+' · '+h.tactic:'HUNT · '+(index===0?'Clear the approach':'Secure the work site')});}
export function huntObjective(sim){const r=sim.huntRun;if(sim.training)return {x:sim.training.x,y:sim.training.y,detail:'TRAINING · '+Math.round(sim.training.damage/Math.max(1,sim.time-sim.training.start))+' DPS · Menu → Hunts to finish'};if(!r||r.completed)return null;const h=HUNT_BY_ID[r.id],living=sim.enemies.filter(e=>e.group===r.group&&!e.dead),nearest=living.slice().sort((a,b)=>Math.hypot(a.x-sim.player.x,a.y-sim.player.y)-Math.hypot(b.x-sim.player.x,b.y-sim.player.y))[0],point=r.stage<0?h.entry:r.objectiveReady?h.stages[1]:nearest||h.stages[r.stage];return {x:point.x,y:point.y,navKey:'hunt-'+r.serial+'-'+r.stage,movingTarget:!!nearest&&!r.objectiveReady,detail:h.name+' · '+(r.stage<0?'Follow the road to the marked entrance':r.objectiveReady?h.objective:r.stage===2?'3/3 · Defeat '+h.bossName+' and its escorts':(r.stage===0?'1/3 · Clear the approach':'2/3 · Clear the work site')+' · '+sim.enemies.filter(e=>e.group===r.group&&!e.dead).length+' enemies left')};}
export function huntInteract(sim){const r=sim.huntRun;if(!r||!r.objectiveReady||sim.player.dead)return false;const h=HUNT_BY_ID[r.id],at=h.stages[1];if(Math.hypot(sim.player.x-at.x,sim.player.y-at.y)>230)return false;r.objectiveReady=false;r.objectiveDone=true;spawnStage(sim,2);sim.emit('chest',{x:at.x,y:at.y,id:'hunt-objective'});return true;}
export function tickHunt(sim){const r=sim.huntRun;if(!r||r.completed||sim.player.dead)return;const h=HUNT_BY_ID[r.id];if(r.objectiveReady){r.objectiveReady=false;r.objectiveDone=true;spawnStage(sim,2);return;}if(r.stage<0){if(Math.hypot(sim.player.x-h.entry.x,sim.player.y-h.entry.y)<230)spawnStage(sim,0);return;}if(!r.fighting||sim.enemies.some(e=>e.group===r.group&&!e.dead))return;r.fighting=false;if(r.stage===0){spawnStage(sim,1);return;}if(r.stage===1){r.objectiveDone=true;spawnStage(sim,2);return;}
 r.completed=true;const s=hunterState(sim.profile);s.destination=null;s.clears[h.id]??={standard:0,veteran:0};s.clears[h.id][r.tier]++;s.fragments[h.id]=(s.fragments[h.id]||0)+(r.tier==='veteran'?3:2);salvageState(sim.profile);sim.profile.materials.scrap+=r.tier==='veteran'?60:35;sim.profile.materials.alloy+=r.tier==='veteran'?8:4;if(!s.outfits.includes(h.outfit))s.outfits.push(h.outfit);if(HUNTS.every(h=>s.clears[h.id]?.veteran)&&!s.outfits.includes('master'))s.outfits.push('master');const spec=SIGNATURES.find(i=>i.hunt===h.id&&i.classId===sim.profile.classId),point=h.stages[2];if(random(sim)<HUNT_RATE[r.tier]){const item=signatureItem(sim,spec.id,h.level+(r.tier==='veteran'?4:0));const drop=sim.drop(point.x,point.y,'equipment');drop.item=item;sim.emit('signatureDrop',{x:point.x,y:point.y,name:item.name});}sim.chests.push({id:'hunt-cache-'+r.serial,name:h.name+' reward chest',...point,x:point.x+140,guards:r.group,gold:r.tier==='veteran'?300:160,heal:45,upgrade:'none',opened:false});sim.xp(r.tier==='veteran'?650:350);s.lastReport={id:h.id,tier:r.tier,seconds:Math.round(sim.time-r.started),text:h.ending};sim.emit('notice',{message:'HUNT COMPLETE · '+(r.tier==='veteran'?3:2)+' fragments · '+OUTFITS.find(o=>o.id===h.outfit).name+' appearance unlocked'});
}
export function hunterAction(sim,action,id,value){const p=sim.profile;if(!p||typeof action!=='string')return false;const s=hunterState(p);
 if(action==='trackDungeon'){if(!Object.hasOwn(HUNT_BY_ID,id)||sim.huntRun&&!sim.huntRun.completed)return false;s.destination=id;return true;}
 if(action==='start'){if(huntError(sim,id,value))return false;sim.enemies=sim.enemies.filter(e=>!e.huntId&&!e.trainingDummy);sim.groups=sim.groups.filter(g=>!g.id.startsWith('hunt-'));sim.chests=sim.chests.filter(c=>!c.id.startsWith('hunt-cache-')||!c.opened);sim.training=null;s.destination=id;sim.huntRun={id,tier:value,serial:++sim.serial,stage:-1,fighting:false,started:sim.time};return true;}
 if(action==='abandon'){if(!sim.huntRun||!safe(sim))return false;sim.enemies=sim.enemies.filter(e=>!e.huntId);sim.groups=sim.groups.filter(g=>!g.id.startsWith('hunt-'));sim.huntRun=null;return true;}
 if(action==='filter'){if(!['all','useful','signature'].includes(id))return false;s.lootFilter=id;return true;}
 if(action==='look'){if(!safe(sim)||!value||typeof value!=='object'||!DYES.some(d=>d.id===value.dye)||value.outfit&&!s.outfits.includes(value.outfit))return false;const slots={};for(const slot of Object.keys(p.equipment)){const key=value.slots?.[slot]||'',item=s.appearances[key];if(key&&(!item||item.slot!==slot||item.classId&&item.classId!==p.classId))return false;slots[slot]=key;}s.cosmetic={outfit:value.outfit||null,dye:value.dye,slots};return true;}
 if(action==='cosmetic'){if(!safe(sim))return false;if(id==='outfit'){if(value!==''&&!s.outfits.includes(value))return false;s.cosmetic.outfit=value||null;}else if(id==='dye'){if(!DYES.some(d=>d.id===value))return false;s.cosmetic.dye=value;}else{if(!Object.hasOwn(p.equipment,id))return false;const item=s.appearances[value];if(value&&(!item||item.slot!==id||item.classId&&item.classId!==p.classId))return false;s.cosmetic.slots[id]=value;}return true;}
 if(action==='craft'){const spec=SIGNATURE_BY_ID[id];if(!spec||spec.classId!==p.classId||(s.fragments[spec.hunt]||0)<FRAGMENT_COST||p.inventory.length>=30)return false;const item=signatureItem(sim,id,s.clears[spec.hunt]?.veteran?HUNT_BY_ID[spec.hunt].level+4:HUNT_BY_ID[spec.hunt].level);s.fragments[spec.hunt]-=FRAGMENT_COST;p.inventory.push(item);rememberAppearance(p,item);return true;}
 if(action==='temper'){const item=[...p.inventory,...Object.values(p.equipment)].find(i=>i&&String(i.id)===String(id));if(!safe(sim)||!item||!Object.hasOwn(TEMPERS,value)||item.temper===value)return false;salvageState(p);if(Object.entries(TEMPER_COST).some(([k,n])=>p.materials[k]<n))return false;for(const [k,n] of Object.entries(TEMPER_COST))p.materials[k]-=n;item.temper=value;item.locked=true;sim.applyStats();return true;}
 if(action==='savePreset'){const index=Number(id);if(!safe(sim)||!Number.isInteger(index)||index<0||index>2)return false;s.presets[index]={equipment:Object.fromEntries(Object.entries(p.equipment).map(([k,i])=>[k,i?.id||null])),tree:structuredClone(treeState(p)),evolution:structuredClone(p.evolution||{version:1,id:null,nodes:[]})};for(const i of Object.values(p.equipment))if(i)i.locked=true;return true;}
 if(action==='loadPreset'){const index=Number(id),preset=s.presets[index];if(!safe(sim)||!Number.isInteger(index)||index<0||index>2||!preset)return false;const all=[...p.inventory,...Object.values(p.equipment).filter(Boolean)],chosen={};for(const [slot,itemId] of Object.entries(preset.equipment)){const item=all.find(i=>String(i.id)===String(itemId));if(itemId&&(!item||item.slot!==slot||item.requiredLevel>p.level||item.classId&&item.classId!==p.classId))return false;chosen[slot]=item||null;}const selected=new Set(Object.values(chosen).filter(Boolean).map(i=>String(i.id))),remaining=all.filter(i=>!selected.has(String(i.id)));if(remaining.length>30)return false;const candidate=structuredClone(p);candidate.skillTree={version:1,nodes:[]};for(const node of preset.tree.nodes)if(!allocate(candidate,node))return false;candidate.evolution={version:1,id:null,nodes:[]};if(preset.evolution.id){if(!changeEvolution(candidate,'choose',preset.evolution.id))return false;for(const node of preset.evolution.nodes)if(!changeEvolution(candidate,'learn',node))return false;}p.inventory=remaining;p.equipment=chosen;p.skillTree=candidate.skillTree;p.evolution=candidate.evolution;sim.applyStats();clearBuildRuntime(sim);sim.player.huntRhythm=0;return true;}
 if(action==='train'){if(!nearKeeper(sim)||!safe(sim)||sim.huntRun&&!sim.huntRun.completed)return false;sim.enemies=sim.enemies.filter(e=>!e.trainingDummy);const e=sim.addEnemy('brute',5910,1000);e.trainingDummy=true;e.displayName='PRACTICE TARGET';e.active=true;e.hp=e.maxHp=1000000000;sim.training={x:e.x,y:e.y,start:sim.time,damage:0,hits:0};return true;}
 if(action==='endTraining'){if(!sim.training)return false;sim.enemies=sim.enemies.filter(e=>!e.trainingDummy);sim.training=null;sim.bullets=[];return true;}return false;
}
export function signatureAttack(sim,def,kind){const id=sim.profile?.equipment.weapon?.huntSignature;if(!id)return def;const d={...def},p=sim.player;d.huntSignature=id;
 if(id==='gale'){const perfect=kind==='dashAttack'&&p.huntPerfectUntil>sim.time;d.damage*=perfect?1.5:.9;if(perfect){d.reach*=1.7;d.shape='rush';d.lunge=600;}}
 if(id==='ember'){if(kind==='skill'){d.pulses=(d.pulses||1)+1;d.damage*=.75;}else d.damage*=.9;}
 if(id==='copper'){const stacks=p.huntRhythmUntil>sim.time?p.huntRhythm||0:0;if(kind==='skill'){d.damage*=1+stacks*.1;p.huntRhythm=0;}else{d.duration/=1+stacks*.06;d.active/=1+stacks*.06;}}
 if(id==='fault'){d.damage*=d.slam?1.4:.85;if(d.slam)d.reach*=1.5;}
 if(id==='railcar'){d.damage*=1.2;d.duration*=1.2;d.active*=1.2;d.pierce=sim.build?.keys.volley?1:(d.pierce||1)+2;}
 if(id==='relay'&&kind==='skill')d.damage*=.85;
 if(id==='glasswing'){d.damage*=.9;d.pierce=1;d.ricochet=1;}
 if(id==='outrun'){d.damage*=kind==='dashAttack'?1.65:.85;if(kind==='dashAttack'){d.pellets=(d.pellets||1)+2;d.spread=Math.max(d.spread||0,.35);}}
 return d;
}
export function signatureMultiplier(sim,a,e){switch(a.def.huntSignature){case 'silk':return e.z>25?1.5:.9;case 'breach':return e.broken>0||e.shieldBroken>0?1.6:.9;case 'mercy':return e.hp/e.maxHp<.3?1.7:.9;case 'anchor':return sim.player.moving?.85:1.35;default:return 1;}}
export function afterSignatureHit(sim,a,e,damage){const p=sim.player,id=a.def.huntSignature;if(e.trainingDummy&&sim.training){sim.training.damage+=damage;sim.training.hits++;}if(id==='copper'&&['normal','juggle'].includes(a.kind)){if(p.huntLastTarget!==e.id){p.huntRhythm=Math.min(5,(p.huntRhythmUntil>sim.time?p.huntRhythm||0:0)+1);p.huntRhythmUntil=sim.time+4;}p.huntLastTarget=e.id;}if(id==='relay'&&['normal','juggle'].includes(a.kind)){const token=a.id+':'+a.pulses;if(p.huntRelayToken!==token){p.skillCooldowns=p.skillCooldowns.map(v=>Math.max(0,v-.2));p.huntRelayToken=token;}}}
export function ricochet(sim,b,e){if(!(b.attack.def.ricochet>0))return false;const next=sim.enemies.filter(n=>!n.dead&&!b.hit.has(n.id)&&Math.hypot(n.x-e.x,n.y-e.y)<350).sort((a,c)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(c.x-e.x,c.y-e.y))[0];if(!next)return false;const angle=Math.atan2(next.y-e.y,next.x-e.x);b.x=e.x;b.y=e.y;b.vx=Math.cos(angle)*1900;b.vy=Math.sin(angle)*1900;b.angle=angle;b.remaining=400;b.pierce=1;b.attack={...b.attack,def:{...b.attack.def,ricochet:0,damage:b.attack.def.damage*.65}};sim.emit('shot',{x:e.x,y:e.y,angle});return true;}
export function lootUseful(p,item){if(!item)return false;if(item.huntSignature||item.signature||item.locked)return true;return (!item.classId||item.classId===p.classId)&&gearScore(item)>gearScore(p.equipment[item.slot]);}
