export const HUNT_KEEPER={id:'c2-hunts',name:'Nadia · Hunt keeper',role:'The Hunter’s Road',x:5730,y:1020,color:'#729e89'};
export const HUNTS=[
 {id:'crystal',name:'Crystal Ravine',boss:'matriarch',bossName:'The Prism Broodmother',color:'#8eddd4',min:6,level:8,entry:{x:6090,y:-1560},stages:[{x:5630,y:-1770},{x:5180,y:-1940},{x:4830,y:-2220}],packs:[['spider','spider','ridgebeast','spider','spider'],['spider','spider','spider','ridgebeast','spider']],objective:'Break the crystal web anchors',action:'BREAK WEB ANCHORS',story:'Idris’s survey crew found a second road beneath the ravine. Crystal spiders have sealed the cutting with web anchors. Nadia needs the passage reopened before the next medicine wagon arrives.',tactic:'Clear the web anchors to weaken the broodmother. Her shard circles slow you; move before they fill. Skills break her guard and expose her for 2 seconds.',ending:'The survey crew can reach the cutting again. Nadia sends the first medicine wagon down the reopened road.',outfit:'surveyor'},
 {id:'cinder',name:'Cinder Quarry',boss:'colossus',bossName:'The Quarry Furnace',color:'#efad72',min:8,level:10,entry:{x:8860,y:-650},stages:[{x:9400,y:-550},{x:10030,y:-270},{x:10600,y:250}],packs:[['golem','spider','golem','ridgebeast'],['golem','golem','spider','spider']],objective:'Open the cooling channel',action:'OPEN COOLING CHANNEL',story:'Vey abandoned a quarry with its pressure lines still running. Yusuf traced the heat to a stone furnace engine. Open the cooling channel before it destroys the workers’ homes below.',tactic:'The cooling channel weakens the furnace. Dodge out of orange heat circles, then attack during its exposed recovery. Veteran difficulty adds a shield escort.',ending:'The cooling channel carries the heat away. The quarry workers return to recover their tools and rebuild.',outfit:'cinderworker'},
 {id:'convoy',name:'The Broken Convoy',boss:'warden',bossName:'Captain of the Last Toll',color:'#d9bc7a',min:6,level:8,entry:{x:7150,y:1340},stages:[{x:7540,y:1650},{x:8130,y:2150},{x:8700,y:2430}],packs:[['scout','shieldguard','archer','raider','raider'],['shieldguard','archer','raider','scout','raider']],objective:'Release the captured travellers',action:'RELEASE THE TRAVELLERS',story:'Hadrik’s remaining guards have taken a convoy off the open road. Salma recognises the wagon cloth: these are the families who supplied the valley during the shortage. Bring them home.',tactic:'Interrupt signal scouts before they call reinforcements. Skills or attacks from behind beat shields. Release the travellers before confronting the captain.',ending:'The travellers leave together under Salma’s escort. Their wagons carry grain again instead of prisoners.',outfit:'roadkeeper'}
];
export const HUNT_BY_ID=Object.fromEntries(HUNTS.map(h=>[h.id,h]));
export const HUNT_POLYGONS=[[[6150,-1300],[6600,-1550],[5800,-1900],[5600,-2600],[4800,-2700],[4300,-2300],[4600,-1500],[5500,-1350]],[[8660,-1000],[9300,-1050],[10400,-900],[11200,-100],[10800,800],[10000,900],[9550,100],[8750,-400]],[[6700,1100],[7200,650],[7870,1230],[8400,1250],[9220,2000],[9040,2700],[8130,2930],[7420,2500],[7060,1720]]];
export const SIGNATURES=[
 ['gale','Gale Edge','katana','crystal','Dodge follow-up','Dodge during the final 0.32 seconds of a nearby enemy wind-up, then immediately attack: 70% longer reach and 50% more damage.','Other attacks deal 10% less damage.','Mobile precision'],
 ['silk','Silk Reaver','twins','crystal','Airborne attacks','Deal 50% more damage to airborne enemies. Launch them with your skill, then continue attacking.','Deal 10% less damage to grounded enemies.','Aerial combos'],
 ['breach','Siegebreaker','greatsword','crystal','Guard breaking','Deal 60% more damage while an enemy’s guard is broken. Use skills to stagger bosses.','Deal 10% less damage before the guard breaks.','Boss openings'],
 ['glasswing','Glasswing Pair','pistols','crystal','Ricochet shots','Each bullet can ricochet to one additional enemy within 350 distance, dealing 65% of the first hit’s damage.','The initial hit deals 10% less damage. Ricochets replace piercing.','Crowd clearing'],
 ['ember','Emberfall','katana','cinder','Class skills','Skills strike one extra time. Each strike deals 75% of its normal damage.','Basic attacks deal 10% less damage.','Repeated skill strikes'],
 ['copper','Copper Fangs','twins','cinder','Alternating targets','Basic hits on a different enemy build a rhythm stack. Each stack grants 6% attack speed, up to 30%, for 4 seconds.','Skills spend all rhythm stacks. Each spent stack grants 10% more skill damage.','Target switching'],
 ['fault','Quarry Splitter','greatsword','cinder','Slam skill','Slams gain 50% reach and 40% damage.','Other attacks deal 15% less damage.','Wide area control'],
 ['railcar','Rivet Drivers','pistols','cinder','Piercing shots','Shots pierce two extra enemies and deal 20% more damage.','Attack animations are 20% slower. The Volley keystone still overrides pierce.','Lined-up targets'],
 ['mercy','Road’s Answer','katana','convoy','Finishing attacks','Deal 70% more damage to enemies below 30% health.','Deal 10% less damage above that threshold.','Finishing bosses'],
 ['relay','Courier Blades','twins','convoy','Basic-to-skill flow','Each basic attack pulse that hits reduces both skill cooldowns by 0.2 seconds.','Skills deal 15% less damage.','Frequent skills'],
 ['anchor','Convoy Anchor','greatsword','convoy','Standing your ground','Deal 35% more damage while standing still.','Deal 15% less damage while moving.','Deliberate heavy hits'],
 ['outrun','Outrider’s Reply','pistols','convoy','Dodge follow-up','Attacks immediately after a dodge deal 65% more damage and fire two additional spread rounds.','All other attacks deal 15% less damage.','Close mobile bursts']
].map(([id,name,classId,hunt,ability,effect,tradeoff,style])=>({id,name,classId,hunt,ability,effect,tradeoff,style}));
export const SIGNATURE_BY_ID=Object.fromEntries(SIGNATURES.map(s=>[s.id,s]));
export const OUTFITS=[{id:'roadkeeper',name:'Roadkeeper',hunt:'convoy',steel:'#b29b70',cloth:'#425d65',shape:0},{id:'surveyor',name:'Glass Surveyor',hunt:'crystal',steel:'#8eccc7',cloth:'#304f60',shape:1},{id:'cinderworker',name:'Cinderworker',hunt:'cinder',steel:'#ba8664',cloth:'#603e35',shape:2},{id:'master',name:'Master Hunter',hunt:'master',steel:'#dfc58b',cloth:'#283d40',shape:3}];
export const DYES=[{id:'original',name:'Original',color:null},{id:'indigo',name:'Indigo',color:'#343e68'},{id:'cedar',name:'Cedar',color:'#365a45'},{id:'saffron',name:'Saffron',color:'#977040'},{id:'crimson',name:'Crimson',color:'#6c303c'}];
export const TEMPERS={swift:{name:'Swift handling',stat:'attackSpeed',value:.06,text:'6% increased attack speed. Makes attack animations shorter; shares the 40% atlas cap.'},force:{name:'Forceful technique',stat:'skillDamage',value:.08,text:'8% increased skill damage. Adds to other increased skill damage bonuses.'},guard:{name:'Reinforced lining',stat:'armor',value:.10,text:'10% increased armor. Adds to other increased armor bonuses.'}};
export const TEMPER_COST={scrap:60,alloy:8};
export const HUNT_RATE={standard:.30,veteran:.45};
export const FRAGMENT_COST=6;
export function hunterState(p){if(!p)return null;const s=p.hunters??={};s.clears??={};s.fragments??={};s.discovered??=[];s.appearances??={};s.outfits??=[];s.cosmetic??={outfit:null,dye:'original',slots:{}};s.presets??=[null,null,null];s.lootFilter??='all';return s;}
export function rememberAppearance(p,item){if(!p||!item)return;const s=hunterState(p),tier=Math.min(2,Math.floor(((item.level||1)-1)/3)),key=[item.slot,item.classId||'any',item.rarity,tier,item.huntSignature||''].join(':');s.appearances[key]??={...item,stats:{...item.stats},id:key};if(item.huntSignature&&!s.discovered.includes(item.huntSignature))s.discovered.push(item.huntSignature);}
export function visualProfile(p){if(!p)return p;const s=hunterState(p),c=s.cosmetic,o=OUTFITS.find(o=>o.id===c.outfit&&s.outfits.includes(o.id)),dye=DYES.find(d=>d.id===c.dye)?.color;const equipment=Object.fromEntries(Object.entries(p.equipment).map(([slot,item])=>{const chosen=s.appearances[c.slots[slot]],visual=chosen&&chosen.slot===slot&&(!chosen.classId||chosen.classId===p.classId)?chosen:item;if(!visual&&!o)return [slot,null];if(slot==='weapon'&&!visual)return [slot,null];return [slot,{...(visual||{slot,rarity:'epic',level:8}),id:(visual?.id||slot)+':'+(o?.id||'')+':'+(dye||''),visualSteel:slot!=='weapon'&&!chosen?o?.steel:null,visualCloth:dye||(slot!=='weapon'&&!chosen?o?.cloth:null),outfitShape:slot!=='weapon'&&!chosen?o?.shape:undefined}];}));return {...p,equipment};}
