import {NAMED_GEAR,NAMED_POOLS} from './named-loot.js';
import {treeBonuses} from './skill-tree.js';
export const CLASSES={katana:{name:'Vanguard',weapon:'Katana',role:'Precise cuts, launcher and sweeping control'},twins:{name:'Skirmisher',weapon:'Twin blades',role:'Fast pursuit and aerial pressure'},greatsword:{name:'Breaker',weapon:'Greatsword',role:'Heavy stagger and guard breaking'},pistols:{name:'Gunslinger',weapon:'Pistol',role:'Mobile fire and piercing shots'}};
export const SLOTS=['weapon','head','chest','hands','legs','feet'];
export const RARITIES=[{id:'common',name:'Common',color:'#c4c6bf',mult:1},{id:'uncommon',name:'Uncommon',color:'#82c98e',mult:1.3},{id:'rare',name:'Rare',color:'#70b5f0',mult:1.7},{id:'epic',name:'Epic',color:'#c59cf4',mult:2.2},{id:'legendary',name:'Legendary',color:'#f46b58',mult:2.7}];
export const REGIONS={approach:{name:'Marigold Downs',min:1,max:2},quarry:{name:'Cedar Hollow / Apricot Orchards',min:2,max:4},garrison:{name:'Willowbend / Wind Stairs',min:3,max:5},keep:{name:'Cloudwater Reservoir',min:5,max:7}};
Object.assign(REGIONS,{terraces:{name:'Amberstep / Glassroot',min:10,max:12},highlands:{name:'Whitewind / Cinderwash',min:13,max:16},fortress:{name:'Brasswater Fortress',min:17,max:20}});
export function regionFor(group){if(group?.startsWith('wild:'))return group.split(':')[1];if(group?.startsWith('hunt-'))return group.includes('cinder')?'fortress':'highlands';if(group?.startsWith('c2-'))return ['c2-fort','c2-colossus'].includes(group)?'fortress':['c2-snow','c2-rescue','c2-cinder','c2-forge'].includes(group)?'highlands':'terraces';return ['lookouts','yard'].includes(group)?'approach':['depot','woodland','quarry'].includes(group)?'quarry':['barracks','captain','bridgePatrol','millDefense'].includes(group)?'garrison':'keep';}
export const LOOT_TABLES={raider:{chance:.28,rarities:[70,24,5.5,.5,0],slots:['weapon','hands','feet','legs']},archer:{chance:.34,rarities:[62,30,7,1,0],slots:['weapon','head','feet']},brute:{chance:.65,rarities:[45,38,15,2,0],slots:['chest','legs','hands','weapon']},captain:{chance:1,rolls:2,rarities:[0,45,50,4.7,.3],slots:['weapon','chest','head']},commander:{chance:1,rolls:3,rarities:[0,15,65,19,1],slots:SLOTS},chest:{chance:1,rolls:2,rarities:[35,45,18,1.9,.1],slots:SLOTS}};
for(const [id,base] of Object.entries({shieldguard:'brute',scout:'archer',spider:'raider',golem:'brute',ridgebeast:'raider',warden:'captain',matriarch:'commander',colossus:'commander'}))LOOT_TABLES[id]=LOOT_TABLES[base];
export const QUESTS=[{id:'road',title:'Clear the road',text:'Defeat 5 raiders in the Marigold Downs.',goal:5,xp:120,gold:60,requires:null},{id:'supplies',title:'Recover the supplies',text:'Open 2 guarded chests anywhere in Windward Vale.',goal:2,xp:220,gold:100,requires:'road'},{id:'captain',title:'Break the blockade',text:'Defeat the Toll Captain.',goal:1,xp:350,gold:160,requires:'supplies'},{id:'keep',title:'Secure Windward Vale',text:'Defeat the Marshal Rook and open his chest.',goal:2,xp:650,gold:250,requires:'captain'}];
export const XP_REQUIRED=level=>Math.round(100+level*70+level*level*12);
export function random(sim){sim.rng=(Math.imul(sim.rng,1664525)+1013904223)>>>0;return sim.rng/4294967296;}
export function itemStats(slot,level,rarity){const m=RARITIES.find(r=>r.id===rarity)?.mult||1;return slot==='weapon'?{power:Math.round((3+level*2)*m),armor:0,health:0}:{power:slot==='hands'?Math.round(level*m):0,armor:Math.round((2+level*1.3)*m),health:Math.round((5+level*3)*m)};}
export function makeItem(id,slot,level,rarity,classId,region){const base={weapon:CLASSES[classId].weapon,head:'Guard hood',chest:'Field armor',hands:'Grips',legs:'Greaves',feet:'Trail boots'}[slot];return{id,slot,level,requiredLevel:Math.max(1,level-1),rarity,classId:slot==='weapon'?classId:null,name:(rarity==='legendary'?'Masterwork ':rarity==='epic'?"Commander’s ":rarity==='rare'?'Honed ':rarity==='uncommon'?'Tempered ':'')+base,stats:itemStats(slot,level,rarity),region};}
export function newProfile(id,name,classId){return{schema:1,id,name,classId,level:1,xp:0,gold:0,inventory:[],equipment:Object.fromEntries(SLOTS.map(s=>[s,s==='weapon'?makeItem(id+'-starter','weapon',1,'common',classId,'outpost'):null])),quests:Object.fromEntries(QUESTS.map(q=>[q.id,{status:q.id==='road'?'active':'locked',progress:0}])),kills:0};}
export function stats(profile){const total={power:0,armor:0,health:240+(profile.level-1)*20};for(const item of Object.values(profile.equipment))if(item){total.power+=item.stats.power;total.armor+=item.stats.armor;total.health+=item.stats.health;}const b=treeBonuses(profile);total.power+=(b.damage||0)*100;total.health=Math.round(total.health*(1+(b.health||0))*(b.keys.glass?.65:1)*(b.keys.sustain?.9:1));total.armor=Math.round(total.armor*(1+(b.armor||0))*(b.keys.fortress?1.7:1));return total;}
export function grantXP(profile,amount){profile.xp+=amount;let levels=0;while(profile.level<20&&profile.xp>=XP_REQUIRED(profile.level)){profile.xp-=XP_REQUIRED(profile.level);profile.level++;levels++;}if(profile.level===20)profile.xp=0;return levels;}
export function rollEquipment(sim,type,group){const table=LOOT_TABLES[type],region=REGIONS[regionFor(group)],items=[];for(let i=0;i<(table.rolls||1);i++){if(random(sim)>=table.chance)continue;let roll=random(sim)*100,index=0;for(;index<RARITIES.length-1;index++){if(roll<table.rarities[index])break;roll-=table.rarities[index];}const slot=table.slots[Math.floor(random(sim)*table.slots.length)],level=region.min+Math.floor(random(sim)*(region.max-region.min+1)),classId=random(sim)<.8?sim.profile.classId:Object.keys(CLASSES)[Math.floor(random(sim)*4)];items.push(makeItem(sim.profile.id+'-'+sim.runId+'-'+(++sim.itemSerial),slot,level,RARITIES[index].id,classId,regionFor(group)));}return items;}

export const gearScore=item=>item?Math.round(item.stats.power*4+item.stats.armor*2+item.stats.health*.25):0;

export function makeNamedItem(sim,key,level=8){const n=NAMED_GEAR[key];if(!n)return null;const item=makeItem(sim.profile.id+'-'+sim.runId+'-named-'+(++sim.itemSerial),n.slot,level,'epic',sim.profile.classId,'fortress');item.name=n.name+(n.slot==='weapon'?' · '+CLASSES[sim.profile.classId].weapon:'');item.signature=key;item.passiveKey=n.key;return item;}
export function rollNamed(sim,type){const pool=NAMED_POOLS[type];return pool&&random(sim)<.25?makeNamedItem(sim,pool[Math.floor(random(sim)*pool.length)],type==='warden'?8:type==='matriarch'?9:12):null;}
