import {gearScore} from './rpg.js';
export const MATERIALS={scrap:{name:'Iron fragments',color:'#acbdc8'},alloy:{name:'Tempered alloy',color:'#dcba79'},crystal:{name:'Prismatic cores',color:'#b7a0e5'}};
export const AUTO_RARITIES=['common','uncommon','rare'];
export const itemKey=id=>String(id);
export function salvageState(p){if(!p)return null;p.materials??={scrap:0,alloy:0,crystal:0};for(const k of Object.keys(MATERIALS))p.materials[k]??=0;p.autoSalvage??={enabled:false,rarities:['common','uncommon']};return p.autoSalvage;}
export function salvageYield(i){const tier=Math.max(0,['common','uncommon','rare','epic','legendary'].indexOf(i.rarity)),level=Math.max(1,Math.min(100,i.level||1));return {scrap:(2+tier)*Math.ceil(level/3),alloy:tier?Math.ceil(level/4)*tier:0,crystal:tier>=3?tier-2:0};}
export function materialText(m){return Object.entries(MATERIALS).filter(([k])=>m[k]>0).map(([k,v])=>`${m[k]} ${v.name}`).join(' · ')||'No materials';}
export function protectedItem(i){return !i||!!i.locked||!!i.signature||!!i.huntSignature||!!i.passiveKey||(i.enhancement||0)>0;}
export function isUpgrade(p,i){if(i.classId&&i.classId!==p.classId)return false;const score=gearScore(i);if(score<=gearScore(p.equipment[i.slot]))return false;const best=p.inventory.filter(n=>n.slot===i.slot&&(!n.classId||n.classId===p.classId)).reduce((a,n)=>!a||gearScore(n)>gearScore(a)?n:a,null);return !best||score>gearScore(best)||itemKey(best.id)===itemKey(i.id);}
export function matchesSalvage(p,i){const s=salvageState(p);return !!i&&s.rarities.includes(i.rarity)&&!protectedItem(i)&&!isUpgrade(p,i);}
export function autoSalvages(p,i){return !!p&&salvageState(p).enabled&&matchesSalvage(p,i);}
export function validSalvageSelection(p,ids){if(!Array.isArray(ids))return [];const byId=new Map((p?.inventory||[]).map(i=>[itemKey(i.id),i]));const seen=new Set(),out=[];for(const id of ids){const key=itemKey(id),item=byId.get(key);if(!item||protectedItem(item)||seen.has(key))continue;seen.add(key);out.push(key);if(out.length===30)break;}return out;}
export function salvagePreview(p,ids){if(!Array.isArray(ids)||!ids.length||ids.length>30||new Set(ids.map(itemKey)).size!==ids.length)return null;const items=ids.map(id=>p.inventory.find(i=>itemKey(i.id)===itemKey(id)));if(items.some(i=>!i))return null;if(items.some(protectedItem))return null;const materials={scrap:0,alloy:0,crystal:0};for(const i of items){const y=salvageYield(i);for(const k of Object.keys(materials))materials[k]+=y[k];}return {items,materials};}
export function grantMaterials(p,items){salvageState(p);const materials={scrap:0,alloy:0,crystal:0};for(const i of items){const y=salvageYield(i);for(const k of Object.keys(materials)){materials[k]+=y[k];p.materials[k]+=y[k];}}return materials;}
export function salvageItems(sim,ids){if(!sim.profile)return false;const preview=salvagePreview(sim.profile,ids);if(!preview)return false;const set=new Set(ids.map(itemKey));sim.profile.inventory=sim.profile.inventory.filter(i=>!set.has(itemKey(i.id)));grantMaterials(sim.profile,preview.items);sim.emit('notice',{message:'SALVAGED · '+materialText(preview.materials)});return true;}
export function salvageConfig(sim,enabled,rarities){if(!sim.profile||typeof enabled!=='boolean'||!Array.isArray(rarities)||rarities.length>3||rarities.some(r=>!AUTO_RARITIES.includes(r))||new Set(rarities).size!==rarities.length)return false;salvageState(sim.profile);sim.profile.autoSalvage={enabled,rarities:[...rarities]};return true;}
export function lockItem(sim,id){const p=sim.profile,i=p?.inventory.find(i=>itemKey(i.id)===itemKey(id))||Object.values(p?.equipment||{}).find(i=>i&&itemKey(i.id)===itemKey(id));if(!i)return false;i.locked=!i.locked;return true;}
export const enhanceCost=i=>{const rank=(i.enhancement||0)+1;return {scrap:rank*(6+Math.ceil(i.level/2)),alloy:rank>=2?rank:0,crystal:rank>=4?1:0};};
export function enhancePreview(i){const base=i.baseStats||i.stats,rank=(i.enhancement||0)+1;return Object.fromEntries(Object.entries(base).map(([k,v])=>[k,v>0?Math.max(v+rank,Math.round(v*(1+rank*.08))):0]));}
export function enhanceItem(sim,id){const p=sim.profile;if(!p||!sim.canEditTree())return false;salvageState(p);const i=p.inventory.find(i=>itemKey(i.id)===itemKey(id))||Object.values(p.equipment).find(i=>i&&itemKey(i.id)===itemKey(id));if(!i||(i.enhancement||0)>=5)return false;const cost=enhanceCost(i);if(Object.keys(cost).some(k=>p.materials[k]<cost[k]))return false;const next=enhancePreview(i);i.baseStats??={...i.stats};for(const k of Object.keys(cost))p.materials[k]-=cost[k];i.enhancement=(i.enhancement||0)+1;i.stats=next;sim.applyStats();sim.emit('notice',{message:i.name+' +'+i.enhancement});return true;}
