import {HUNT_KEEPER} from './hunt-data.js';
import {CARAVAN_PEOPLE} from './chapter-two-data.js';
import {caravanCurrent,caravanAdvance} from './caravan-story.js';
// Chapter 2 replaces the discarded Iron Pass story. Rewards remain server-replayed.
export const PEOPLE=[
 {id:'farid',name:'Farid',role:'Ferryman of Seabell',x:-2620,y:1370,color:'#c99857'},
 {id:'cart',name:'Overturned seed cart',role:'Recover the village seed sacks',x:-1620,y:1040,kind:'supplies',guards:'lookouts'},
 {id:'lina',name:'Lina',role:'Millwright and irrigation engineer',x:150,y:900,color:'#668eab'},
 {id:'orchard',name:'Orchard sluice',role:'Open the irrigation channel',x:1050,y:690,kind:'wheel',guards:'depot'},
 {id:'cedar',name:'Cedar bypass',role:'Recover the spare drive belt',x:-1110,y:-1110,kind:'supplies',guards:'quarry'},
 {id:'mill',name:'Lina · Willowbend',role:'Restart the waterwheel',x:1130,y:-640,color:'#668eab',guards:'barracks'},
 {id:'defense',name:'Main sluice wheel',role:'Hold the mill against the raiders',x:1050,y:-760,kind:'wheel'},
 {id:'captain',name:'Tollhouse winch',role:'Break the blockade',x:2750,y:-1810,kind:'wheel',guards:'captain'},
 {id:'reservoir',name:'Reservoir controls',role:'Release the stolen water',x:2720,y:-3570,kind:'wheel',guards:'commander'},
 {id:'ending',name:'Lina · Reservoir',role:'A valley worth returning to',x:2440,y:-3520,color:'#668eab'}
];
PEOPLE.push(...CARAVAN_PEOPLE,HUNT_KEEPER);
export const CHAPTER=[
 {who:'farid',title:'The day the river stopped',text:'Yesterday you could hear our mill from the harbor. Today even the gulls sound too loud. Rook’s men dammed the river and took our seed cart. Lina went upriver to repair the channels. Bring the seeds to her. Without them, freeing the water will not save the harvest.',reply:'I will reach her before the fields dry.',goal:'Meet Farid at Seabell Harbor.'},
 {who:'cart',title:'What grows after us',text:'The cart carries no treasure—only seed sacks marked with the names of the families who saved them. A raider has cut one open to feed his horse. You bind the torn sack and take what remains. The orchard road leads east.',reply:'Take the seeds to Lina.',goal:'Defeat the roadside raiders and recover the seed cart.'},
 {who:'lina',title:'Two ways to bring back the river',text:'My father built these channels. He taught me that water belongs to whoever is downstream. Rook bought the reservoir and decided that meant the valley. We can open the orchard sluice to save the trees, or take the cedar path for a stronger mill belt. Choose a route; I will meet you at Willowbend.',choices:[['orchard','Save the orchard. Keep this year’s harvest alive.'],['cedar','Take the cedar trail. Make the mill reliable.']],goal:'Find Lina on the orchard road and choose your route.'},
 {who:'branch',title:'A small repair, a long future',text:'You clear the channel and secure the repair. The mill lies northeast, where the two paths meet.',reply:'Continue to Willowbend Mill.',goal:'Clear your chosen route and recover its repair.'},
 {who:'mill',title:'Hold until the wheel turns',text:'The teeth are aligned. Once I release the brake, the sound will bring every patrol nearby. Keep them away while the wheel catches. Twenty-four seconds. After that, we carry the fight to their captain.',reply:'Start the wheel. I will hold the yard.',goal:'Clear the mill yard and speak to Lina.'},
 {who:'defense',title:'The mill stands',text:'The belt catches. Then the wheel takes a full turn, and water strikes the channel with a sound louder than the fighting. Lina grips the railing, breathless. The mill is working. A courier brings news of missing medicine wagons beyond the valley. The caravan road beside Willowbend is open: meet Lina at Saffron. Rook’s captain and reservoir can be dealt with when you return.',reply:'The mill is safe. Open the caravan road.',goal:'Defend Willowbend: survive three raider waves and finish the restart.'},
 {who:'captain',title:'No toll on the rain',text:'The captain’s winch locks the bridge, not the water. You release it. Beyond the narrow crossing, Rook has opened a private outlet while the valley’s channels stand dry. This was never an emergency ration. It was a price.',reply:'Cross to Cloudwater Reservoir.',goal:'Defeat the Toll Captain and release the bridge winch.'},
 {who:'reservoir',title:'Let the valley drink',text:'Rook falls beside the controls. You open the public spillway, and the reservoir answers in a white rush. Far below, water divides into the old channels. The valley’s fields will belong to the people who work them again.',reply:'Open the spillway.',goal:'Defeat Marshal Rook and open the reservoir controls.'},
 {who:'ending',title:'When the river returns',text:'Lina watches the white line of water reach the mill. “Tomorrow I will have to repair everything we broke today.” She smiles. “When the work is done, I would like our families to meet. If you want a future here too.” Below you, the first boats leave the harbor. For once, there is time to answer.',choices:[['courtship','I would like that—with our families involved.'],['friendship','I will return as your friend. This valley is home.']],goal:'Speak with Lina above the restored spillway.'}
];
export function storyState(profile){if(!profile)return null;if(profile.story?.version!==2){if(profile.story)profile.previousStory=profile.story;profile.story={version:2,stage:0,choice:null,relationship:null,flags:{},journal:[]};}return profile.story;}
export function currentStory(profile){return null;}
function archivedStory(profile){const st=storyState(profile);if(!st)return null;if(profile.caravan?.started&&profile.caravan.stage<9)return caravanCurrent(profile);const chapter=CHAPTER[st.stage];if(!chapter)return caravanCurrent(profile);const who=chapter.who==='branch'?(st.choice==='cedar'?'cedar':'orchard'):chapter.who;const text=st.stage===3?(st.choice==='cedar'?'Under the blue cedars, you find the millwright’s spare belt packed in oiled cloth. It is heavier than the worn one at Willowbend. A quiet repair that could spare the village another season of failure.':'The sluice is jammed with stones. You free it and watch the first thin stream reach the apricot roots. New leaves float down the channel. The crop has a chance now.'):chapter.text;return {...chapter,text,target:PEOPLE.find(n=>n.id===who),stage:st.stage};}
export function storyBlocked(sim,target){return target.id==='defense'?!sim.millDefense?.complete:!!target.guards&&sim.enemies.some(e=>!e.dead&&e.group===target.guards);}
export function personPresent(profile,n){return ['farid','c2-hunts','c2-trainer','c2-surveyor'].includes(n.id);}
function archivedPersonPresent(profile,n){const s=storyState(profile);if(!s)return false;if(n.id.startsWith('c2-')){const c=profile.caravan;if(!c?.started)return false;if(n.id==='c2-lina')return !c.fatherSafe;if(n.id==='c2-home')return !!c.fatherSafe&&!(c.stage>=9&&s.stage<9);if(n.id==='c2-rescued')return !c.fatherSafe;return true;}if(n.id==='lina')return s.stage<=3;if(n.id==='mill')return s.stage>=4&&s.stage<=6&&!profile.caravan?.started;if(n.id==='ending')return s.stage>=8&&(!profile.caravan?.started||profile.caravan.stage>=9&&s.stage<9);return !(n.id==='cart'&&s.stage>1);}
export function nearbyPerson(sim){const target=currentStory(sim.profile)?.target;const nearby=PEOPLE.filter(n=>personPresent(sim.profile,n)&&Math.hypot(n.x-sim.player.x,n.y-sim.player.y)<210);return nearby.find(n=>n.id===target?.id)||nearby.sort((a,b)=>Math.hypot(a.x-sim.player.x,a.y-sim.player.y)-Math.hypot(b.x-sim.player.x,b.y-sim.player.y))[0];}
export function advanceStory(sim,id,choice){if(typeof id==='string'&&id.startsWith('c2-'))return caravanAdvance(sim,id,choice);const p=sim.profile,st=storyState(p),q=currentStory(p);if(!p||!q||sim.player.dead||q.target.id!==id||Math.hypot(sim.player.x-q.target.x,sim.player.y-q.target.y)>230||storyBlocked(sim,q.target))return false;if(q.choices&&!q.choices.some(c=>c[0]===choice))return false;if(q.stage===2)st.choice=choice;if(q.stage===8)st.relationship=choice;st.journal.push({title:q.title,text:q.text,choice:q.choices?.find(c=>c[0]===choice)?.[1]||null});st.stage++;if(q.stage===3){sim.drop(sim.player.x,sim.player.y,'heal',st.choice==='orchard'?90:45);sim.drop(sim.player.x,sim.player.y,'gold',st.choice==='cedar'?90:45);}p.gold+=q.stage===7?180:25;sim.xp(q.stage===7?350:60);sim.applyStats();sim.emit('notice',{message:q.stage===8?'WINDWARD VALE RESTORED':q.title+' · JOURNAL UPDATED'});return true;}
export function tickStory(sim,dt){if(!sim.profile||storyState(sim.profile).stage!==5||sim.player.dead)return;const d=sim.millDefense??={elapsed:0,wave:0,complete:false};if(d.complete)return;if(Math.hypot(sim.player.x-1050,sim.player.y+600)>1200)return;d.elapsed+=dt;const times=[0,8,16];while(d.wave<3&&d.elapsed>=times[d.wave]){const wave=d.wave++;for(let i=0;i<3+wave;i++){const e=sim.addEnemy(i===2?'archer':i===3?'brute':'raider',550+i*180,-950+wave*130,'millDefense');e.active=true;e.level=3;e.hp=Math.round(e.hp*1.2);e.maxHp=e.hp;}sim.emit('notice',{message:'MILL DEFENSE · WAVE '+(wave+1)+'/3'});}if(d.elapsed>=24&&d.wave===3&&!sim.enemies.some(e=>e.group==='millDefense'&&!e.dead)){d.complete=true;sim.emit('notice',{message:'WATERWHEEL RUNNING · TURN THE SLUICE'});}}
export function ambientDialogue(id,profile){const s=storyState(profile);if(id==='farid')return s.stage>7?'The boats are moving again. You can hear the mill from here. I had forgotten how much that sound meant.':'The road bends east through the flowers. Follow the painted posts to Lina. Bring her back safely.';if(id==='ending')return s.relationship==='courtship'?'I will write to my family. There is a home to rebuild, and we can take the time to do this properly.':'The river is running. Stay a while, if you can. There will always be work—and a place—for a friend here.';return 'Follow the gold objective marker. The journal records your route through the valley.';}
