import {applyCommands} from '../src/js/commands.js';
export {applyCommands} from '../src/js/commands.js';
import CombatSim from '../src/js/combat.js';
import {CLASSES,newProfile} from '../src/js/rpg.js';
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
export async function api(request,env){try{const user=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email');if(!user||!email)return json({error:'Sign in to load your characters'},401);if(!env.DB)return json({error:'Character storage unavailable. Please retry.'},503);const url=new URL(request.url),db=env.DB;
 if(request.method==='GET'&&url.pathname==='/api/account'){const rows=await db.prepare('SELECT id, profile FROM characters WHERE owner = ? ORDER BY updated DESC').bind(user).all();return json({email,characters:rows.results.map(r=>JSON.parse(r.profile))});}
 if(request.method!=='POST')return json({error:'Not found'},404);
 if(request.headers.get('origin')!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')return json({error:'Invalid origin'},403);
 if(!(request.headers.get('content-type')||'').startsWith('application/json'))return json({error:'JSON required'},415);
 const raw=await request.text();if(raw.length>90000)fail('Request too large',413);let body;try{body=JSON.parse(raw);}catch{fail('Invalid JSON');}
 if(url.pathname==='/api/characters'){const name=String(body.name||'').trim();if(!/^[\p{L}\p{N} _-]{2,20}$/u.test(name)||!Object.hasOwn(CLASSES,body.classId))fail('Use a 2–20 character name and choose a class');const id=crypto.randomUUID(),profile=newProfile(id,name,body.classId);const result=await db.prepare('INSERT INTO characters (id,owner,name,class_id,profile,revision,updated) SELECT ?,?,?,?,?,0,? WHERE (SELECT COUNT(*) FROM characters WHERE owner=?) < 4').bind(id,user,name,body.classId,JSON.stringify(profile),Date.now(),user).run();if(!result.meta.changes)fail('Four character slots are already filled',409);return json({profile});}
 if(!['/api/run','/api/batch'].includes(url.pathname))return json({error:'Not found'},404);
 const row=await db.prepare('SELECT * FROM characters WHERE id = ? AND owner = ?').bind(String(body.id),user).first();if(!row)return json({error:'Character not found'},404);
 if(url.pathname==='/api/run'){let sim;if(row.run&&!body.restart)sim=CombatSim.restore(JSON.parse(row.run));else{const seed=crypto.getRandomValues(new Uint32Array(1))[0];sim=new CombatSim(row.class_id).attachProfile(JSON.parse(row.profile),seed,crypto.randomUUID());}sim.wallCredit=2;sim.wallAt=Date.now();const revision=row.revision+1,result=await db.prepare('UPDATE characters SET run=?,revision=?,updated=? WHERE id=? AND owner=? AND revision=?').bind(JSON.stringify(sim.exportState()),revision,Date.now(),row.id,user,row.revision).run();if(!result.meta.changes)fail('Character changed in another session. Reload.',409);return json({state:sim.exportState(),revision});}
 if(!row.run)fail('Start a run first',409);const sim=CombatSim.restore(JSON.parse(row.run));if(typeof body.batchId!=='string'||body.batchId.length>64)fail('Invalid batch ID');if(sim.lastBatchId===body.batchId)return json({revision:row.revision,state:sim.exportState()});if(body.revision!==row.revision)fail('Character opened in another session. Reload to continue.',409);if(!Array.isArray(body.commands)||body.commands.length>500)fail('Invalid command batch');const time=body.commands.reduce((sum,c)=>sum+(c.op==='step'?(c.dt||0):0),0),now=Date.now(),credit=Math.min(15,(sim.wallCredit||0)+(now-(sim.wallAt||now))/1000);if(!Number.isFinite(time)||time>credit+.15)fail('Gameplay is ahead of server time. Retry shortly.',429);applyCommands(sim,body.commands);sim.wallAt=now;sim.wallCredit=Math.max(0,credit-time);sim.lastBatchId=body.batchId;const revision=row.revision+1,result=await db.prepare('UPDATE characters SET profile=?,run=?,revision=?,updated=? WHERE id=? AND owner=? AND revision=?').bind(JSON.stringify(sim.profile),JSON.stringify(sim.exportState()),revision,now,row.id,user,row.revision).run();if(!result.meta.changes)fail('Character changed in another session. Reload.',409);return json({revision,state:sim.exportState()});
 }catch(error){if(!error.status)console.error('Character API failed',error.message);return json({error:error.status?error.message:'Save service unavailable. Your pending inputs are retained; retry.'},error.status||503);}}
