import * as T from 'three';
const mat=c=>new T.MeshStandardMaterial({color:c,roughness:.82});
export function createCreature(scene,e){const root=new T.Group();scene.add(root);const shell=mat(e.type==='colossus'?'#514947':e.type==='golem'?'#635a53':e.type==='ridgebeast'?'#a7aeb0':'#365d73'),accent=new T.MeshStandardMaterial({color:e.type==='golem'||e.type==='colossus'?'#f58c35':'#9ae8ee',emissive:e.type==='golem'||e.type==='colossus'?'#f35a16':'#439ba7',emissiveIntensity:.65,roughness:.3}),legs=[];
 const part=(geo,m,x,y,z,sx=1,sy=1,sz=1)=>{const mesh=new T.Mesh(geo,m);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;root.add(mesh);return mesh;};
 const spider=['spider','matriarch'].includes(e.type),golem=['golem','colossus'].includes(e.type);
 if(spider){part(new T.IcosahedronGeometry(.53,1),shell,0,.62,-.20,1,.68,1.4);part(new T.IcosahedronGeometry(.33,1),shell,0,.53,.42);for(let i=0;i<5;i++){const spike=part(new T.ConeGeometry(.13,.65+i*.055,5),accent,Math.sin(i*2.4)*.3,.95,-.30+Math.cos(i*2.4)*.35);spike.rotation.z=Math.sin(i)*.35;}for(const side of [-1,1])for(let i=0;i<4;i++){const pivot=new T.Group();pivot.position.set(side*.3,.55,-.6+i*.3);root.add(pivot);const upper=new T.Mesh(new T.CylinderGeometry(.04,.075,.8,5),shell);upper.position.set(side*.34,.10,0);upper.rotation.z=-side*1.2;pivot.add(upper);const lower=new T.Mesh(new T.ConeGeometry(.065,.75,5),accent);lower.position.set(side*.70,-.22,.08);lower.rotation.z=side*.5;pivot.add(lower);legs.push(pivot);}}
 else if(golem){part(new T.DodecahedronGeometry(.57,0),shell,0,1.05,0,1.2,1.35,.9);part(new T.IcosahedronGeometry(.32,0),shell,0,1.94,.06);part(new T.OctahedronGeometry(.25),accent,0,1.1,.48);for(const side of [-1,1]){const arm=part(new T.DodecahedronGeometry(.36),shell,side*.82,.88,.02,.9,1.65,1);legs.push(arm);part(new T.DodecahedronGeometry(.28),shell,side*.32,.27,0,.9,1.4,1);part(new T.OctahedronGeometry(.10),accent,side*.33,.63,.15);for(let i=0;i<3;i++)part(new T.ConeGeometry(.15,.44,5),shell,side*(.36+i*.20),1.65-i*.05,0);}}
 else{part(new T.IcosahedronGeometry(.5,1),shell,0,.70,0,.8,.85,1.5);part(new T.IcosahedronGeometry(.31,0),shell,0,.88,.72);for(const side of [-1,1]){const horn=part(new T.ConeGeometry(.10,.65,5),accent,side*.22,1.23,.58);horn.rotation.x=-.4;for(const z of [-.48,.48]){const leg=part(new T.CylinderGeometry(.07,.10,.60,5),shell,side*.32,.29,z);legs.push(leg);}}for(let i=0;i<4;i++)part(new T.ConeGeometry(.12,.28,5),accent,0,1.13,-.55+i*.27);}
 root.scale.setScalar(e.boss?1.75:1.2);return {root,creature:true,shell,accent,legs,id:e.id,baseScale:e.boss?1.75:1.2};
}
export function updateCreature(a,e,dt,sim){a.root.position.set(e.x*.01,(e.z||0)*.01,e.y*.01);a.root.rotation.y=Math.PI/2-e.angle;const walking=e.moving?1:0;for(const [i,leg] of a.legs.entries())leg.rotation.x=Math.sin(sim.time*(e.type==='ridgebeast'?15:11)+i*Math.PI)*walking*.40;a.root.position.y+=e.dead?0:Math.sin(sim.time*6)*.025;a.root.rotation.z=e.dead?(e.deathSide||1)*Math.min(1.4,(1.65-e.death)*2):e.wind>0?Math.sin(sim.time*24)*.035:0;a.shell.emissive.set(e.hit>0?'#f1bea1':'#000000');a.shell.emissiveIntensity=e.hit>0?1:0;a.accent.emissiveIntensity=e.wind>0?1.6:.65;}
export function disposeCreature(a){a.root.removeFromParent();a.root.traverse(o=>{if(o.isMesh)o.geometry.dispose();});a.shell.dispose();a.accent.dispose();}
