import {EVOLUTIONS,EVOLUTION_NODES,EVOLUTION_BY_ID,evolutionState,evolutionUnlock,evolutionBudget,evolutionError} from './js/evolutions.js';
import {STAT_LABELS} from './js/skill-tree.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modifiers=n=>n.text||Object.entries(n.effects).map(([k,v])=>`+${['healKill','regen'].includes(k)?Number(v.toFixed(2)):Math.round(v*100)+'%'} ${STAT_LABELS[k]}`).join(' · ');
export function mountEvolutionUI(host,sim,act){const p=sim.profile,state=evolutionState(p),current=EVOLUTION_BY_ID[state.id],reason=evolutionUnlock(p),safe=sim.canEditTree(),budget=evolutionBudget(p);
 host.innerHTML=`<section class="evolution-section"><div class="evolution-heading"><div><small>CLASS EVOLUTION · SEPARATE POINT POOL</small><h3>${current?.name||'Choose what you become'}</h3></div><b>${budget-state.nodes.length} / ${budget} POINTS FREE</b></div><p>Unlock at level 6 after defeating the Toll Captain. Earn 2 evolution points at levels 6, 10, 15 and 20. Choose one evolution; its signature technique activates immediately. The base weapon and four combat controls stay the same.</p>${reason?`<p class="evolution-lock">LOCKED · ${reason}</p>`:''}<div class="evolution-options">${EVOLUTIONS.filter(e=>e.classId===p.classId).map(e=>`<article class="${state.id===e.id?'chosen':''}"><small>${e.role.toUpperCase()}</small><h4>${e.name}</h4><p>${e.text}</p><button data-evolve="${e.id}" ${reason||!safe||state.id===e.id?'disabled':''}>${state.id===e.id?'ACTIVE EVOLUTION':state.id?'SWITCH EVOLUTION':'EVOLVE'}</button></article>`).join('')}</div>${current?`<div class="evolution-tree"><h4>CORE PATH</h4><div class="evolution-core">${EVOLUTION_NODES.filter(n=>n.evolution===state.id&&n.branch===-1).map(card).join('')}</div><div class="evolution-branches">${[0,1].map(branch=>`<section><h4>${current.branches[branch][0].toUpperCase()}</h4>${EVOLUTION_NODES.filter(n=>n.evolution===state.id&&n.branch===branch).map(card).join('')}</section>`).join('')}</div><button id="evolutionReset" ${!safe||!state.nodes.length?'disabled':''}>REFUND EVOLUTION POINTS</button><p class="rpg-muted">Eight points cannot complete all twelve nodes. Finish one branch or combine partial branches. Switching evolution refunds its learned nodes; your atlas stays allocated. All changes require safety.</p></div>`:''}</section>`;
 function card(n){const has=state.nodes.includes(n.id),error=evolutionError(p,n.id),parent=EVOLUTION_NODES.find(x=>x.id===n.requires);return `<article class="evolution-node ${has?'learned':''} ${n.flag?'signature':''}"><small>${has?'LEARNED':`1 POINT · LEVEL ${n.level}`}</small><h5>${esc(n.name)}</h5><p>${esc(modifiers(n))}</p><small>${n.requires?'Requires '+esc(parent.name):'Start here'}</small><button data-evo-node="${n.id}" data-action="${has?'refund':'learn'}" ${!safe||!has&&error?'disabled':''}>${has?'REFUND':error||'LEARN'}</button></article>`;}
 host.querySelectorAll('[data-evolve]').forEach(b=>b.onclick=()=>{if(state.id&&!confirm('Switch evolution and refund its learned nodes? Your atlas and equipment stay equipped.'))return;act({op:'evolution',action:'choose',id:b.dataset.evolve});});host.querySelectorAll('[data-evo-node]').forEach(b=>b.onclick=()=>act({op:'evolution',action:b.dataset.action,id:b.dataset.evoNode}));host.querySelector('#evolutionReset')?.addEventListener('click',()=>{if(confirm('Refund all evolution points for free? Your evolution identity remains active.'))act({op:'evolution',action:'reset'});});
}
