import {visualProfile,SIGNATURE_BY_ID,HUNT_BY_ID} from './js/hunt-data.js';
import * as T from 'three';
const metal=(color,m=.6)=>new T.MeshStandardMaterial({color,metalness:m,roughness:.42,flatShading:true});
const part=(g,geo,mat,x=0,y=0,z=0)=>{const o=new T.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=true;g.add(o);return o;};
export function appearance(item){const rank=['common','uncommon','rare','epic','legendary'].indexOf(item?.rarity||'common');return{tier:Math.min(2,Math.floor(((item?.level||1)-1)/3)),rank,steel:item?.visualSteel||(item?.huntSignature?HUNT_BY_ID[SIGNATURE_BY_ID[item.huntSignature]?.hunt]?.color:null)||['#656c70','#81928e','#819eb3','#c3b18d','#c77769'][Math.max(0,rank)],cloth:item?.visualCloth||['#3c3430','#314239','#303c50','#4b3548','#632f2d'][Math.max(0,rank)]};}
export function gearMesh(slot,item={},classId='katana',side=1){const g=new T.Group(),a=appearance(item),steel=metal(a.steel),trim=metal(a.rank>=2?'#c4a56e':'#a09a85'),cloth=metal(a.cloth,.08),tier=a.tier;
 if(slot==='weapon'){
  const id=item.classId||classId;
  if(id==='pistols'){part(g,new T.BoxGeometry(.14,.53+tier*.1,.18),steel,0,.23,0);part(g,new T.BoxGeometry(.14,.23,.2),cloth,0,-.1,-.07);part(g,new T.CylinderGeometry(.09,.09,.15,8),trim,0,.53+tier*.1,0);if(tier>0)part(g,new T.BoxGeometry(.21,.18,.2),trim,0,.14,0);if(tier===2)part(g,new T.BoxGeometry(.07,.35,.08),trim,.1,.33,0);g.userData.tip=new T.Vector3(0,.68+tier*.1,0);}
  else{const len=id==='greatsword'?1.65+tier*.10:id==='twins'?.7+tier*.06:1.35+tier*.08,w=id==='greatsword'?.19+tier*.025:.065+tier*.013;const shape=new T.Shape();shape.moveTo(-w,.12);shape.lineTo(-w,len-.18);shape.lineTo(tier===2?w*.5:0,len+.04);shape.lineTo(w,len-.2);shape.lineTo(w,.12);shape.closePath();part(g,new T.ExtrudeGeometry(shape,{depth:.04,bevelEnabled:true,bevelSize:.015,bevelThickness:.01,bevelSegments:1,steps:1}),steel,0,0,-.025);part(g,new T.BoxGeometry(w*4,.06,.13),trim,0,.12,0);part(g,new T.CylinderGeometry(.047,.047,.28,8),cloth,0,-.055,0);if(tier>0)for(const y of [.26,.40])part(g,new T.BoxGeometry(w*1.4,.04,.06),trim,0,y,.024);g.userData.tip=new T.Vector3(0,len,0);}
  const edge=part(g,new T.SphereGeometry(.045,6,4),new T.MeshBasicMaterial({color:'#ffe2aa',transparent:true,opacity:0}),0,.6,0);g.userData.edge=edge;g.userData.base=new T.Vector3(0,.25,0);
 }else if(slot==='head'){
  // Open-faced hood armor: the faceless black head remains visible.
  part(g,new T.SphereGeometry(.36,8,5,0,Math.PI*2,0,Math.PI*.50),steel,0,.20,0);for(const x of [-.28,.28])part(g,new T.BoxGeometry(.12,.39,.40),steel,x,.07,-.04);part(g,new T.BoxGeometry(.60,.07,.10),trim,0,.30,.23);if(tier>0)part(g,new T.BoxGeometry(.09,.12+tier*.08,.42),trim,0,.47,-.02);
 }else if(slot==='chest'){
  const shape=new T.Shape();shape.moveTo(-.34,.24);shape.lineTo(-.23,-.23);shape.lineTo(0,-.31);shape.lineTo(.23,-.23);shape.lineTo(.34,.24);shape.lineTo(.15,.32);shape.lineTo(-.15,.32);shape.closePath();part(g,new T.ExtrudeGeometry(shape,{depth:.24,bevelEnabled:true,bevelSize:.04,bevelThickness:.04,bevelSegments:2,steps:1}),steel,0,0,-.09);part(g,new T.BoxGeometry(.46,.14,.39),cloth,0,-.30,.03);for(const x of [-.42,.42]){const shoulder=part(g,new T.DodecahedronGeometry(.23+tier*.045,0),steel,x,.20,0);shoulder.scale.set(1,.6,.95);}for(const x of [-.21,.21])part(g,new T.BoxGeometry(.045,.46,.035),trim,x,0,.235);
 }else if(slot==='hands'){part(g,new T.SphereGeometry(.14,8,6),steel,0,.01,.025).scale.set(.8,1,.7);for(let i=0;i<4;i++)part(g,new T.CapsuleGeometry(.022,.09,3,5),cloth,-.065+i*.043,-.13,.03);part(g,new T.BoxGeometry(.22,.065,.24),trim,0,.13,.02);}
 else if(slot==='legs'){part(g,new T.CylinderGeometry(.16,.12,.43,8),steel,0,-.20,0);part(g,new T.DodecahedronGeometry(.16+tier*.02,0),trim,0,-.40,.11);}
 else if(slot==='feet'){part(g,new T.CylinderGeometry(.13,.14,.30+tier*.04,8),steel,0,.06,0);part(g,new T.SphereGeometry(.16,8,6),steel,0,-.05,.14).scale.set(.82,.7,1.5);part(g,new T.BoxGeometry(.28,.055,.46),cloth,0,-.12,.10);part(g,new T.BoxGeometry(.28,.045,.26),trim,0,.13,0);}
 if(item.huntSignature&&slot==='weapon'){const v=Object.keys(SIGNATURE_BY_ID).indexOf(item.huntSignature)%3;for(let k=0;k<=v;k++)part(g,new T.BoxGeometry(.15,.035,.08),trim,0,.3+k*.14,.08);if(v===2)part(g,new T.BoxGeometry(.35,.07,.12),trim,0,.19,0);}
 if(item.outfitShape!==undefined&&slot==='chest'){const n=item.outfitShape;for(const side of [-1,1])part(g,new T.BoxGeometry(.14+n*.025,.38+n*.04,.07),cloth,side*.30,-.18,.23);if(n>0)part(g,new T.BoxGeometry(.38,.1+n*.025,.12),trim,0,.30,.18);}
 return g;
}
export function disposeGear(g){g.removeFromParent();g.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}
export function syncGear(actor,profile){if(!profile)return;profile=visualProfile(profile);const key=Object.values(profile.equipment).map(i=>i?.id||'-').join('|');if(actor.gearKey===key)return;actor.gearKey=key;for(const g of actor.gearParts||[])disposeGear(g);actor.gearParts=[];const add=(slot,boneName,item,side=1)=>{const bone=actor.model.getObjectByName(boneName);if(!bone)return;const g=gearMesh(slot,item,profile.classId,side);bone.add(g);if(slot!=='weapon')actor.gearParts.push(g);return g;};
 const w=profile.equipment.weapon;if(w){disposeGear(actor.sword);actor.sword=add('weapon','handslotr',w);if(actor.second){disposeGear(actor.second);actor.second=add('weapon','handslotl',w);actor.second.visible=profile.classId==='twins';}}
 for(const slot of ['head','chest','hands','legs','feet']){const item=profile.equipment[slot];if(!item)continue;const bones={head:['head'],chest:['chest'],hands:['handl','handr'],legs:['upperlegl','upperlegr'],feet:['footl','footr']}[slot];for(const b of bones)add(slot,b,item,b.endsWith('l')?-1:1);}
 const torso=profile.equipment.chest;if(torso)actor.cloak.color.set(appearance(torso).cloth);else actor.cloak.color.set('#6a1e2f');
}
let iconRenderer,iconScene,iconCamera;const icons=new Map();
export function gearIcon(item,slot,classId){const a=appearance(item),key=[slot,item?.classId||classId,a.tier,a.rank,a.steel,a.cloth,item?.huntSignature,item?.outfitShape].join(':');if(icons.has(key))return icons.get(key);try{if(!iconRenderer){iconRenderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});iconRenderer.setSize(112,112);iconRenderer.setPixelRatio(1);iconScene=new T.Scene();iconScene.add(new T.HemisphereLight('#e2edf5','#25292d',2.3));const light=new T.DirectionalLight('#ffdfae',4);light.position.set(3,4,5);iconScene.add(light);iconCamera=new T.PerspectiveCamera(32,1,.01,20);}const g=gearMesh(slot,item||{slot,rarity:'common',level:1},classId);iconScene.add(g);g.updateMatrixWorld(true);const box=new T.Box3().setFromObject(g),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());g.position.sub(center);const d=Math.max(size.x,size.y,size.z)*2.3;iconCamera.position.set(d*.6,d*.35,d);iconCamera.lookAt(0,0,0);iconRenderer.render(iconScene,iconCamera);const data=iconRenderer.domElement.toDataURL('image/png');icons.set(key,data);disposeGear(g);return data;}catch{return '';}}
