import {SIGNATURE_BY_ID,HUNT_BY_ID,HUNT_RATE,TEMPERS,FRAGMENT_COST} from './js/hunt-data.js';
import {NAMED_GEAR} from './js/named-loot.js';
import {KEYSTONES} from './js/skill-tree.js';
import {RARITIES,CLASSES,REGIONS,gearScore} from './js/rpg.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const HELP={power:['Power','Each Power point adds 1 percentage point to your equipment damage bonus. Signature effects, skill bonuses and enemy defenses are calculated separately.'],armor:['Armor', 'Armor reduces incoming damage using 100 ÷ (100 + Armor × 2). For example, 50 Armor halves incoming damage before other defenses.'],health:['Health','Adds to your maximum health. Equipping, crafting and changing loadouts never refill your current health.'],rarity:['Rarity and item level','Rarity controls base stat strength. Item level also increases base stats and the required character level. A higher rarity is not automatically a better match for your build.'],signature:['Signature effect','A special weapon mechanic with a benefit and a trade-off. It changes your existing four controls and works with your skill tree. Read its trigger before equipping.'],score:['Base stat score','Power × 4 + Armor × 2 + Health × 0.25. This is a quick base stat comparison; it does not measure signature effects or skill synergy. Equip Best preserves your equipped hunt signature weapon.'],fragments:['Boss fragments','Standard clears award 2 fragments. Veteran clears award 3. Spend 6 from a hunt to craft its signature weapon for your class. A random drop is independent of this guaranteed progress.'],temper:['Tempering','Spend 60 Iron fragments and 8 Tempered alloy to choose one additional property. Success is guaranteed. A new choice replaces the previous property. The item is then locked against salvage.'],filter:['Loot labels','All: nearby equipment names. Useful: possible base stat upgrades plus named, signature and locked gear. Signatures: special named or signature items. This only filters labels; items remain on the ground and can still be picked up.'],loadout:['Saved loadouts','Save your equipment, passive tree and evolution in one of three slots. Saving locks equipped items. Loading requires safety and every saved item. Missing items cause the whole change to be rejected.'],veteran:['Veteran hunts','Requires level 12 and a Standard clear of that hunt. Enemies have more health, deal 35% more damage, and gain additional escorts. Signature chance rises from 30% to 45%; fragment rewards rise from 2 to 3.']};
export const helpButton=(id,label='?')=>`<button type="button" class="info-dot" data-help="${esc(id)}" aria-label="Explain ${esc(HELP[id]?.[0]||id)}">${esc(label)}</button>`;
export function itemFacts(item){const s=SIGNATURE_BY_ID[item.huntSignature],n=NAMED_GEAR[item.signature],h=s&&HUNT_BY_ID[s.hunt];return {title:item.name,style:s?.style|| (n?'Named equipment':item.slot==='weapon'?'Base weapon damage':'Survival and equipment stats'),ability:s?.ability||'Always active while equipped',effect:s?.effect|| (n?KEYSTONES[n.key]?.text||n.text:`${item.stats.power?'+'+item.stats.power+' Power. ':''}${item.stats.armor?'+'+item.stats.armor+' Armor. ':''}${item.stats.health?'+'+item.stats.health+' maximum Health. ':''}`),tradeoff:s?.tradeoff|| (n?'An identical named passive and atlas keystone do not stack.':'No special combat mechanic. Compare the base stats and any tempered property.'),source:h?`${h.name}: ${HUNT_RATE.standard*100}% per Standard clear; ${HUNT_RATE.veteran*100}% per Veteran clear. Or craft for ${FRAGMENT_COST} ${h.name} fragments.`:n?n.source:REGIONS[item.region]?.name||'World equipment drops',temper:TEMPERS[item.temper]?.text};}
export function itemSummary(item){const f=itemFacts(item);return `<div class="item-meaning"><small>${esc(f.style.toUpperCase())}</small><h4>${esc(f.ability)}</h4><p>${esc(f.effect)}</p>${item.huntSignature?`<p class="item-tradeoff"><b>Trade-off:</b> ${esc(f.tradeoff)}</p>`:''}${f.temper?`<p><b>Tempered:</b> ${esc(f.temper)}</p>`:''}<button type="button" data-item-explain="${esc(item.id)}">HOW THIS ITEM WORKS ${helpButtonPlaceholder()}</button></div>`;}
function helpButtonPlaceholder(){return '<span aria-hidden="true">ⓘ</span>';}
let dialog;
function show(title,body){if(!dialog){dialog=document.createElement('dialog');dialog.className='item-help-dialog';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});}dialog.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" autofocus aria-label="Close explanation">CLOSE</button></header><div>${body}</div>`;dialog.querySelector('button').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();}
export function openItemInfo(item,p){const f=itemFacts(item),old=p?.equipment[item.slot];show(item.name,`<p class="info-kicker">${esc(RARITIES.find(r=>r.id===item.rarity)?.name)} · ITEM LEVEL ${item.level} · REQUIRES LEVEL ${item.requiredLevel}</p><h3>What changes?</h3><p>${esc(f.effect)}</p><h3>How to use it</h3><p>${esc(f.ability)} · ${esc(f.style)}</p><h3>${item.huntSignature?'Trade-off':'Keep in mind'}</h3><p>${esc(f.tradeoff)}</p>${f.temper?`<h3>Tempered property</h3><p>${esc(f.temper)}</p>`:''}<h3>Compared with equipped</h3><div class="info-compare">${['power','armor','health'].map(k=>`<div><b>${k.toUpperCase()}</b><span>${old?.stats[k]||0} → ${item.stats[k]||0}</span><small>${esc(HELP[k][1])}</small></div>`).join('')}</div><p>${esc(HELP.score[1])}</p><h3>Where to get it</h3><p>${esc(f.source)}</p><p>${item.classId?esc(CLASSES[item.classId].name)+' weapon. ':''}${item.locked?'Locked against salvage. Unlock it from Character if you want to dismantle ordinary gear.':''}</p>`);}
export function bindInfo(root,p,extras=[]){root.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>{const h=HELP[b.dataset.help];if(h)show(h[0],`<p>${esc(h[1])}</p>`);});root.querySelectorAll('[data-item-explain]').forEach(b=>b.onclick=()=>{const i=[...(p?.inventory||[]),...Object.values(p?.equipment||{}),...extras].find(i=>i&&String(i.id)===b.dataset.itemExplain);if(i)openItemInfo(i,p);});}
export function closeItemInfo(){dialog?.close();}
