import {wildernessRegion} from './js/wilderness-data.js';
import {regionDestination} from './js/region-travel.js';
import {guardedFrame} from './frame-loop.js';
import {QuestWalker,questGoal,campaignComplete} from './quest-navigation.js';
import {createBackPauseGuard} from './back-navigation.js';
import {huntObjective} from './js/hunters.js';
import {HUNTS,HUNT_BY_ID} from './js/hunt-data.js';
import {itemFacts} from './item-info.js';
import {WORLD_PORTALS,nearbyPortal,portalUnlocked} from './js/world-portals.js';
import {installMobileHUD,icon} from './mobile-ui.js';
import {EVOLUTION_BY_ID} from './js/evolutions.js';
import {buildStatus} from './js/evolution-combat.js';
import {pointsLeft} from './js/skill-tree.js';
import {currentStory,nearbyPerson} from './js/story.js';
import {Ambience} from './ambience.js';
const ambience=new Ambience();
import {setupProgression} from './progression.js';
import {XP_REQUIRED,QUESTS,CLASSES,RARITIES} from './js/rpg.js';
import {LEVEL,areaAt} from './js/level.js';
import ShadowData from './js/weapons.js';
import CombatSim from './js/combat.js';
import ShadowRenderer from './render3d.js';
installMobileHUD();let lastMapDraw=0;
const $=selector=>document.querySelector(selector);let sim=new CombatSim(),progression;
$('#objective').innerHTML='<span class="quest-copy"></span>';
const questWalker=new QuestWalker(message=>toast(message));
function walkToQuest(){if(questWalker.path){questWalker.cancel();toast('Auto-walk stopped');}else questWalker.start(sim);}
let renderer;let lastZone='',zoneTTL=0;const zoneBanner=document.createElement('div');zoneBanner.id='zoneBanner';document.querySelector('#game').append(zoneBanner);
try { renderer=new ShadowRenderer($('#world')); }
catch(error){$('#startButton').textContent='3D GRAPHICS UNAVAILABLE';$('#startButton').disabled=true;$('.intro').textContent='This device could not start WebGL. Try a current Android browser.';throw error;}
$('#startButton').disabled=true;$('#startButton').textContent='PREPARING WINDWARD VALE…';
renderer.ready.then(()=>{$('#startButton').disabled=false;$('#startButton').innerHTML='ENTER WINDWARD VALE <span>→</span>';}).catch(error=>{$('#startButton').textContent='RETRY LOADING';$('#startButton').disabled=false;$('#startButton').onclick=()=>location.reload();$('.intro').textContent='Character assets could not load. Tap to retry.';console.error(error);});
const keys=new Set(),stick={id:null,x:0,y:0},prefs={sound:true,feedback:true,performance:false,cameraMode:'adventure',cameraYaw:.48,cameraZoom:1};let running=false,started=false,selectedWeapon='katana',audio=null,last=0,moveTTL=0,toastTTL=0,holdAttack=false,holdDelay=0,armoryReturn='game',defeatPending=0;
try{Object.assign(prefs,JSON.parse(localStorage.getItem('kage.preferences')||'{}'));}catch(e){}
function savePrefs(){try{localStorage.setItem('kage.preferences',JSON.stringify(prefs));}catch(e){}}
const backPauseGuard=createBackPauseGuard(window,()=>pause(),()=>started,()=>running);
function sound(kind,side=1){if(!prefs.sound)return;try{
 audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();
 if(!audio.noise){const n=audio.createBuffer(1,audio.sampleRate*.5,audio.sampleRate),d=n.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;audio.noise=n;const compressor=audio.createDynamicsCompressor();compressor.threshold.value=-13;compressor.ratio.value=4;compressor.connect(audio.destination);audio.bus=compressor;}
 const t=audio.currentTime,hit=kind==='hit'||kind==='gun',heavy=kind==='heavy',dur=hit?.14:heavy?.22:.15;
 const n=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain(),pan=audio.createStereoPanner();n.buffer=audio.noise;n.playbackRate.value=.9+Math.random()*.2;f.type=kind==='gun'?'lowpass':hit?'highpass':'bandpass';f.Q.value=hit?.6:1.1;f.frequency.setValueAtTime(hit?1800:heavy?450:750,t);f.frequency.exponentialRampToValueAtTime(hit?800:5200,t+dur*.45);f.frequency.exponentialRampToValueAtTime(hit?500:700,t+dur);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(hit?.55:heavy?.75:.6,t+.018);g.gain.exponentialRampToValueAtTime(.001,t+dur);pan.pan.setValueAtTime(-side*.45,t);pan.pan.linearRampToValueAtTime(side*.45,t+dur);n.connect(f);f.connect(g);g.connect(pan);pan.connect(audio.bus);n.start(t,Math.random()*.15);n.stop(t+dur+.02);
 if(hit||heavy){const o=audio.createOscillator(),b=audio.createGain();o.frequency.setValueAtTime(hit?155:90,t);o.frequency.exponentialRampToValueAtTime(35,t+.12);b.gain.setValueAtTime(hit?.32:.17,t);b.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(b);b.connect(audio.bus);o.start(t);o.stop(t+.18);}
}catch(e){}}
function vibrate(ms){if(prefs.feedback&&navigator.vibrate)navigator.vibrate(ms);}
function resetInput(){questWalker.cancel();if(ambience.ctx)ambience.master.gain.setTargetAtTime(0,ambience.ctx.currentTime,.05);keys.clear();stick.id=null;stick.x=0;stick.y=0;holdAttack=false;$('#stick').style.transform='translate(0,0)';for(const b of document.querySelectorAll('#actions button'))b.classList.remove('pressed');}
function showPanel(id){running=false;resetInput();$('#overlay').classList.remove('hidden');for(const p of document.querySelectorAll('.panel'))p.classList.toggle('hidden',p.id!==id);}
function start(){if(!renderer.loaded||!progression?.ready()||$('#rpgLayer')&&!$('#rpgLayer').hidden)return;started=true;backPauseGuard.arm();running=true;$('#pauseButton').textContent='Ⅱ PAUSE';$('#pauseButton').setAttribute('aria-label','Pause game');resetInput();$('#overlay').classList.add('hidden');sound('slash');}
function pause(){if(!started||sim.player.dead)return;$('#pauseButton').textContent='▶ RESUME';$('#pauseButton').setAttribute('aria-label','Resume game');$('#pauseTitle').textContent='Between shadows.';$('#pauseCopy').textContent='Take a breath. Your blade will wait.';$('#resumeButton').textContent='RESUME';showPanel('pausePanel');}
window.pauseCombat=pause;
function defeat(){showPanel('pausePanel');$('#pauseTitle').textContent='Rise from the dark.';$('#pauseCopy').textContent=`${sim.kills} raiders defeated · ${sim.gold} coins · ${sim.chests.filter(c=>c.opened).length}/${sim.chests.length} chests`;$('#resumeButton').textContent='TRY AGAIN';}
function restart(){if(!sim.profile)return;progression.restart();}
function toast(message){$('#moveName').textContent=message;moveTTL=1.3;}
function act(action){if(!running)return;questWalker.cancel();const entrance=HUNTS.find(h=>Math.hypot(h.entry.x-sim.player.x,h.entry.y-sim.player.y)<230);if(action==='interact'&&entrance&&(!sim.huntRun||sim.huntRun.completed)){progression.startEncounter(entrance.id);return true;}if(action==='interact'&&!nearbyPortal(sim)&&nearbyPerson(sim)){progression.talk(nearbyPerson(sim).id);return true;}const ok=sim.input(action);progression?.record({op:'act',action});if(ok&&action==='dash'){sound('slash');vibrate(9);}return ok;}
function updateWeaponUI(){const w=sim.weapon;document.documentElement.style.setProperty('--accent',w.color);$('#weaponLabel').textContent=w.name.toUpperCase()+' · '+w.type;for(let i=0;i<2;i++){const b=$('#skill'+i);b.querySelector('i').innerHTML=icon(i===0?(w.ranged?'target':'blade'):'burst');b.querySelector('span').textContent=(!w.ranged&&i===(w.id==='twins'?1:0)?'LAUNCH / SLAM':w.skills[i].name).toUpperCase();b.setAttribute('aria-label',b.querySelector('span').textContent);}$('#ultimate span').textContent=w.ultimate.name.toUpperCase();$('#ultimate').setAttribute('aria-label',w.ultimate.name);$('#chainHint').textContent=w.ranged?'Move + Fire · Skills: pierce / barrage':`Attack → Launch skill → Attack → Slam skill`;}
function openArmory(){armoryReturn=!started?'intro':'game';selectedWeapon=sim.player.weapon;showPanel('armoryPanel');drawArmory();}
function drawArmory(){const container=$('#weaponCards');container.replaceChildren();for(const w of Object.values(ShadowData.weapons)){const b=document.createElement('button');b.className='weapon-card'+(selectedWeapon===w.id?' selected':'');b.style.setProperty('--weapon-color',w.color);b.innerHTML=`<i>${w.id==='pistols'?'➤':w.id==='twins'?'╱╱':w.id==='greatsword'?'╱':'╱'}</i><span>${w.type}</span><strong>${w.name}</strong><small>${w.tag}</small>`;b.onclick=()=>{selectedWeapon=w.id;drawArmory();};container.append(b);}const w=ShadowData.weapons[selectedWeapon];$('#weaponDetails').innerHTML=w.ranged?`<p>${w.description}</p><p class="chain-line">Aimed shot → follow-up → piercing shot</p><p><strong>Heavy:</strong> five-shot spread · <strong>Dash → Attack:</strong> retaliation burst</p><p><strong>Skills:</strong> Piercing round · Strafe barrage · <strong>Ultimate:</strong> Full magazine</p>`:`<p>${w.description}</p><p class="chain-line">${w.chain.length}-hit chain · ${w.chain.map(a=>a.name).join(' → ')}</p><p><strong>Dash → Attack:</strong> ${w.dashAttack.name} &nbsp; <strong>2 attacks → Heavy:</strong> ${w.finisher.name}</p><p><strong>Airborne → Attack:</strong> Juggle · <strong>Airborne → Heavy:</strong> ${w.slam.name}</p><p><strong>Skills:</strong> ${w.skills.map(s=>s.name+' ('+s.cooldown+'s)').join(' · ')} &nbsp; <strong>Ultimate:</strong> ${w.ultimate.name}</p>`;$('#equipButton').innerHTML=`WIELD ${w.name.toUpperCase()} <span>→</span>`;}
$('#startButton').onclick=start;$('#pauseButton').onclick=()=>running?pause():started&&!sim.player.dead?start():null;$('#resumeButton').onclick=()=>sim.player.dead?restart():start();$('#restartButton').onclick=restart;$('#menuButton').onclick=()=>progression.openHub();$('#worldMapButton').onclick=()=>progression.openJourney();$('#objective').onclick=()=>{if(running){if(questWalker.path||questGoal(sim))walkToQuest();else progression.openJourney();}};$('#skillsButton').onclick=()=>progression.openSkills();$('#armoryButton').onclick=openArmory;$('#weaponsFromPause').onclick=openArmory;$('#equipButton').onclick=()=>{sim.equip(selectedWeapon);updateWeaponUI();if(armoryReturn==='intro')showPanel('introPanel');else if(sim.player.dead)defeat();else start();};$('#closeArmory').onclick=()=>{if(armoryReturn==='intro')showPanel('introPanel');else if(sim.player.dead)defeat();else pause();};
function updatePrefs(){renderer.setCamera({mode:prefs.cameraMode,yaw:prefs.cameraYaw,zoom:prefs.cameraZoom});$('#cameraModeButton').textContent='CAMERA · '+renderer.cameraRig.mode.toUpperCase();$('#cameraZoomButton').textContent='DISTANCE · '+Math.round(renderer.cameraRig.zoom*100)+'%';$('#qualityButton').textContent='GRAPHICS · '+(prefs.performance?'PERFORMANCE':'BALANCED');renderer.setQuality(!!prefs.performance);$('#soundButton').textContent=prefs.sound?'SOUND ON':'SOUND OFF';$('#feedbackButton').textContent=prefs.feedback?'FEEDBACK ON':'FEEDBACK OFF';renderer.reduced=!prefs.feedback||matchMedia('(prefers-reduced-motion: reduce)').matches;}
$('#cameraModeButton').onclick=()=>{const modes=['adventure','tactical','close'];prefs.cameraMode=modes[(modes.indexOf(renderer.cameraRig.mode)+1)%3];updatePrefs();savePrefs();};$('#cameraLeftButton').onclick=()=>{prefs.cameraYaw=renderer.cameraRig.yaw-Math.PI/4;updatePrefs();savePrefs();};$('#cameraRightButton').onclick=()=>{prefs.cameraYaw=renderer.cameraRig.yaw+Math.PI/4;updatePrefs();savePrefs();};$('#cameraZoomButton').onclick=()=>{prefs.cameraZoom=renderer.cameraRig.zoom>=1.2?.8:Math.round((renderer.cameraRig.zoom+.1)*10)/10;updatePrefs();savePrefs();};$('#qualityButton').onclick=()=>{prefs.performance=!prefs.performance;updatePrefs();savePrefs();};$('#soundButton').onclick=()=>{prefs.sound=!prefs.sound;updatePrefs();savePrefs();};$('#feedbackButton').onclick=()=>{prefs.feedback=!prefs.feedback;updatePrefs();savePrefs();};$('#fullButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape');}catch(e){$('#fullButton').textContent='USE DEVICE LANDSCAPE';}};
// Pointer capture gives the left thumb and each action independent multitouch ownership.
const joystick=$('#joystick');function moveStick(e){if(e.pointerId!==stick.id)return;const r=joystick.getBoundingClientRect(),max=r.width*.34,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),factor=Math.min(1,max/Math.max(1,len));stick.x=dx*factor/max;stick.y=dy*factor/max;$('#stick').style.transform=`translate(${dx*factor}px,${dy*factor}px)`;}
joystick.onpointerdown=e=>{if(!running||stick.id!==null)return;e.preventDefault();questWalker.cancel();stick.id=e.pointerId;joystick.setPointerCapture(e.pointerId);moveStick(e);};joystick.onpointermove=moveStick;joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=e=>{if(stick.id===e.pointerId){stick.id=null;stick.x=0;stick.y=0;$('#stick').style.transform='translate(0,0)';}};
for(const b of document.querySelectorAll('#actions button')){b.onpointerdown=e=>{e.preventDefault();if(!running)return;b.setPointerCapture(e.pointerId);b.classList.add('pressed');act(b.dataset.action);if(b.dataset.action==='attack'){holdAttack=true;holdDelay=.23;}};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{b.classList.remove('pressed');if(b.dataset.action==='attack')holdAttack=false;};}
const keyActions={j:'attack',' ':'dash',shift:'dash',q:'skill0',e:'skill1',f:'interact'};
addEventListener('keydown',e=>{if(e.target.closest?.('dialog[open]')||e.target.matches?.('input,textarea,select'))return;const k=e.key.toLowerCase();if([' ','arrowleft','arrowright','arrowup','arrowdown'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='escape'){if(running)pause();else if(started&&!sim.player.dead)start();return;}keys.add(k);if(keyActions[k])act(keyActions[k]);});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{resetInput();if(running)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause();});addEventListener('resize',()=>renderer.resize());addEventListener('contextmenu',e=>e.preventDefault());
function movement(){const sx=stick.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),sy=stick.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),magnitude=Math.min(1,Math.hypot(sx,sy));if(magnitude<.12)return{x:0,y:0};const ox=renderer.offset.x,oz=renderer.offset.z,n=Math.hypot(ox,oz),wx=(sx*oz+sy*ox)/n,wy=(-sx*ox+sy*oz)/n,len=Math.hypot(wx,wy);return{x:wx/len*magnitude,y:wy/len*magnitude};}
$('#interact').onclick=()=>act('interact');
function mapUI(){const story=null,hunterGoal=huntObjective(sim),navigationGoal=questWalker.customGoal||questGoal(sim),region=wildernessRegion(sim.player.x,sim.player.y),objective=navigationGoal||{x:sim.player.x,y:sim.player.y,detail:'OPEN WORLD · '+region.name+' · Enemy level '+region.level};$('#objective .quest-copy').textContent=objective.detail;
 const chest=sim.nearbyChest(),button=$('#interact');button.hidden=!chest;button.disabled=!!chest&&sim.chestLocked(chest);button.textContent=chest?(button.disabled?'CLEAR THE GUARDS':'OPEN '+chest.name.toUpperCase()):'';const person=nearbyPerson(sim);if(person){button.hidden=false;button.disabled=false;button.textContent=(person.kind?'EXAMINE ':'TALK · ')+person.name.toUpperCase();}
const hr=sim.huntRun;if(hr?.objectiveReady){const h=HUNT_BY_ID[hr.id],at=h.stages[1];if(Math.hypot(at.x-sim.player.x,at.y-sim.player.y)<230){button.hidden=false;button.disabled=false;button.textContent=h.action;}}
 const entrance=HUNTS.find(h=>Math.hypot(h.entry.x-sim.player.x,h.entry.y-sim.player.y)<230);if(entrance&&(!sim.huntRun||sim.huntRun.completed)){button.hidden=false;button.disabled=false;button.textContent='FIGHT · '+entrance.name.toUpperCase();}

 const boss=sim.activeBoss();$('#bossbar').hidden=!boss;if(boss){$('#bossName').textContent=(boss.displayName||ShadowData.enemies[boss.type].name)+(boss.broken>0?' · GUARD BROKEN':boss.phase===2?' · ENRAGED':'');$('#bossHealth').style.width=Math.max(0,boss.hp/boss.maxHp)*100+'%';}
 if(performance.now()-lastMapDraw<100)return;lastMapDraw=performance.now();const canvas=$('#minimap'),c=canvas.getContext('2d'),scale=.023,x=v=>64+(v-sim.player.x)*scale,y=v=>64+(v-sim.player.y)*scale;c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle='#46504b';for(const poly of LEVEL.polygons){c.beginPath();poly.forEach(([px,py],i)=>i?c.lineTo(x(px),y(py)):c.moveTo(x(px),y(py)));c.closePath();c.fill();}for(const e of sim.enemies)if(!e.dead){c.fillStyle=e.boss?'#f29165':'#ac6962';c.fillRect(x(e.x)-1,y(e.y)-1,e.boss?4:2,e.boss?4:2);}for(const chest of sim.chests)if(!chest.opened){c.fillStyle='#ebc975';c.fillRect(x(chest.x)-1,y(chest.y)-1,3,3);}for(const gate of WORLD_PORTALS){c.strokeStyle=portalUnlocked(sim,gate)?'#a3f0e0':'#777';c.strokeRect(x(gate.x)-3,y(gate.y)-3,6,6);}if(questWalker.path){c.save();c.strokeStyle='#ffe5a0';c.lineWidth=1.5;c.setLineDash([3,3]);c.beginPath();c.moveTo(64,64);for(const point of questWalker.path)c.lineTo(x(point.x),y(point.y));c.stroke();c.restore();}c.fillStyle='#83d4cf';c.fillRect(x(LEVEL.start.x)-2,y(LEVEL.start.y)-2,4,4);c.strokeStyle=story?'#ffdd83':'#ffffff';c.strokeRect(Math.max(5,Math.min(123,x(objective.x)))-3,Math.max(5,Math.min(123,y(objective.y)))-3,6,6);c.fillStyle='#fff';c.beginPath();c.arc(x(sim.player.x),y(sim.player.y),2.6,0,Math.PI*2);c.fill();}
function ui(dt){$('#objective').dataset.walking=questWalker.path?'true':'false';$('#objective').setAttribute('aria-label',questWalker.path?'Stop travelling':'Open wilderness map');const p=sim.player;$('#skillsButton span').textContent='Skills'+(sim.profile?' · '+pointsLeft(sim.profile):'');$('#health').style.width=p.hp/p.maxHp*100+'%';$('#healthText').textContent=Math.ceil(p.hp)+' / '+p.maxHp+(p.barrier>0?' + '+Math.ceil(p.barrier)+' SHIELD':'');$('#essence').style.width=(sim.profile?sim.profile.xp/XP_REQUIRED(sim.profile.level)*100:0)+'%';$('#characterNameHUD').textContent=sim.profile?.name||'THE SHADOW';$('#playerLevel').textContent=sim.profile?(EVOLUTION_BY_ID[sim.profile.evolution?.id]?.name||CLASSES[sim.profile.classId].name)+' · LV '+sim.profile.level:'';$('#weaponLabel').textContent=buildStatus(sim)||Math.floor(sim.profile?.xp||0)+' / '+XP_REQUIRED(sim.profile?.level||1)+' XP';const zone=areaAt(p.x,p.y);$('#zoneName').textContent=zone.toUpperCase();if(sim.profile&&zone!==lastZone){lastZone=zone;zoneTTL=0;zoneBanner.textContent='';}if(running)zoneTTL-=dt;zoneBanner.style.opacity=Math.min(1,Math.max(0,zoneTTL));$('#wave').textContent=`${sim.gold} COINS · ${sim.chests.filter(c=>c.opened).length}/${sim.chests.length} CHESTS`;mapUI();$('#combo').style.opacity=sim.combo>0?1:0;$('#combo b').textContent=sim.combo;for(let i=0;i<2;i++){const b=$('#skill'+i),t=p.skillCooldowns[i];b.classList.toggle('cooling',t>0);b.querySelector('b').textContent=Math.ceil(t);b.setAttribute('aria-label',`${sim.weapon.skills[i].name}${t>0?', '+Math.ceil(t)+' seconds remaining':', ready'}`);}$('#dash').classList.toggle('cooling',p.dashCooldown>0);$('#dash b').textContent=p.dashCooldown.toFixed(1);$('#ultimate').classList.toggle('cooling',p.ultimate<100);$('#ultimate').classList.toggle('ready',p.ultimate>=100);$('#ultimate b').textContent=Math.floor(p.ultimate)+'%';const aerial=!sim.weapon.ranged&&sim.airborneTarget();$('#heavy').classList.toggle('ready',!!aerial||(p.chainTime>0&&p.chain>=2));$('#heavy span').textContent=sim.weapon.ranged?'SPREAD':aerial?'SLAM':p.chainTime>0&&p.chain>=2?'LAUNCH':'HEAVY';$('#combo').dataset.rank=sim.style>75?'RELENTLESS':sim.style>40?'SAVAGE':'AWAKENING';$('#chainDots').textContent=sim.weapon.chain.map((a,i)=>p.chainTime>0&&i<p.chain?'◆':'◇').join(' ');$('#tutorial').style.opacity=sim.time<10?1:0;if(running)moveTTL-=dt;$('#moveName').style.opacity=Math.min(1,Math.max(0,moveTTL*3));}
let lastHudUpdate=0;
function loop(now){const dt=Math.min((now-last)/1000||0,.033);last=now;if(running){if(holdAttack){holdDelay-=dt;if(holdDelay<=0){act('attack');holdDelay=.13;}}let mv=movement();if(mv.x||mv.y)questWalker.cancel();else mv=questWalker.step(sim,dt);sim.update(dt,mv);if(dt>0)progression?.record({op:'step',dt,x:mv.x,y:mv.y});const events=sim.drainEvents();renderer.receive(events);let hit=false;for(const e of events){if(e.type==='attack'){if(!['normal','juggle'].includes(e.kind))toast(e.name);}if(e.type==='launch')toast('AIRBORNE');if(e.type==='slam')toast('EXECUTION');if(e.type==='hit')hit=true;if(e.type==='hurt'){questWalker.cancel();vibrate(30);}if(e.type==='whoosh')sound(e.kind==='gun'?'gun':['normal','juggle'].includes(e.kind)?'slash':'heavy',e.side);if(e.type==='guardBreak')toast('GUARD BROKEN');if(e.type==='bossPhase')toast(e.name+' · SECOND PHASE');if(e.type==='bossDown')toast(e.name+' DEFEATED');if(e.type==='chest'){toast('CHEST OPENED · COLLECT THE DROPS');sound('hit');}if(e.type==='levelUp')toast('LEVEL '+e.level);if(e.type==='questReady')toast(e.name+' · REWARD READY');if(e.type==='notice')toast(e.message);if(e.type==='signatureDrop'){sound('heavy');vibrate([20,45,35]);toast('SIGNATURE DROP · '+e.name);}if(e.type==='pickup'){if(e.itemId)showLootReceipt(e.itemId);toast(e.name|| (e.kind==='gold'?'+'+e.amount+' COINS':e.kind==='heal'?'HEALED +'+e.amount:e.kind==='blade'?'BLADE DAMAGE +12%':'MAX HEALTH +30'));sound('pickup');}if(e.type==='victory'){toast('WINDWARD VALE SECURED');$('#pauseTitle').textContent='Windward Vale secured.';$('#pauseCopy').textContent=`${sim.kills} raiders defeated · ${sim.gold} coins. Continue exploring or replay the fort.`;$('#resumeButton').textContent='CONTINUE EXPLORING';}if(e.type==='defeat')defeatPending=.9;}if(hit){sound('hit');vibrate(8);}if(defeatPending>0){defeatPending-=dt;if(defeatPending<=0)defeat();}}ambience.update(audio,dt,running&&prefs.sound,sim);renderer.paused=!running;renderer.render(sim,dt);if(now-lastHudUpdate>=80){ui((now-lastHudUpdate)/1000);lastHudUpdate=now;}}
progression=setupProgression({walkToRegion:id=>renderer.ready.then(()=>{const goal=regionDestination(id);if(goal)questWalker.start(sim,goal);}),walkToQuest:()=>renderer.ready.then(()=>walkToQuest()),getSim:()=>sim,previewGear:(el,p)=>renderer.mountGearPreview(el,p),setSim:(newSim,reconcile=false)=>{sim=newSim;if(!reconcile){renderer.reset();defeatPending=0;moveTTL=0;updateWeaponUI();}},pause:()=>{running=false;resetInput();},resume:()=>renderer.ready.then(()=>{if(sim.player.dead){started=true;defeat();}else start();}),toast});
$('#menuButton').onclick=()=>progression.openHub();$('#worldMapButton').onclick=()=>progression.openJourney();$('#objective').onclick=()=>{if(running){if(questWalker.path||questGoal(sim))walkToQuest();else progression.openJourney();}};$('#skillsButton').onclick=()=>progression.openSkills();$('#armoryButton').onclick=()=>progression.openInventory();$('#weaponsFromPause').onclick=()=>progression.openInventory();$('#questsButton').onclick=()=>progression.openQuests();$('#charactersButton').onclick=()=>progression.openAccount();
updatePrefs();updateWeaponUI();window.combatSnapshot=()=>({...sim.snapshot(),running});requestAnimationFrame(guardedFrame(loop,error=>{running=false;resetInput();console.error('Game frame stopped',error);const panel=document.createElement('section');panel.style.cssText='position:fixed;inset:0;z-index:10000;background:#101b24f5;color:#f4e8ce;display:grid;place-content:center;padding:24px;gap:16px;font:16px system-ui';const title=document.createElement('h2');title.textContent='Game paused after an error';const copy=document.createElement('p');copy.textContent='Reload to recover your last saved character. If this repeats, send the error below.';const detail=document.createElement('pre');detail.style.cssText='white-space:pre-wrap;max-width:80vw;font-size:12px';detail.textContent=String(error?.message||error).slice(0,180);const button=document.createElement('button');button.textContent='RELOAD GAME';button.style.cssText='padding:16px;font:inherit';button.onclick=()=>location.reload();panel.append(title,copy,detail,button);document.body.append(panel);},requestAnimationFrame));

window.selectGroundLoot=id=>{if(!running)return;questWalker.cancel();sim.selectLoot(id);progression.record({op:'loot',id});};$('#world').addEventListener('pointerdown',e=>{if(!running)return;const id=renderer.hitLoot(sim,e.clientX,e.clientY);if(id!==null){e.preventDefault();window.selectGroundLoot(id);}});

window.openStoryPerson=id=>{if(running)progression.talk(id);};

const lootReceipt=document.createElement('button');lootReceipt.className='loot-receipt';lootReceipt.hidden=true;document.querySelector('#game').append(lootReceipt);let receiptTimer;function showLootReceipt(id){const item=sim.profile?.inventory.find(i=>String(i.id)===String(id));if(!item)return;const f=itemFacts(item);lootReceipt.replaceChildren();const name=document.createElement('strong');name.textContent=item.name;const line=document.createElement('span');line.textContent=f.effect.length>145?f.effect.slice(0,142)+'…':f.effect;const hint=document.createElement('span');hint.textContent=f.style+' · TAP TO INSPECT';lootReceipt.append(name,line,hint);lootReceipt.hidden=false;lootReceipt.onclick=()=>{lootReceipt.hidden=true;progression.openInventory(id);};clearTimeout(receiptTimer);receiptTimer=setTimeout(()=>lootReceipt.hidden=true,7000);}
window.openDungeon=id=>{if(running)progression.startEncounter(id);};
window.huntWorldInteract=()=>act('interact');
