import {REGION_DESTINATIONS} from './js/region-travel.js';
import {HUNTS,HUNT_KEEPER} from './js/hunt-data.js';
import {WORLD_PORTALS} from './js/world-portals.js';
import {LEVEL} from './js/level.js';
import {CLASSES,XP_REQUIRED} from './js/rpg.js';
import {EVOLUTION_BY_ID} from './js/evolutions.js';
import {pointsLeft} from './js/skill-tree.js';
import {caravanState,caravanCurrent,TRIALS} from './js/caravan-story.js';
import {NAMED_GEAR} from './js/named-loot.js';
const paths={menu:'M4 6h16M4 12h16M4 18h16',bag:'M5 7h14l2 14H3L5 7zm3 0V5a4 4 0 018 0v2',tree:'M12 3v18M12 9L5 5M12 15l7-5M3 4h4v4H3zM17 8h4v4h-4z',quest:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',map:'M3 5l6-2 6 3 6-2v15l-6 2-6-3-6 2V5zm6-2v15m6-12v15',dungeon:'M3 21V6l4-3 5 3 5-3 4 3v15H3zm6 0v-7a3 3 0 016 0v7',shop:'M3 9l2-6h14l2 6M4 9v12h16V9M9 21v-7h6v7M2 9q3 5 5 0 2 5 5 0 2 5 5 0 2 5 5 0',book:'M12 5q-5-3-9-1v15q4-2 9 1 5-3 9-1V4q-4-2-9 1v15',person:'M7 21v-5q5-5 10 0v5M8 7a4 4 0 108 0 4 4 0 10-8 0',pause:'M8 4v16M16 4v16',blade:'M4 21l5-5M5 13l6 6M8 15L19 3l2-1-1 4L10 17',dash:'M3 5l7 7-7 7m9-14l7 7-7 7',target:'M12 2v5m0 10v5M2 12h5m10 0h5M5 12a7 7 0 1014 0 7 7 0 10-14 0',burst:'M12 2v6m0 8v6M2 12h6m8 0h6M5 5l4 4m6 6 4 4M5 19l4-4m6-6 4-4',return:'M10 5l-7 7 7 7M3 12h18'};
export const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${(paths[name]||paths.menu).split('~').map(d=>`<path d="${d}"/>`).join('')}</svg>`;
export const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const className=p=>EVOLUTION_BY_ID[p.evolution?.id]?.name||CLASSES[p.classId].name;
export function installMobileHUD(){const header=document.querySelector('#game>header');header.classList.add('combat-header');document.querySelector('.vitals').insertAdjacentHTML('afterbegin','<div class="shadow-portrait" aria-hidden="true"><svg viewBox="0 0 64 72"><path d="M5 69L9 39 20 11 32 3 45 11 57 40 61 69Z" fill="#39444a" stroke="#ac9363"/><path d="M16 40L20 20 32 12 44 20 48 40 41 59 22 59Z" fill="#04070c"/><path d="M9 64L20 45 26 65 32 55 40 65 47 45 58 64" fill="#7a363d"/></svg></div>');document.querySelector('.name').firstChild.textContent='';document.querySelector('.name').insertAdjacentHTML('afterbegin','<strong id="characterNameHUD">THE SHADOW</strong>');for(const [id,key,label] of [['skillsButton','tree','Skills'],['armoryButton','bag','Equipment'],['questsButton','quest','Guide']]){const b=document.getElementById(id);b.innerHTML=icon(key)+`<span>${label}</span>`;b.setAttribute('aria-label',label);}const b=document.createElement('button');b.id='menuButton';b.setAttribute('aria-label','Open main menu');b.innerHTML=icon('menu')+'<span>Menu</span>';header.querySelector('.menu-buttons').append(b);document.querySelector('#mapPanel').insertAdjacentHTML('afterbegin','<button id="worldMapButton" aria-label="Open world map">'+icon('map')+'</button>');for(const [id,key] of [['attack','blade'],['dash','dash'],['skill0','target'],['skill1','burst']])document.querySelector('#'+id+' i').innerHTML=icon(key);}
export function hubView(p){const s=caravanState(p),q=caravanCurrent(p);return `<div class="hub-profile"><div class="hub-sigil">K</div><div><small>YOUR JOURNEY</small><h3>${safe(p.name)}</h3><p>${className(p)} · Level ${p.level}</p></div><div class="hub-currency"><b>${p.gold.toLocaleString()}</b><span>COINS</span></div></div><section class="journey-card"><small>OPEN WORLD</small><h3>The wilderness is yours</h3><p>Hunt, loot, craft and refine your build. Stronger regions hold higher-level equipment. No quest gates.</p><button data-tab="journey">${icon('map')} CHOOSE A REGION</button></section><div class="system-grid">${[['inventory','bag','Character','Equipment & backpack'],['skills','tree','Disciplines',pointsLeft(p)+' passive points available'],['quests','quest','Wilderness guide','Region danger & progression'],['bestiary','book','Field guide','Creatures, tactics & loot'],['journey','map','World map','Regions & safe travel'],['account','person','Characters','Choose your adventurer'],['dungeons','dungeon','Boss dungeons','Repeatable bosses & crafting fragments'],['lootJournal','book','Craft weapons','Fragments, recipes & signature effects'],['wardrobe','person','Wardrobe','Earned outfits & dyes'],['loadouts','tree','Loadouts','Saved builds & practice'],['shop','shop','Cash shop','PLANNED']].map(([id,i,title,sub])=>`<button data-tab="${id}" class="system-tile ${['shop'].includes(id)?'future-system':''}">${icon(i)}<strong>${title}</strong><small>${sub}</small></button>`).join('')}</div>`;}
export function journeyView(p,player=null){return `<div class="world-route">${worldRouteMap(player)}<small>ALL REGIONS OPEN</small><h3>Choose where to explore</h3><p>Walk freely or choose a destination below. Recommended levels indicate danger, not entry requirements. Attacks or manual movement cancel auto-walk.</p><div class="region-travel-grid">${REGION_DESTINATIONS.map(r=>`<button data-walk-region="${r.id}"><b>${r.name}</b><small>WALK HERE · RECOMMENDED ${r.level}</small></button>`).join('')}</div><p>Equipment drops on the ground. Tap it to collect; gold and health are collected nearby. Salvage spare equipment for enhancement materials. Boss fragments are used in Craft weapons.</p></div>`;}
export function bestiaryView(){return `<div class="bestiary-grid">${[['Glassback Spider','GLASSROOT RAVINE','A low, eight-legged crystal scavenger. Its fixed-target shard web slows you after a visible warning. Move before the circle fills.','spider'],['Cinder Golem','CINDERWASH BASIN','A heavy volcanic creature with a glowing core. Its slam leaves heated ground, then exposes it during recovery.','golem'],['Ridge Stalker','AMBERSTEP / WHITEWIND','A pale, horned mountain predator. Its pounce commits to a direction; dodge across the marked lane.','beast'],['Signal Scout','CARAVAN ESCORTS','Calls two reinforcements after two uninterrupted seconds. Hit the scout before it finishes.','scout'],['Shieldguard','CHECKPOINTS / FORTRESS','Moves ahead of ranged allies. Flank its shield or break its guard with a class skill.','guard']].map(([name,zone,text,type])=>`<article><div class="bestiary-emblem ${type}">${icon(type==='golem'?'burst':type==='spider'?'target':'blade')}</div><small>${zone}</small><h3>${name}</h3><p>${text}</p></article>`).join('')}</div><h3>Named equipment · target your hunt</h3><p>Each Chapter Two boss has a separate 25% named-item roll, split equally between its two signatures. Normal equipment rolls are independent. Identical granted passives do not stack with the atlas.</p><div class="named-catalog">${Object.values(NAMED_GEAR).map(n=>`<article><small>${n.source}</small><h4>${n.name}</h4><p>${n.text}</p></article>`).join('')}</div><button data-tab="tables">FULL LOOT PROBABILITIES</button>`;}
export function futureView(kind){return `<section class="future-preview">${icon(kind==='shop'?'shop':'dungeon')}<small>FUTURE SYSTEM · NOT AVAILABLE YET</small><h3>${kind==='shop'?'The merchant quarter':'Beyond the fortress gates'}</h3><p>${kind==='shop'?'This space is reserved for a future cash shop. There are no purchases, premium balances or checkout in this build.':'This space is reserved for future instanced dungeons and party expeditions. Matchmaking and multiplayer are not available in this build.'}</p><button data-tab="hub">RETURN TO MENU</button></section>`;}
export function trainingView(p){const s=caravanState(p),t=s.training,definition=t&&TRIALS[t.id],id=p.evolution?.id,next=TRIALS[id];return `<div class="trainer-dialogue"><small>CAPTAIN MARYAM · DISCIPLINE INSTRUCTOR</small><h3>Practice with purpose</h3><p>“A title does not make a fighter. Show me you understand what your discipline asks of you, then bring that skill back to the road.”</p>${t&&!t.claimed?`<h4>${definition.name}</h4><p>${definition.text}</p><b>${t.progress} / ${definition.goal}</b><p>Reward: 500 XP, 250 coins and Instructor’s Grips dropped beside you.</p><button data-training="claim" ${t.progress<definition.goal?'disabled':''}>CLAIM TRAINING REWARD</button>`:next?`<h4>${next.name}</h4><p>${next.text}</p><button data-training="start" ${s.trainingDone.includes(id)?'disabled':''}>${s.trainingDone.includes(id)?'COMPLETED':'ACCEPT CHALLENGE'}</button>`:'<p>Choose a class evolution in Disciplines first.</p>'}<button id="leaveDialogue">RETURN TO CAMP</button></div>`;}

export function worldRouteMap(player){const x=v=>(v+3800)/15,y=v=>(v+4200)/15;return `<svg class="world-route-map" viewBox="0 0 1040 510" role="img" aria-label="Connected world map. Gold lines mark continuous roads. White dot marks your location."><rect width="1040" height="510" fill="#182b30"/>${LEVEL.polygons.map(p=>`<polygon points="${p.map(([a,b])=>x(a)+','+y(b)).join(' ')}" fill="#526d58" stroke="none"/>`).join('')}${LEVEL.paths.map(p=>`<polyline points="${p.map(([a,b])=>x(a)+','+y(b)).join(' ')}" fill="none" stroke="#d1b77e" stroke-width="2"/>`).join('')}${HUNTS.map(h=>`<polyline points="${[h.entry,...h.stages].map(p=>x(p.x)+','+y(p.y)).join(' ')}" fill="none" stroke="${h.color}" stroke-width="3" stroke-dasharray="5 3"/><circle cx="${x(h.entry.x)}" cy="${y(h.entry.y)}" r="4" fill="${h.color}"/><text x="${x(h.stages[2].x)-35}" y="${y(h.stages[2].y)+18}">${h.name}</text>`).join('')}${WORLD_PORTALS.map(p=>`<rect x="${x(p.x)-5}" y="${y(p.y)-5}" width="10" height="10" fill="#f2cd82"/><text x="${x(p.x)+10}" y="${y(p.y)+5}">${p.name}</text>`).join('')}<circle cx="${x(HUNT_KEEPER.x)}" cy="${y(HUNT_KEEPER.y)}" r="4" fill="#f3d4a2"/><text x="${x(HUNT_KEEPER.x)-12}" y="${y(HUNT_KEEPER.y)+20}">NADIA</text><text x="80" y="70">WINDWARD VALE</text><text x="655" y="62">OPEN WILDERNESS</text>${player?`<circle cx="${x(player.x)}" cy="${y(player.y)}" r="5" fill="white" stroke="#162727" stroke-width="2"/>`:''}</svg>`;}
