import {replayWithoutBlocking} from './replay-scheduler.js';
import {fieldGuide,lairsView,loreView} from './wilderness-ui.js';
import {questGoal,campaignComplete} from './quest-navigation.js';
import {gameRequest} from './network-request.js';
import {huntJournal,huntsView,lootJournalView,wardrobeView,loadoutsView,temperOptions,catalogItems,previewProfile} from './hunter-ui.js';
import {itemSummary,bindInfo,helpButton,closeItemInfo} from './item-info.js';
import {hunterState} from './js/hunt-data.js';
import {salvageView,materialWallet} from './salvage-ui.js';
import {salvageState,salvageYield,materialText,matchesSalvage,protectedItem,enhanceCost,enhancePreview,itemKey,validSalvageSelection} from './js/salvage.js';
import {hubView,journeyView,bestiaryView,futureView,trainingView,icon} from './mobile-ui.js';
import {caravanState,CARAVAN_STORY,TRIALS} from './js/caravan-story.js';
import {NAMED_GEAR} from './js/named-loot.js';
import {EVOLUTION_BY_ID} from './js/evolutions.js';
import {mountSkillTree} from './skill-tree-ui.js';
import {dialogueView,journalView} from './story-ui.js';
import {PEOPLE,personPresent} from './js/story.js';
import {gearIcon} from './gear-visuals.js';
import {applyCommands} from './js/commands.js';
import CombatSim from './js/combat.js';
import {CLASSES,SLOTS,RARITIES,QUESTS,LOOT_TABLES,REGIONS,XP_REQUIRED,stats,gearScore} from './js/rpg.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rarity=i=>RARITIES.find(r=>r.id===i.rarity);
export function setupProgression({getSim,setSim,pause,resume,toast,previewGear,walkToQuest,walkToRegion}){
 const layer=document.createElement('section');layer.id='rpgLayer';document.querySelector('#game').append(layer);let account=null,revision=0,commands=[],pending=null,busy=false,selected=null,currentView='account',classId='katana',message='Connecting to your account…',syncError=false,backlogPaused=false;let disposePreview=null,bagFilter='all',talkingTo=null,salvageSelection=null;let wardrobeDraft=null;
 const status=document.createElement('span');status.id='saveStatus';document.querySelector('#game').append(status);
 const request=gameRequest;
 function record(c){if(getSim().profile)commands.push(c);}
 async function flush(){if(busy||!getSim().profile)return;if(!pending&&!commands.length)return;busy=true;status.textContent='Saving…';if(!pending)pending={id:getSim().profile.id,revision,batchId:crypto.randomUUID(),commands:commands.splice(0,400)};try{const out=await request('batch',pending);revision=out.revision;pending=null;const authoritative=CombatSim.restore(out.state);await replayWithoutBlocking(authoritative,commands,state=>setSim(state,true));syncError=false;status.textContent='Saved';if(backlogPaused&&commands.length<180){backlogPaused=false;resume();}}catch(e){syncError=true;status.textContent='SAVE PAUSED · RETRY';pause();message=e.message;show('connection');}finally{busy=false;}}
 async function drain(){while(busy)await new Promise(r=>setTimeout(r,50));while(pending||commands.length){await flush();if(syncError)throw Error(message);}}
 function act(c){const sim=getSim();let ok=false;if(c.op==='hunter')ok=sim.hunterAction(c.action,c.id,c.value);if(c.op==='salvageBatch')ok=sim.salvageBatch(c.ids);if(c.op==='autoSalvage')ok=sim.configureSalvage(c.enabled,c.rarities);if(c.op==='lockItem')ok=sim.lockItem(c.id);if(c.op==='enhance')ok=sim.enhanceItem(c.id);if(c.op==='travel')ok=sim.travel(c.id);if(c.op==='training')ok=sim.trainingAction(c.action);if(c.op==='evolution')ok=sim.evolutionAction(c.action,c.id);if(c.op==='tree')ok=sim.treeAction(c.action,c.id);if(c.op==='story')ok=sim.storyAction(c.id,c.choice);if(c.op==='best')ok=sim.equipBest();if(c.op==='equip')ok=sim.equipItem(c.id);if(c.op==='unequip')ok=sim.unequipItem(c.slot);if(c.op==='salvage')ok=sim.salvageItem(c.id);if(c.op==='quest')ok=sim.claimQuest(c.id);if(ok){record(c);draw();if(c.op==='hunter'){const f=layer.querySelector('#rpgFeedback');if(f)f.textContent=({craft:'Signature crafted. Open Character to inspect and equip it.',temper:'Property applied. Item locked against salvage.',look:'Appearance applied. Combat stats unchanged.',savePreset:'Loadout saved. Equipped items locked.',loadPreset:'Loadout equipped.',start:'Boss encounter started. Return to the world and follow your minimap marker.'})[c.action]||'';}flush();}else{const feedback=layer.querySelector('#rpgFeedback');if(feedback)feedback.textContent='Action unavailable. Check safety, required materials, backpack space, or missing saved equipment.';else toast('Cannot perform that action now');}return ok;}
 function show(view){closeItemInfo();pause();document.querySelector('#overlay').classList.add('hidden');layer.hidden=false;currentView=view;draw();}
 function close(){if(syncError)return;closeItemInfo();disposePreview?.();disposePreview=null;layer.hidden=true;resume();}
 function shell(title,html,nav=true){const previous=layer.querySelector('.rpg-content'),scroll=previous?.dataset.view===currentView?previous.scrollTop:0;disposePreview?.();disposePreview=null;layer.innerHTML=`<div class="rpg-window"><header class="rpg-heading"><div><small>KAGE · THE OPEN WILDERNESS</small><h2>${title}</h2></div>${getSim().profile?'<button id="rpgClose" aria-label="Return to combat">RETURN</button>':''}</header>${nav?'<nav class="rpg-tabs"><button data-tab="hub">MENU</button><button data-tab="inventory">CHARACTER</button><button data-tab="skills">SKILLS</button><button data-tab="quests">GUIDE</button><button data-tab="tables">LOOT GUIDE</button><button data-tab="account">CHARACTERS</button></nav>':''}<div class="rpg-content" data-view="${esc(currentView)}">${html}</div><div id="rpgFeedback" role="status" aria-live="polite"></div></div>`;layer.querySelector('#rpgClose')?.addEventListener('click',close);layer.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===currentView);b.onclick=()=>{currentView=b.dataset.tab;selected=null;wardrobeDraft=null;draw();};});bindInfo(layer,getSim().profile,getSim().profile?catalogItems(getSim().profile):[]);layer.querySelector('.rpg-content').scrollTop=scroll;}
 function craftAndInspect(id){if(act({op:'hunter',action:'craft',id})){selected=getSim().profile.inventory.at(-1).id;show('inventory');toast('WEAPON CRAFTED · SELECT EQUIP TO USE IT');}}
 function guideDungeon(id){close();if(layer.hidden)walkToRegion?.(id);}
 function draw(){const p=getSim().profile;
 if(currentView==='connection'){shell('Save interrupted',`<p>${esc(message)}</p><p>Play is paused so progress does not get ahead of your saved character.</p><button id="retrySave">RETRY SAVE</button><button id="reloadSave">RELOAD LAST SAVE</button>`,false);layer.querySelector('#retrySave').onclick=async()=>{await flush();if(!syncError)close();};layer.querySelector('#reloadSave').onclick=()=>{if(confirm('Discard unsaved actions and reload the last confirmed save?'))location.reload();};return;}
 if(currentView==='account'){const cards=account?.characters||[];shell('Choose your character',`<div class="account-bar"><span>${esc(account?.email||message)}</span><a href="/signout-with-chatgpt?return_to=%2F" target="_top">Sign out</a></div>${!account?'<p>Sign in securely to save characters, equipment and skills.</p><a class="rpg-primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">SIGN IN WITH CHATGPT</a><button id="retryAccount">RETRY CONNECTION</button>':`<div class="character-list">${cards.map(c=>`<button data-character="${esc(c.id)}"><strong>${esc(c.name)}</strong><span>${EVOLUTION_BY_ID[c.evolution?.id]?.name||CLASSES[c.classId].name} · Level ${c.level}</span><small>${c.inventory.length} items · ${c.gold} coins</small></button>`).join('')}</div>${cards.length<4?`<h3>Create a character</h3><div class="class-list">${Object.entries(CLASSES).map(([id,c])=>`<button data-class="${id}" class="${id===classId?'selected':''}"><strong>${c.name}</strong><span>${c.weapon}</span><small>${c.role}</small></button>`).join('')}</div><form id="createCharacter"><label>Character name<input id="characterName" maxlength="20" minlength="2" required autocomplete="off" placeholder="Your character’s name"></label><button class="rpg-primary" type="submit">CREATE ${CLASSES[classId].name.toUpperCase()}</button></form><p class="rpg-muted">Four character slots. Your class determines which weapons you can equip.</p>`:''}`}<p id="accountMessage" role="status">${account?esc(message):''}</p>`,!!p);
 layer.querySelector('#retryAccount')?.addEventListener('click',loadAccount);layer.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{classId=b.dataset.class;message='';draw();});layer.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>enter(b.dataset.character));layer.querySelector('#createCharacter')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await drain();const {profile}=await request('characters',{name:layer.querySelector('#characterName').value,classId});account.characters.push(profile);await enter(profile.id);}catch(error){message=error.message;draw();}});return;}
 if(!p){currentView='account';draw();return;}
 
 if(currentView==='hunts'||currentView==='dungeons'){shell('Boss dungeons',lairsView(getSim()));layer.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>craftAndInspect(b.dataset.craft));layer.querySelector('[data-walk-hunt]')?.addEventListener('click',()=>{close();if(layer.hidden)walkToQuest?.();});layer.querySelectorAll('[data-find-dungeon]').forEach(b=>b.onclick=()=>guideDungeon(b.dataset.findDungeon));layer.querySelectorAll('[data-hunt-start]').forEach(b=>b.onclick=()=>{if(act({op:'hunter',action:'start',id:b.dataset.huntStart,value:b.dataset.tier})){close();if(layer.hidden)walkToQuest?.();}});layer.querySelectorAll('[data-hunter-action]').forEach(b=>b.onclick=()=>act({op:'hunter',action:b.dataset.hunterAction}));return;}
 if(currentView==='lootJournal'){shell('Signature loot journal',lootJournalView(getSim()));layer.querySelectorAll('[data-find-dungeon]').forEach(b=>b.onclick=()=>guideDungeon(b.dataset.findDungeon));layer.querySelector('#huntLootFilter').onchange=e=>act({op:'hunter',action:'filter',id:e.target.value});layer.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>craftAndInspect(b.dataset.craft));return;}
 if(currentView==='loadouts'){shell('Loadouts & training',loadoutsView(getSim()));layer.querySelectorAll('[data-save-preset]').forEach(b=>b.onclick=()=>act({op:'hunter',action:'savePreset',id:b.dataset.savePreset}));layer.querySelectorAll('[data-load-preset]').forEach(b=>b.onclick=()=>act({op:'hunter',action:'loadPreset',id:b.dataset.loadPreset}));layer.querySelectorAll('[data-hunter-action]').forEach(b=>b.onclick=()=>{if(act({op:'hunter',action:b.dataset.hunterAction})&&b.dataset.hunterAction==='train')close();});return;}
 if(currentView==='wardrobe'){wardrobeDraft??=structuredClone(hunterState(p).cosmetic);shell('Wardrobe',wardrobeView(p,wardrobeDraft));layer.querySelectorAll('[data-preview-outfit]').forEach(b=>b.onclick=()=>{wardrobeDraft.outfit=b.dataset.previewOutfit||null;draw();});layer.querySelectorAll('[data-preview-dye]').forEach(b=>b.onclick=()=>{wardrobeDraft.dye=b.dataset.previewDye;draw();});layer.querySelectorAll('[data-preview-slot]').forEach(b=>b.onchange=()=>{wardrobeDraft.slots??={};wardrobeDraft.slots[b.dataset.previewSlot]=b.value;draw();});layer.querySelector('#applyWardrobe').onclick=()=>act({op:'hunter',action:'look',value:wardrobeDraft});disposePreview=previewGear?.(layer.querySelector('#wardrobePreview'),previewProfile(p,wardrobeDraft));return;}
 if(currentView==='hub'){shell('Adventurer’s menu',hubView(p));return;}
 if(currentView==='journey'){shell('World & travel',journeyView(p,getSim().player));layer.querySelectorAll('[data-walk-region]').forEach(b=>b.onclick=()=>{close();if(layer.hidden)walkToRegion?.(b.dataset.walkRegion);});return;}
 if(currentView==='bestiary'){shell('Field guide',bestiaryView());return;}
 if(currentView==='dungeons'||currentView==='shop'){shell(currentView==='shop'?'Cash shop':'Dungeons',futureView(currentView));return;}
 if(currentView==='skills'){shell('The Discipline Atlas','<div id="skillAtlas"></div>');disposePreview=mountSkillTree(layer.querySelector('#skillAtlas'),getSim(),act);return;}
 if(currentView==='dialogue'){const v=loreView(talkingTo);shell(v.title,v.html,false);layer.querySelector('#leaveDialogue').onclick=close;return;}
 if(currentView==='salvage'){
 salvageSelection=validSalvageSelection(p,salvageSelection||[]);shell('Salvage & auto-dismantle',salvageView(p,salvageSelection));const cfg=salvageState(p);const picked=()=>validSalvageSelection(getSim().profile,salvageSelection||[]);
 layer.querySelector('[data-forge-back]').onclick=()=>{currentView='inventory';draw();};
 layer.querySelector('#autoSalvageToggle').onclick=()=>act({op:'autoSalvage',enabled:!cfg.enabled,rarities:cfg.rarities});
 layer.querySelectorAll('[data-salvage-rarity]').forEach(b=>b.onclick=()=>{salvageSelection=null;const r=b.dataset.salvageRarity;act({op:'autoSalvage',enabled:cfg.enabled,rarities:cfg.rarities.includes(r)?cfg.rarities.filter(v=>v!==r):[...cfg.rarities,r]});});
 layer.querySelectorAll('input[data-salvage-item]').forEach(input=>input.onchange=()=>{const id=input.dataset.salvageItem,ids=picked(),key=itemKey(id),has=ids.some(v=>itemKey(v)===key);salvageSelection=has?ids.filter(v=>itemKey(v)!==key):[...ids,key];salvageSelection=validSalvageSelection(p,salvageSelection);draw();});
 layer.querySelector('#selectSalvageFiltered').onclick=()=>{salvageSelection=validSalvageSelection(p,p.inventory.filter(i=>matchesSalvage(p,i)).map(i=>i.id));draw();};
 layer.querySelector('#clearSalvageSelection').onclick=()=>{salvageSelection=[];draw();};
 layer.querySelector('#confirmSalvage').onclick=()=>{const ids=picked();if(!ids.length)return;salvageSelection=[];layer.querySelector('#rpgFeedback').textContent='';act({op:'salvageBatch',ids});};return;
 }
 if(currentView==='inventory'){
 const st=stats(p),item=p.inventory.find(i=>String(i.id)===String(selected))||Object.values(p.equipment).find(i=>i&&String(i.id)===String(selected)),equipped=item&&p.equipment[item.slot]?.id===item.id,old=item&&p.equipment[item.slot];
 const icon=(i,slot)=>`<img src="${gearIcon(i,slot,p.classId)}" alt="${esc(i?.name||slot)}" draggable="false">`;
 const filtered=p.inventory.filter(i=>bagFilter==='all'||(bagFilter==='weapon'?i.slot==='weapon':i.slot!=='weapon')).sort((a,b)=>gearScore(b)-gearScore(a));
 shell(`${esc(p.name)} · ${CLASSES[p.classId].name}`,`<div class="loadout-top"><div><span class="gear-level">LEVEL ${p.level}</span><span>${p.gold} COINS</span></div><div class="loadout-buttons"><button id="openSalvage">SALVAGE / AUTO</button><button id="equipBest" class="rpg-primary">EQUIP BEST</button></div></div><div class="gear-summary"><span>POWER <b>+${Math.round(getSim().damageBonus*100)}%</b></span><span>ARMOR <b>${st.armor}</b></span><span>HEALTH <b>${st.health}</b></span></div>
 ${materialWallet(p)}<div class="loadout-layout"><section class="paperdoll"><div id="gearPreview" aria-label="Equipped character. Drag to rotate."></div><div class="portrait-caption">DRAG TO ROTATE</div>${SLOTS.map(slot=>{const i=p.equipment[slot];return `<button class="paper-slot slot-${slot} ${i?.id===selected?'selected':''} ${i?'':'empty'}" data-item="${i?.id||''}" style="--rarity:${i?rarity(i).color:'#697980'}" aria-label="${slot}: ${esc(i?.name||'empty')}">${icon(i,slot)}<span>${slot.toUpperCase()}</span>${i?`<small>iLv ${i.level}</small>`:''}</button>`;}).join('')}</section>
 <section class="backpack"><div class="backpack-title"><h3>BACKPACK</h3><span>${p.inventory.length} / 30</span></div><div class="bag-filters">${[['all','ALL'],['weapon','WEAPONS'],['armor','ARMOR']].map(([id,label])=>`<button data-filter="${id}" class="${bagFilter===id?'active':''}">${label}</button>`).join('')}</div><div class="bag-grid">${filtered.map(i=>`<button class="bag-cell ${selected===i.id?'selected':''}" data-item="${i.id}" style="--rarity:${rarity(i).color}" aria-label="${esc(i.name)}, ${rarity(i).name}, item level ${i.level}">${icon(i,i.slot)}<small>${i.level}${i.enhancement?` +${i.enhancement}`:''}</small>${i.locked?'<span class="gear-protected">LOCKED</span>':''}${i.requiredLevel>p.level||i.classId&&i.classId!==p.classId?'<span class="gear-lock">×</span>':''}</button>`).join('')}${Array.from({length:Math.max(0,30-filtered.length)},()=>'<div class="bag-empty"></div>').join('')}</div><p class="rpg-muted">Tap an item to compare. Equipment on the ground is collected by tapping it.</p></section></div>
 <section class="gear-inspect">${item?`<div class="inspect-icon" style="--rarity:${rarity(item).color}">${icon(item,item.slot)}</div><div class="inspect-info"><small style="color:${rarity(item).color}">${rarity(item).name.toUpperCase()} · ${item.slot.toUpperCase()} · ITEM LEVEL ${item.level}</small><h3>${esc(item.name)}${item.enhancement?` +${item.enhancement}`:''}</h3>${item.signature?`<p class="signature-effect">${esc(NAMED_GEAR[item.signature]?.text||'')}</p>`:''}<p>${item.classId?CLASSES[item.classId].name+' only · ':''}Requires level ${item.requiredLevel} · Score ${gearScore(item)} ${helpButton('score')}</p>${itemSummary(item)}<div class="inspect-stats">${['power','armor','health'].map(k=>`<span>${k.toUpperCase()} ${helpButton(k)} <b>${item.stats[k]}</b>${old&&!equipped?` <em class="${item.stats[k]>=old.stats[k]?'stat-up':'stat-down'}">${item.stats[k]-old.stats[k]>=0?'+':''}${item.stats[k]-old.stats[k]}</em>`:''}</span>`).join('')}</div>${temperOptions(item,p)}</div><div class="inspect-actions">${equipped?item.slot!=='weapon'?'<button id="unequipItem">UNEQUIP</button>':'<strong>EQUIPPED</strong>':`<button id="equipItem" class="rpg-primary" ${item.requiredLevel>p.level||item.classId&&item.classId!==p.classId?'disabled':''}>EQUIP</button><button id="salvageItem" ${protectedItem(item)?'disabled':''}>SALVAGE · ${materialText(salvageYield(item))}</button>`}<button id="lockItem">${item.locked?'UNLOCK ITEM':'LOCK ITEM'}</button>${(item.enhancement||0)<5?`<button id="enhanceItem" ${!getSim().canEditTree()||Object.entries(enhanceCost(item)).some(([k,v])=>p.materials[k]<v)?'disabled':''}>ENHANCE +${(item.enhancement||0)+1}</button><small>${materialText(enhanceCost(item))}<br>${Object.entries(enhancePreview(item)).filter(([k,v])=>v>0).map(([k,v])=>k+' '+item.stats[k]+' → '+v).join(' · ')}<br>Guaranteed success · Safe areas only</small>`:'<strong>ENHANCEMENT MAX +5</strong>'}</div>`:'<h3>Select equipment to compare</h3><p>Equip Best compares base stats and preserves hunt signature weapons. Tap an item to read its effect, trade-off and source.</p>'}</section>`);
 layer.querySelectorAll('[data-temper]').forEach(b=>b.onclick=()=>act({op:'hunter',action:'temper',id:b.dataset.temperItem,value:b.dataset.temper}));
 layer.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=b.dataset.item;draw();});layer.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{bagFilter=b.dataset.filter;draw();});layer.querySelector('#equipBest').onclick=()=>{if(!getSim().equipBest()){toast('Your best eligible gear is already equipped');return;}record({op:'best'});draw();flush();};layer.querySelector('#equipItem')?.addEventListener('click',()=>act({op:'equip',id:selected}));layer.querySelector('#unequipItem')?.addEventListener('click',()=>act({op:'unequip',slot:item.slot}));layer.querySelector('#salvageItem')?.addEventListener('click',()=>{salvageSelection=validSalvageSelection(p,[selected]);currentView='salvage';draw();});layer.querySelector('#openSalvage').onclick=()=>{salvageSelection=[];currentView='salvage';draw();};layer.querySelector('#lockItem')?.addEventListener('click',()=>act({op:'lockItem',id:selected}));layer.querySelector('#enhanceItem')?.addEventListener('click',()=>act({op:'enhance',id:selected}));disposePreview=previewGear?.(layer.querySelector('#gearPreview'),p);return;
 }
 if(currentView==='quests'){shell('Wilderness guide',fieldGuide(getSim()));return;}
 shell('Windward Vale · Loot guide',`<p>Equipment rolls separately from coins and supplies. Percentages below are conditional on an equipment drop. Rolls are independent; a rare item is never guaranteed unless stated.</p><div class="table-scroll"><table><thead><tr><th>Source</th><th>Equipment chance</th><th>Common</th><th>Uncommon</th><th>Rare</th><th>Epic</th><th>Legendary</th><th>Eligible slots</th></tr></thead><tbody>${Object.entries(LOOT_TABLES).map(([id,t])=>`<tr><td>${id}</td><td>${t.chance*100}% × ${t.rolls||1}</td>${t.rarities.map(n=>`<td>${n}%</td>`).join('')}<td>${t.slots.join(', ')}</td></tr>`).join('')}</tbody></table></div><h3>Regional item levels</h3>${Object.values(REGIONS).map(r=>`<p>${r.name}: <b>item level ${r.min}–${r.max}</b></p>`).join('')}<p>80% of weapon rolls target your class; the other 20% roll among all four classes. Required character level is item level minus one, minimum level 1. Item level and rarity both scale stats.</p>`);
 }
 async function loadAccount(){message='Connecting…';show('account');try{account=await request('account');message='';draw();}catch(e){message=e.message;account=null;draw();}}
 async function enter(id,restart=false){try{await drain();const data=await request('run',{id,restart});revision=data.revision;commands=[];pending=null;syncError=false;setSim(CombatSim.restore(data.state));layer.hidden=true;resume();status.textContent='Saved';if(backlogPaused&&commands.length<180){backlogPaused=false;resume();}}catch(e){message=e.message;draw();}}
 const timer=setInterval(()=>{if(commands.length>350){backlogPaused=true;pause();status.textContent='Waiting for save…';flush();}else flush();},1800);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)flush();});
 status.onclick=()=>{if(syncError)show('connection');};
 loadAccount();return{record,flush,act,startEncounter:id=>act({op:'hunter',action:'start',id,value:'standard'}),talk:id=>{const n=PEOPLE.find(n=>n.id===id),sim=getSim();if(!n||!sim.profile||sim.player.dead||!personPresent(sim.profile,n))return;if(Math.hypot(n.x-sim.player.x,n.y-sim.player.y)>230){toast('MOVE CLOSER TO '+n.name.toUpperCase());return;}talkingTo=id;show('dialogue');},openHub:()=>show('hub'),openJourney:()=>show('journey'),openInventory:(id=null)=>{selected=id;show('inventory');},openSkills:()=>show('skills'),openDungeon:id=>{show('dungeons');layer.querySelector('[data-dungeon-card="'+id+'"]')?.scrollIntoView({block:'start'});},openQuests:()=>show('quests'),openAccount:async()=>{try{await drain();}catch{}loadAccount();},restart:()=>{if(getSim().player.dead||confirm('Start a new expedition? Equipment, XP and skill allocations are kept. Uncollected ground drops are left behind.'))enter(getSim().profile.id,true);},ready:()=>!!getSim().profile&&!syncError,showAccount:()=>show('account')};
}
