import {nearbyRenderIds,renderBudget} from './render-budget.js';
import {syncChests} from './chest-renderer.js';
import {planWorldMarkers,paintMarker} from './world-markers.js';
import {AdventureCamera} from './camera-rig.js';
import {projectedPoint} from './world-visibility.js';
import {buildAtmosphere} from './landscape-atmosphere.js';
import {buildHuntScenery,updateHuntMarkers} from './hunt-scenery.js';
import {motionSample,clipPhase} from './js/attack-timing.js';
import {createCreature,updateCreature,disposeCreature} from './creature-rigs.js';
import EnemyData from './js/weapons.js';
import {updateEnemyBars,clearEnemyBars,lootLabelIds} from './combat-hud.js';
import {surfaceAt} from './surface-fx.js';
import {buildDarkWorld as buildValley} from './dark-world.js';
import {PEOPLE,currentStory,personPresent} from './js/story.js';
import {syncGear,gearMesh,disposeGear} from './gear-visuals.js';
import {RARITIES} from './js/rpg.js';
import {LEVEL,inFloor} from './js/level.js';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneRig } from 'three/addons/utils/SkeletonUtils.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
const C=THREE,TAU=Math.PI*2,unit=.01;
const mat=(color,roughness=.85,metalness=.1)=>new C.MeshStandardMaterial({color,roughness,metalness});
const glow=(color,opacity=1)=>new C.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,blending:C.AdditiveBlending,side:C.DoubleSide});
function mesh(geo,material,parent,x=0,y=0,z=0){const m=new C.Mesh(geo,material);m.position.set(x,y,z);if(parent)parent.add(m);return m;}
const V=new C.Vector3(),Q=new C.Quaternion();
export default class ShadowRenderer {
 constructor(canvas){
  this.mobile=matchMedia("(pointer: coarse)").matches;this.budget=renderBudget(this.mobile,false);this.canvas=canvas;this.renderer=new C.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.budget.pixelRatio));this.renderer.outputColorSpace=C.SRGBColorSpace;this.renderer.toneMapping=C.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=C.PCFSoftShadowMap;
  this.scene=new C.Scene();this.scene.background=new C.Color('#a5d4d9');this.scene.fog=new C.Fog('#b0c1c4',65,155);this.camera=new C.PerspectiveCamera(42,1,.1,90);this.focus=new C.Vector3(0,.45,.9);this.offset=new C.Vector3(9,13,12);this.effects=[];this.particles=[];this.labels=[];this.ghosts=[];this.actors=new Map();this.shake=0;this.flash=0;this.reduced=false;this.loaded=false;this.time=0;this.lastHit=0;
  this.cameraRig=new AdventureCamera(this.camera,this.focus,this.offset);this.scene.add(new C.HemisphereLight('#d7e6f1','#858574',1.8));const moon=new C.DirectionalLight('#fff0d5',2.3);moon.position.set(-6,11,-7);moon.castShadow=true;moon.shadow.mapSize.set(this.budget.shadowSize,this.budget.shadowSize);moon.shadow.camera.left=-17;moon.shadow.camera.right=17;moon.shadow.camera.top=17;moon.shadow.camera.bottom=-17;moon.shadow.camera.near=.5;moon.shadow.camera.far=60;moon.shadow.bias=-.00015;moon.shadow.normalBias=.025;moon.shadow.radius=2;this.sun=moon;this.scene.add(moon);this.scene.add(moon.target);this.scene.add(new C.AmbientLight('#d4e4e9',.45));const rim=new C.DirectionalLight('#c4e0ed',.9);rim.position.set(4,4,8);this.scene.add(rim);
  this.environment();this.atmosphere=buildAtmosphere(this.scene);this.makeParticleSystem();this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new C.Vector2(1,1),.18,.4,1.3);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.resize();
  this.labelLayer=document.createElement('div');this.labelLayer.className='damage-layer';document.querySelector('#game').append(this.labelLayer);
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();window.pauseCombat?.();document.querySelector('#pauseCopy').textContent='Graphics paused. Restore the app or restart to continue.';});
  canvas.addEventListener('webglcontextrestored',()=>location.reload());
  const loader=new GLTFLoader();this.ready=Promise.all([loader.loadAsync('./models/shadow.glb'),loader.loadAsync('./models/guard.glb')]).then(([hero,enemy])=>{this.templates={hero,enemy};this.loaded=true;});
 }
 setQuality(performance){this.performanceMode=performance;this.budget=renderBudget(this.mobile,performance);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.budget.pixelRatio));this.renderer.shadowMap.enabled=!performance;if(this.bloom)this.bloom.enabled=this.budget.postprocessing;this.resize();}
 setCamera(settings){this.cameraRig.configure({...settings,aspect:this.width/this.height});}
 resize(){this.width=innerWidth;this.height=innerHeight;this.renderer.setSize(this.width,this.height,false);this.cameraRig.configure({aspect:this.width/this.height});this.composer?.setPixelRatio(this.renderer.getPixelRatio());this.composer?.setSize(this.width,this.height);}

 environment(){
  this.settlement=buildValley(this.scene);this.huntScenery={update(){}};this.portals={update(){}};this.windObjects=[];this.fires=[];
  const wood=mat('#a88353'),iron=mat('#5e706b',.7,.2);this.chestObjects=new Map();syncChests(this.scene,this.chestObjects,LEVEL.chests,0);
  this.gate=new C.Group();

 }
 makeParticleSystem(){this.maxParticles=600;const geometry=new C.BufferGeometry();this.positions=new Float32Array(this.maxParticles*3);this.colors=new Float32Array(this.maxParticles*3);geometry.setAttribute('position',new C.BufferAttribute(this.positions,3));geometry.setAttribute('color',new C.BufferAttribute(this.colors,3));const material=new C.PointsMaterial({size:.07,vertexColors:true,transparent:true,opacity:.9,depthWrite:false,blending:C.AdditiveBlending});this.particleMesh=new C.Points(geometry,material);this.particleMesh.frustumCulled=false;this.scene.add(this.particleMesh);this.telegraphPool=[];}
 makeSword(parent,id,enemy=false){const group=new C.Group(),length=id==='greatsword'?1.65:id==='twins'?.72:1.32,width=id==='greatsword'?.16:.065;parent?.add(group);const steel=mat(enemy?'#536069':'#b8c5ce',.28,.85);if(id==='pistols'){mesh(new C.BoxGeometry(.13,.52,.16),steel,group,0,.20,0);mesh(new C.BoxGeometry(.12,.19,.22),mat('#554332'),group,0,-.05,-.06);const edge=mesh(new C.ConeGeometry(.11,.28,6),glow('#ffd588',0),group,0,.57,0);group.userData={edge,tip:new C.Vector3(0,.65,0),base:new C.Vector3(0,.2,0)};return group;}const shape=new C.Shape();shape.moveTo(-width,0);shape.lineTo(-width*.7,length-.16);shape.lineTo(0,length);shape.lineTo(width,length-.15);shape.lineTo(width,0);shape.closePath();const blade=mesh(new C.ExtrudeGeometry(shape,{depth:.035,bevelEnabled:false}),steel,group,0,.12,-.017);const edge=mesh(new C.BoxGeometry(.013,length-.12,.02),glow(enemy?'#c87944':'#ff552c',enemy?.2:.5),group,width-.005,length/2+.1,.01);edge.visible=!enemy;mesh(new C.BoxGeometry(width*5,.05,.09),mat('#6c5242',.5,.6),group,0,.1,0);mesh(new C.CylinderGeometry(.045,.045,.28,6),mat('#282029'),group,0,-.08,0);group.userData={edge,tip:new C.Vector3(0,length+.12,0),base:new C.Vector3(0,.3,0)};return group;}
 createActor(e,isPlayer,weapon){if(!isPlayer&&EnemyData.enemies[e.type]?.creature)return createCreature(this.scene,e);const source=isPlayer?this.templates.hero:this.templates.enemy,root=new C.Group();this.scene.add(root);const model=cloneRig(source.scene);model.scale.setScalar(isPlayer?.90:e.boss?1.2:e.type==='brute'?1.1:.79);if(isPlayer)model.scale.y*=1.09;root.add(model);
  const body=mat(isPlayer?'#101420':e.type==='brute'?'#6c6061':e.type==='archer'?'#605574':'#8c8a76',isPlayer?.68:.9,isPlayer?.35:.04),cloak=mat(isPlayer?'#6a1e2f':e.type==='archer'?'#332347':'#302c32',.9),face=mat('#02030a',1),eyes=new C.MeshBasicMaterial({color:new C.Color(e.type==='archer'?'#bd80ff':'#ff6840').multiplyScalar(2.2)});
  model.traverse(o=>{if(o.isMesh){o.frustumCulled=false;o.castShadow=true;o.receiveShadow=true;o.material=o.name.includes('Cape')||o.name.includes('Cloak')?cloak:o.name.includes('Eyes')?eyes:o.name.includes('Head')?face:body;if(/Knife|Crossbow|Throwable|Shield|Sword|Eyes/.test(o.name))o.visible=false;}});
  const right=model.getObjectByName('handslotr'),left=model.getObjectByName('handslotl');const sword=this.makeSword(right,isPlayer?weapon.id:e.type==='brute'?'greatsword':'katana',!isPlayer);if(!isPlayer&&e.type==='archer'){for(const child of [...sword.children]){sword.remove(child);child.geometry.dispose();child.material.dispose();}const stock=mesh(new C.BoxGeometry(.09,.6,.12),mat('#6b503b'),sword,0,.15,0);mesh(new C.BoxGeometry(.72,.045,.06),mat('#777e80',.4,.7),sword,0,.36,0);mesh(new C.BoxGeometry(.65,.012,.015),mat('#b7a98d'),sword,0,.2,.035);}
  const extraParts=[];if(!isPlayer&&['shieldguard','warden'].includes(e.type)){const shield=mesh(new C.CylinderGeometry(.42,.42,.10,8),mat('#688084',.5,.4),left,0,0,.12);shield.rotation.x=Math.PI/2;extraParts.push(shield);}
  const second=isPlayer?this.makeSword(left,'twins'):null;if(second)second.visible=weapon.id==='twins';
  const health=new C.Group();root.add(health);health.position.y=isPlayer?2.5:e.boss?3.3:e.type==='brute'?3:2.3;const healthBack=mesh(new C.PlaneGeometry(1.30,.16),new C.MeshBasicMaterial({color:'#080a0d',depthTest:false,transparent:true,opacity:1}),health);healthBack.renderOrder=15;const healthFill=mesh(new C.PlaneGeometry(1.22,.105),new C.MeshBasicMaterial({color:e.type==='brute'?'#ffad56':'#e75345',depthTest:false}),health,0,0,.002);healthFill.renderOrder=16;health.visible=false;
  const bones=[];model.traverse(o=>{if(o.isBone)bones.push(o);});const mixer=new C.AnimationMixer(model),actions={};for(const clip of source.animations)actions[clip.name]=mixer.clipAction(clip);const runClip=source.animations.find(c=>c.name==='Running_B');const legMixer=isPlayer?new C.AnimationMixer(model):null;if(legMixer&&runClip){const clip=new C.AnimationClip('Moving attack legs',runClip.duration,runClip.tracks.filter(t=>/^(upperleg|lowerleg|foot|toes)/.test(t.name)).map(t=>t.clone()));legMixer.clipAction(clip).play();}const actor={extraParts,legMixer,bones,root,model,mixer,actions,current:null,state:'',weapon:weapon.id,sword,second,body,cloak,face,materials:[body,cloak,face,eyes],trail:[],id:e.id,deadStarted:false,health,healthFill};this.play(actor,'Idle',1,true);return actor;
 }
 play(actor,name,duration,loop=false){const next=actor.actions[name]||actor.actions.Idle;if(actor.current===next&&loop)return;actor.blend=actor.bones.map(b=>({p:b.position.clone(),q:b.quaternion.clone()}));actor.blendTime=0;actor.mixer.stopAllAction();next.reset();next.setLoop(loop?C.LoopRepeat:C.LoopOnce,loop?Infinity:1);next.clampWhenFinished=!loop;next.enabled=true;next.setEffectiveWeight(1);next.setEffectiveTimeScale(loop?duration:next.getClip().duration/Math.max(.12,duration));next.play();actor.current=next;}
 updateActor(actor,e,isPlayer,weapon,dt,sim){if(actor.creature){updateCreature(actor,e,dt,sim);return;}const root=actor.root;root.position.set(e.x*unit,(e.z||0)*unit,e.y*unit);let desired=Math.PI/2-(isPlayer&&weapon.ranged&&e.attack?e.attack.aimAngle:e.angle);let delta=Math.atan2(Math.sin(desired-root.rotation.y),Math.cos(desired-root.rotation.y));root.rotation.y+=delta*Math.min(1,dt*26||1);
  if(isPlayer&&actor.weapon!==weapon.id){actor.sword.parent.remove(actor.sword);actor.sword.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});actor.sword=this.makeSword(actor.model.getObjectByName('handslotr'),weapon.id);actor.second.visible=weapon.id==='twins';actor.weapon=weapon.id;actor.trail=[];}
  let state='idle',clip='Idle',duration=1,loop=true;
  if(e.dead){state='death';clip=e.deathSide>0?'Death_A':'Death_B';duration=.48;loop=false;root.position.y=(e.z||0)*unit;root.rotation.z=(e.deathSide||1)*Math.min(.7,(1.65-(e.death??1.25))*1.1);}
  else if(isPlayer&&e.dashTime>0){state='dash';clip='Dodge_Forward';duration=.23;loop=false;}
  else if(isPlayer&&e.attack){const motion=motionSample(e.attack);state='attack'+e.attack.id+':'+motion.pulse;clip=e.attack.def.clip;if(weapon.id==='twins'&&(e.attack.def.pulses||1)>1)clip=motion.pulse%2?'Dualwield_Melee_Attack_Chop':'Dualwield_Melee_Attack_Slice';duration=motion.duration;loop=false;}
  else if(!isPlayer&&e.z>5){state='air';clip='Hit_B';duration=.7;loop=false;root.rotation.z=Math.sin(sim.time*12)*.09;}
  else if(!isPlayer&&e.hit>.02){state='hit'+e.hitSerial;clip=e.hitSerial%2?'Hit_A':'Hit_B';duration=.28;loop=false;}
  else if(!isPlayer&&e.wind>0){state='wind';clip=e.type==='archer'?'1H_Ranged_Shooting':e.type==='brute'?'2H_Melee_Attack_Chop':'1H_Melee_Attack_Slice_Diagonal';duration=(e.type==='brute'?1.2:e.type==='archer'?1.1:.85)+.4;loop=false;}
  else if(!isPlayer&&e.attackAnim>0){state=actor.state==='wind'?'wind':'attackEnemy';clip=e.type==='archer'?'1H_Ranged_Shooting':e.type==='brute'?'2H_Melee_Attack_Chop':'1H_Melee_Attack_Slice_Diagonal';duration=1.2;loop=false;}
  else if(e.moving){state='run';clip=isPlayer?'Running_B':'Running_A';duration=isPlayer?1.7:e.active?1.05:.65;}
  if(actor.state!==state){actor.state=state;this.play(actor,clip,duration,loop);}
  actor.mixer.update(dt);
  if(isPlayer&&e.attack&&actor.current){
   const impact={'1H_Melee_Attack_Chop':.56,'1H_Melee_Attack_Slice_Diagonal':.43,'1H_Melee_Attack_Slice_Horizontal':.25,'1H_Melee_Attack_Stab':.24,'2H_Melee_Attack_Chop':.51,'2H_Melee_Attack_Slice':.35,'2H_Melee_Attack_Spin':.29,'Dualwield_Melee_Attack_Chop':.38,'Dualwield_Melee_Attack_Slice':.65,'Dualwield_Melee_Attack_Stab':.24}[actor.current.getClip().name]||.38;
   const sample=motionSample(e.attack),phase=clipPhase(sample,weapon.ranged?.38:impact,e.attack.chained||sample.pulse>0);
   actor.current.paused=true;actor.current.time=phase*actor.current.getClip().duration;actor.mixer.update(0);
  }
  if(isPlayer&&e.attack&&actor.legMixer){const legs=actor.bones.filter(b=>/^(upperleg|lowerleg|foot|toes)/.test(b.name)),poses=legs.map(b=>({p:b.position.clone(),q:b.quaternion.clone()}));actor.legWeight=(actor.legWeight||0)+((e.moving?1:0)-(actor.legWeight||0))*Math.min(1,dt*16);actor.legMixer.update(dt*1.7);legs.forEach((b,i)=>{b.position.lerpVectors(poses[i].p,b.position.clone(),actor.legWeight);b.quaternion.slerpQuaternions(poses[i].q,b.quaternion.clone(),actor.legWeight);});}
  if(actor.blend){actor.blendTime+=dt;const t=Math.min(1,actor.blendTime/(isPlayer&&e.attack?Math.min(.055,motionSample(e.attack).hit*.55):.10)),smooth=t*t*(3-2*t);actor.bones.forEach((b,i)=>{b.position.lerpVectors(actor.blend[i].p,b.position.clone(),smooth);b.quaternion.slerpQuaternions(actor.blend[i].q,b.quaternion.clone(),smooth);});if(t===1)actor.blend=null;}

  actor.body.emissive.set(e.hit>0?'#ce9f86':'#000000');actor.body.emissiveIntensity=e.hit>0?e.hit*6:0;if(isPlayer){actor.face.emissive.set('#000000');actor.sword.userData.edge.material.color.set(weapon.color).multiplyScalar(2);actor.sword.userData.edge.material.opacity=weapon.ranged?(e.attack&&Math.abs(e.attack.elapsed-e.attack.def.active)<.045?.95:0):e.attack?.85:.25;}
  if(state!=='air'&&!e.dead)root.rotation.z=0;if(isPlayer){const a=e.attack,weight=a?Math.sin(Math.min(1,a.elapsed/a.def.duration)*Math.PI):0;actor.model.rotation.z=weapon.ranged?0:(a?.step%2?1:-1)*weight*.065;actor.model.position.y=surfaceAt(e.x,e.y)==='snow'?-.035:0;}root.traverse(o=>{if(o.isSkinnedMesh)o.frustumCulled=false;});root.updateMatrixWorld(true);
  if(actor.health){actor.health.visible=false;const ratio=Math.max(0,e.hp/e.maxHp);actor.healthFill.scale.x=ratio;actor.healthFill.position.x=-.61*(1-ratio);actor.health.quaternion.copy(this.camera?.quaternion||new C.Quaternion()).premultiply(root.quaternion.clone().invert());}
  if(e.dead){for(const m of actor.materials){m.transparent=true;m.opacity=isPlayer?1:Math.min(1,e.death/.3);}}
  // Trail is sampled from the animated weapon, not a disconnected overlay.
  if(isPlayer&&!weapon.ranged&&e.attack&&motionSample(e.attack).t>motionSample(e.attack).hit-.045&&motionSample(e.attack).t<motionSample(e.attack).hit+.07){const tip=actor.sword.localToWorld(actor.sword.userData.tip.clone()),base=actor.sword.localToWorld(actor.sword.userData.base.clone());if(dt>0){actor.trail.push({tip,base,life:.10});if(actor.trail.length>9)actor.trail.shift();}}
  for(const item of actor.trail)item.life-=dt;actor.trail=actor.trail.filter(t=>t.life>0);
  if(actor.ribbon){this.scene.remove(actor.ribbon);actor.ribbon.geometry.dispose();actor.ribbon.material.dispose();actor.ribbon=null;}
  if(actor.trail.length>1){const values=[];for(let i=1;i<actor.trail.length;i++){const a=actor.trail[i-1],b=actor.trail[i];values.push(...a.tip.toArray(),...a.base.toArray(),...b.tip.toArray(),...a.base.toArray(),...b.base.toArray(),...b.tip.toArray());}const geo=new C.BufferGeometry();geo.setAttribute('position',new C.Float32BufferAttribute(values,3));actor.ribbon=new C.Mesh(geo,glow(weapon.color,.75));actor.ribbon.frustumCulled=false;this.scene.add(actor.ribbon);}
 }
 burst(x,z,y,color,count,force=1){const col=new C.Color(color).multiplyScalar(1.8);for(let i=0;i<count;i++){const a=Math.random()*TAU,v=(1+Math.random()*4)*force;this.particles.push({x,y,z,vx:Math.cos(a)*v,vy:1+Math.random()*4*force,vz:Math.sin(a)*v,life:.2+Math.random()*.5,color:col});}if(this.particles.length>this.maxParticles)this.particles.splice(0,this.particles.length-this.maxParticles);}
 ring(x,z,r,color,duration=.45){const object=mesh(new C.RingGeometry(r*.90,r,64),glow(color,.6),this.scene,x,.10,z);object.rotation.x=-Math.PI/2;this.effects.push({object,life:duration,max:duration,expand:true});}
 receive(events){for(const e of events){if(e.type==='hit'){this.lastHit=this.time;this.burst(e.x*unit,e.y*unit,.9+(e.z||0)*unit,e.color,e.heavy?28:16,e.heavy?1.3:.8);this.damageLabel(e);this.cutMark(e);this.impactFlash(e);if(!this.reduced)this.shake=Math.max(this.shake,e.heavy?.13:.055);}
   if(e.type==='portal'){this.cameraRig.reset();}
   if(e.type==='signatureDrop'){this.ring(e.x*unit,e.y*unit,1.3,'#f0c278',.8);this.burst(e.x*unit,e.y*unit,.6,'#f0c278',18,.7);}
   if(e.type==='shot'&&e.kind==='skill'){const length=Math.min(9,(e.reach||900)*unit);for(const side of (e.spread?[-1,0,1]:[0])){const angle=e.angle+side*(e.spread||0)*.5;const o=mesh(new C.PlaneGeometry(side? .06:.12,length),glow(side?e.color:'#fff2ca',.65),this.scene,e.x*unit+Math.cos(angle)*length/2,.8,e.y*unit+Math.sin(angle)*length/2);o.rotation.set(-Math.PI/2,0,Math.PI/2-angle);this.effects.push({object:o,life:.12,max:.12});}}
   if(e.type==='shot'){this.burst((e.x+Math.cos(e.angle)*65)*unit,(e.y+Math.sin(e.angle)*65)*unit,1,'#ffe0a0',6,.45);}
   if(e.type==='chest')this.burst(e.x*unit,e.y*unit,.65,'#cbb884',16,.55);
   if(e.type==='slash'){this.slash(e);for(const p of this.settlement?.surface.cut(e)||[])this.burst(p.x,p.z,.25,'#97b766',3,.23);}
   if(e.type==='slam'){this.ring(e.x*unit,e.y*unit,e.reach*unit,'#a79d89',.22);this.burst(e.x*unit,e.y*unit,.15,e.color,65,1.5);if(!this.reduced)this.shake=.25;}
   if(e.type==='death'){this.burst(e.x*unit,e.y*unit,1,e.color,22,.7);}
   if(e.type==='hurt'){this.flash=.3;this.damageLabel({...e,damage:'−'+e.damage});if(!this.reduced)this.shake=.14;}
   if(e.type==='spawn')this.ring(e.x*unit,e.y*unit,.6,'#809faf',.7);
   if(e.type==='enemyStrike')this.ring(e.x*unit,e.y*unit,e.reach*unit,'#ec633f',.3);
   if(e.type==='trail')this.burst(e.x*unit,e.y*unit,.12,'#8e8478',2,.12);
  }}
 cutMark(e){const actor=this.actors.get(e.id);if(actor){const o=mesh(new C.PlaneGeometry(.65,.045),new C.MeshBasicMaterial({color:'#531f1b',side:C.DoubleSide,transparent:true,depthWrite:false}),actor.root,0,1.05,.32);o.rotation.z=e.side>0?.65:-.65;this.effects.push({object:o,life:.55,max:.55});}for(let i=0;i<(e.heavy?7:3);i++){const o=mesh(new C.TetrahedronGeometry(.045+Math.random()*.04),mat('#a79882',.4,.6),this.scene,e.x*unit,.9+(e.z||0)*unit,e.y*unit);this.effects.push({object:o,life:.55,max:.55,v:new C.Vector3(Math.cos(e.angle)*(3+Math.random()*3)+(Math.random()-.5)*3,2+Math.random()*3,Math.sin(e.angle)*(3+Math.random()*3)+(Math.random()-.5)*3)});}}
 impactFlash(e){const g=new C.PlaneGeometry(e.heavy?.85:.5,.035);const o=mesh(g,glow('#fff2c9',.95),this.scene,e.x*.01,1+(e.z||0)*.01,e.y*.01);o.quaternion.copy(this.camera.quaternion);o.rotateZ(e.side*.65);this.effects.push({object:o,life:.085,max:.085});const core=mesh(new C.RingGeometry(.03,e.heavy?.25:.14,12),glow('#ffe1a2',.8),this.scene,e.x*.01,1+(e.z||0)*.01,e.y*.01);core.quaternion.copy(this.camera.quaternion);this.effects.push({object:core,life:.12,max:.12,expand:true});}
 slash(e){const x=e.x*unit,z=e.y*unit,r=e.reach*unit,a=-e.angle;
  if(e.kind==='skill'&&['twins','greatsword'].includes(e.weapon)){const count=e.weapon==='twins'?6:5;for(let i=0;i<count;i++){const angle=e.angle+i*Math.PI*2/count,length=r*(e.weapon==='twins'?.7:.9),o=mesh(new C.PlaneGeometry(e.weapon==='twins'?.08:.16,length),glow(e.color,.7),this.scene,x+Math.cos(angle)*length*.5,.12+i*.005,z+Math.sin(angle)*length*.5);o.rotation.set(-Math.PI/2,0,Math.PI/2-angle);this.effects.push({object:o,life:.24,max:.24});}}
  if(['nova','spin','pull'].includes(e.shape)){this.ring(x,z,r,e.color,.28);this.ring(x,z,r*.68,'#fff3c8',.18);for(let i=0;i<(this.reduced?2:4);i++){const arc=new C.RingGeometry(r*.82,r,32,1,0,Math.PI*.65),o=mesh(arc,glow(e.color,.75),this.scene,x,.25+i*.18,z);o.rotation.set(-Math.PI/2,0,i*Math.PI*.5-(e.index||0)*.8);this.effects.push({object:o,life:.22,max:.22});}this.burst(x,z,.35,e.color,this.reduced?12:32,1.4);return;}
  if(e.kind==='skill'&&e.shape==='rush'){this.ring(x,z,r*.7,e.color,.2);this.burst(x,z,.3,e.color,this.reduced?8:22,1.3);}
  if(e.shape==='line'){const o=mesh(new C.PlaneGeometry(.16,r),glow(e.color,.85),this.scene,x+Math.cos(e.angle)*r/2,.14,z+Math.sin(e.angle)*r/2);o.rotation.set(-Math.PI/2,0,Math.PI/2-e.angle);this.effects.push({object:o,life:.3,max:.3});this.burst(x+Math.cos(e.angle)*r,z+Math.sin(e.angle)*r,.2,e.color,16);return;}
  const arc=Math.min(e.arc||1.5,Math.PI*1.5),geo=new C.RingGeometry(r*.90,r,56,1,0,arc);const o=mesh(geo,glow(e.color,.65),this.scene,x,.7+(e.z||0)*unit,z);o.rotation.set(-Math.PI/2,0,-e.angle-arc/2);this.effects.push({object:o,life:.12,max:.12});
 }
 damageLabel(e){const node=document.createElement('span');node.className='damage-number'+(e.heavy?' heavy':'')+(e.aerial?' aerial':'');node.textContent=(e.critical?'CRIT ':'')+e.damage;this.labelLayer.append(node);this.labels.push({node,x:e.x*unit,y:1.6+(e.z||0)*unit,z:e.y*unit,life:.65});}
 screenPosition(x,y,z){return projectedPoint(this.camera,this.width,this.height,x,y,z);}
 render(sim,dt=0){this.time+=dt;this.portals?.update(sim,this.time);this.shake=Math.max(0,this.shake-dt*.7);this.flash=Math.max(0,this.flash-dt);const p=sim.player;
  this.cameraRig.update(p,sim.enemies,dt,this.reduced);if(this.shake&&!this.reduced){this.camera.position.x+=Math.sin(this.time*83)*this.shake*.4;this.camera.position.y+=Math.cos(this.time*71)*this.shake*.25;this.camera.lookAt(this.focus);this.camera.updateMatrixWorld();}
  this.atmosphere.update(this.time,this.focus);
  // Snap the light in light-space texels: static scenery no longer crawls as the camera moves.
  const direction=new C.Vector3(-12,22,-10).normalize(),right=new C.Vector3().crossVectors(new C.Vector3(0,1,0),direction).normalize(),up=new C.Vector3().crossVectors(direction,right),texel=34/this.budget.shadowSize;
  const lightFocus=this.focus.clone().addScaledVector(right,Math.round(this.focus.dot(right)/texel)*texel-this.focus.dot(right)).addScaledVector(up,Math.round(this.focus.dot(up)/texel)*texel-this.focus.dot(up));
  this.sun.position.copy(lightFocus).addScaledVector(direction,30);this.sun.target.position.copy(lightFocus);this.sun.target.updateMatrixWorld();

  const animationDt=this.paused||sim.hitstop>0?0:sim.slowmo>0?dt*.35:dt;
  if(this.loaded){let actor=this.actors.get('hero');if(!actor){actor=this.createActor(p,true,sim.weapon);this.actors.set('hero',actor);}syncGear(actor,sim.profile);this.updateActor(actor,p,true,sim.weapon,animationDt,sim);
   const actorIds=nearbyRenderIds(sim.enemies,p,this.actors,this.performanceMode?1500:1800,this.performanceMode?1800:2100);for(const e of sim.enemies){if(!actorIds.has(e.id))continue;let a=this.actors.get(e.id);if(!a){a=this.createActor(e,false,sim.weapon);this.actors.set(e.id,a);}this.updateActor(a,e,false,sim.weapon,animationDt,sim);}
   for(const [id,a] of this.actors)if(id!=='hero'&&!actorIds.has(id)){this.disposeActor(a);this.actors.delete(id);}
  }
  let teleIndex=0;for(const e of sim.enemies)if(e.wind>0&&!e.dead){let g=this.telegraphPool[teleIndex++];if(!g){g=new C.Group();g.ring=mesh(new C.RingGeometry(.9,1,48),glow('#f58353',.65),g);g.ring.rotation.x=-Math.PI/2;g.fill=mesh(new C.CircleGeometry(1,40),glow('#d44327',.28),g,0,-.01,0);g.fill.rotation.x=-Math.PI/2;g.lane=mesh(new C.BoxGeometry(.85,.02,1),glow('#f27240',.35),g);this.scene.add(g);this.telegraphPool.push(g);}g.visible=true;const r=(e.attackKind==='web'?(e.boss?255:85):e.attackKind==='sweep'?(e.type==='colossus'||e.type==='warden'?270:e.type==='golem'?200:235):e.boss?145:e.type==='brute'?125:e.type==='archer'?36:78)*unit;g.position.set((e.attackKind==='sweep'?e.x:e.attackX)*unit,.14,(e.attackKind==='sweep'?e.y:e.attackY)*unit);g.scale.setScalar(r);const progress=Math.max(.01,1-e.wind/e.windMax);g.fill.scale.setScalar(progress);const charge=e.attackKind==='charge';g.lane.visible=charge;g.ring.visible=g.fill.visible=!charge;if(charge){g.scale.setScalar(1);g.position.set(e.x*unit,.14,e.y*unit);const len=e.type==='warden'?3.9:e.type==='ridgebeast'?2.73:e.boss?3.29:1.68;g.lane.scale.x=2;g.lane.scale.z=len;g.lane.position.set(Math.cos(e.angle)*len/2,0,Math.sin(e.angle)*len/2);g.lane.rotation.y=Math.PI/2-e.angle;}}
  this.hazardPool??=[];for(const [i,h] of (sim.hazards||[]).entries()){let m=this.hazardPool[i];if(!m){m=mesh(new C.RingGeometry(.1,1,32),glow('#f19b56',.3),this.scene);m.rotation.x=-Math.PI/2;this.hazardPool.push(m);}m.visible=true;m.position.set(h.x*.01,.035,h.y*.01);m.scale.setScalar(h.radius*.01);m.material.color.set(h.kind==='web'?'#92dce1':'#f69b42');m.material.opacity=h.delay>0?.14+Math.sin(sim.time*15)*.05:.32;}for(let i=(sim.hazards||[]).length;i<this.hazardPool.length;i++)this.hazardPool[i].visible=false;
  for(let i=teleIndex;i<this.telegraphPool.length;i++)this.telegraphPool[i].visible=false;
  for(let i=this.ghosts.length-1;i>=0;i--){const g=this.ghosts[i];g.life-=dt;g.material.opacity=Math.max(0,g.life)*.9;if(g.life<=0){this.scene.remove(g.object);g.material.dispose();this.ghosts.splice(i,1);}}
  this.boltPool??=[];sim.projectiles.forEach((b,i)=>{let o=this.boltPool[i];if(!o){o=mesh(new C.BoxGeometry(.025,.025,.5),mat('#b6aa8b'),this.scene);this.boltPool.push(o);}o.visible=true;o.position.set(b.x*unit,.9,b.y*unit);o.rotation.y=Math.atan2(b.vx,b.vy);});for(let i=sim.projectiles.length;i<this.boltPool.length;i++)this.boltPool[i].visible=false;
  const lootLabelPositions=[];const visibleLootLabels=lootLabelIds(sim);this.lootObjects??=new Map();const lootIds=nearbyRenderIds(sim.loot,p,this.lootObjects);for(const l of sim.loot){if(!lootIds.has(l.id))continue;let o=this.lootObjects.get(l.id);if(!o){const color=l.item?RARITIES.find(r=>r.id===l.item.rarity).color:l.kind==='gold'?'#e8bc58':l.kind==='heal'?'#c2684b':l.kind==='blade'?'#80bada':'#92bfa3';o=new C.Group();if(l.item){const gear=gearMesh(l.item.slot,l.item,l.item.classId||sim.player.weapon);gear.scale.setScalar(l.item.slot==='weapon'?1:1.1);gear.rotation.set(-Math.PI/2,0,l.id*2.399);const box=new C.Box3().setFromObject(gear),center=box.getCenter(new C.Vector3());gear.position.x-=center.x;gear.position.z-=center.z;gear.position.y-=box.min.y;gear.position.y+=.08;gear.traverse(m=>{if(m.isMesh&&m.material.emissive){m.material.emissive.set(color);m.material.emissiveIntensity=.20;m.material.roughness=.5;}});o.add(gear);}else if(l.kind==='gold'){mesh(new C.CylinderGeometry(.14,.14,.07,10),mat(color,.35,.6),o,0,.07,0);}else{mesh(new C.CylinderGeometry(.10,.15,.24,8),mat('#bd735e',.6,.05),o,0,.16,0);mesh(new C.CylinderGeometry(.065,.065,.08,8),mat('#ddcda5'),o,0,.32,0);}const marker=mesh(new C.RingGeometry(.25,.27,24),glow(color,l.item?.4:0),o,0,.035,0);marker.rotation.x=-Math.PI/2;this.scene.add(o);const label=document.createElement('span');label.className='loot-label'+(l.item?' tappable':'');if(l.item){label.dataset.lootId=String(l.id);label.setAttribute?.('role','button');label.setAttribute?.('aria-label','Pick up '+l.item.name);label.onpointerdown=e=>{e.preventDefault();e.stopPropagation();window.selectGroundLoot?.(l.id);};}label.textContent=l.item?l.item.name:l.kind==='gold'?l.amount+' coins':l.kind==='heal'?'Supplies +'+l.amount:l.kind==='blade'?'Tempered steel':'Reinforced armor';label.style.color=color;this.labelLayer.append(label);o.userData.label=label;this.lootObjects.set(l.id,o);}o.position.set(l.x*.01,l.z*.01,l.y*.01);if(!l.item)o.children[0].rotation.y=l.age*1.5;const pos=this.screenPosition(l.x*.01,l.z*.01+.5,l.y*.01);if(visibleLootLabels.has(l.id)){for(let j=0;j<3;j++)if(lootLabelPositions.some(q=>Math.abs(q.x-pos.x)<150&&Math.abs(q.y-pos.y)<22))pos.y-=23;lootLabelPositions.push(pos);}o.userData.label.style.transform=`translate(${pos.x}px,${pos.y}px)`;o.userData.label.style.display=visibleLootLabels.has(l.id)&&pos.visible?'block':'none';}
  for(const [id,o] of this.lootObjects)if(!lootIds.has(id)){o.userData.label?.remove();o.removeFromParent();o.traverse(n=>{if(n.isMesh){n.geometry.dispose();n.material.dispose();}});this.lootObjects.delete(id);}
  this.shotPool??=[];sim.bullets.forEach((b,i)=>{let o=this.shotPool[i];if(!o){o=mesh(new C.BoxGeometry(.035,.035,.95),glow('#ffde9c',.9),this.scene);this.shotPool.push(o);}o.visible=true;o.position.set(b.x*.01,1,b.y*.01);o.rotation.y=Math.PI/2-b.angle;});for(let i=sim.bullets.length;i<this.shotPool.length;i++)this.shotPool[i].visible=false;
  syncChests(this.scene,this.chestObjects,sim.chests,sim.time);this.gate.position.y=C.MathUtils.lerp(this.gate.position.y,sim.bossesDefeated.includes('captain')?3:0,Math.min(1,dt*3));
  for(let i=this.effects.length-1;i>=0;i--){const fx=this.effects[i];fx.life-=dt;if(fx.v){fx.object.position.addScaledVector(fx.v,dt);fx.v.y-=12*dt;fx.object.rotation.x+=dt*9;}fx.object.material.opacity=Math.max(0,fx.life/fx.max)*.6;if(fx.expand)fx.object.scale.setScalar(1+(1-fx.life/fx.max)*.22);if(fx.life<=0){fx.object.removeFromParent();fx.object.geometry.dispose();fx.object.material.dispose();this.effects.splice(i,1);}}
  for(const particle of this.particles){particle.life-=dt;particle.x+=particle.vx*dt;particle.y+=particle.vy*dt;particle.z+=particle.vz*dt;particle.vy-=10*dt;}this.particles=this.particles.filter(a=>a.life>0);let index=0;for(const a of this.particles){this.positions[index*3]=a.x;this.positions[index*3+1]=a.y;this.positions[index*3+2]=a.z;this.colors[index*3]=a.color.r*Math.min(1,a.life*4);this.colors[index*3+1]=a.color.g*Math.min(1,a.life*4);this.colors[index*3+2]=a.color.b*Math.min(1,a.life*4);index++;}this.particleMesh.geometry.setDrawRange(0,index);this.particleMesh.geometry.attributes.position.needsUpdate=true;this.particleMesh.geometry.attributes.color.needsUpdate=true;
  for(let i=this.labels.length-1;i>=0;i--){const l=this.labels[i];l.life-=dt;l.y+=dt;const q=this.screenPosition(l.x,l.y,l.z);l.node.style.transform=`translate(${q.x}px,${q.y}px)`;l.node.style.opacity=Math.min(1,l.life*3);if(l.life<=0){l.node.remove();this.labels.splice(i,1);}}
  this.fires.forEach((f,i)=>{f.flame.scale.set(1+Math.sin(this.time*8+i)*.12,1+Math.sin(this.time*13+i)*.17,1);f.flame.rotation.y=this.time*.8;if(Math.random()<dt*6)this.burst(f.x,f.z,2,'#ff9540',1,.1);});
  if(!this.paused&&Math.random()<dt*12)this.burst(p.x*.01+(Math.random()-.5)*16,p.y*.01+(Math.random()-.5)*16,Math.random()*2,'#aaa58a',1,.08);
  for(const [i,w] of (this.windObjects||[]).entries())w.object.rotation.z=w.base+Math.sin(this.time*.8+i)*.017;
  if(this.haze){for(let i=0;i<this.haze.children.length;i++){const o=this.haze.children[i];o.position.x=p.x*.01+Math.sin(this.time*.07+i*2)*11;o.position.z=p.y*.01+Math.cos(this.time*.09+i*1.7)*10;}}
  this.worldMarkerPlan=planWorldMarkers(this,sim);this.huntScenery?.update(sim);updateHuntMarkers(this,sim);this.settlement?.update(sim.time,sim.profile);if(!this.paused){const step=this.settlement?.surface.update(sim.time,p);if(step?.surface==='snow')this.burst(step.x,step.z,.07,'#cddfe7',p.dashTime>0?10:4,.14);}updateEnemyBars(this,sim,animationDt);
  if(this.loaded){this.storyActors??=new Map();const current=currentStory(sim.profile);for(const n of PEOPLE){let a=this.storyActors.get(n.id);if(!a){const root=new C.Group();this.scene.add(root);let mixer=null;if(!n.kind){const model=cloneRig(this.templates.hero.scene);model.scale.setScalar(['lina','mill','ending'].includes(n.id)?.82:.88);const cloth=mat(n.color),face=mat('#292c2b');model.traverse(o=>{if(o.isMesh){o.material=/Head|Eyes/.test(o.name)?face:cloth;o.castShadow=true;if(/Knife|Crossbow|Throwable|Shield|Sword|Eyes/.test(o.name))o.visible=false;}});root.add(model);mixer=new C.AnimationMixer(model);const idle=this.templates.hero.animations.find(c=>c.name==='Idle');if(idle)mixer.clipAction(idle).play();}else{if(n.kind==='wheel'){const wheel=mesh(new C.TorusGeometry(.48,.07,6,20),mat('#ad8550'),root,0,.82,0);for(let i=0;i<4;i++){const spoke=mesh(new C.BoxGeometry(.06,.86,.05),mat('#ad8550'),wheel);spoke.rotation.z=i*Math.PI/4;}}mesh(new C.BoxGeometry(.8,.55,.65),mat('#886648'),root,0,.28,0);mesh(new C.BoxGeometry(.4,.02,.3),mat('#eed8a5'),root,0,.57,0);}root.position.set(n.x*.01,0,n.y*.01);const node=document.createElement('button');node.className='story-marker';node.onclick=()=>window.openStoryPerson?.(n.id);this.labelLayer.append(node);a={root,mixer,node};this.storyActors.set(n.id,a);}const near=personPresent(sim.profile,n)&&Math.hypot(n.x-p.x,n.y-p.y)<1000;a.root.visible=near;paintMarker(a.node,this.worldMarkerPlan.get('npc:'+n.id),'story-marker',n.name);if(near)a.mixer?.update(animationDt);}}
  if(!this.budget.postprocessing)this.renderer.render(this.scene,this.camera);else this.composer.render();
 }
 mountGearPreview(container,profile){if(!this.loaded||!container)return()=>{};const renderer=new C.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(container.clientWidth||280,container.clientHeight||380);renderer.outputColorSpace=C.SRGBColorSpace;renderer.toneMapping=C.ACESFilmicToneMapping;container.append(renderer.domElement);const preview=Object.create(ShadowRenderer.prototype);preview.scene=new C.Scene();preview.templates=this.templates;preview.camera=new C.PerspectiveCamera(30,(container.clientWidth||280)/(container.clientHeight||380),.1,20);preview.camera.position.set(1.2,1.6,5);preview.camera.lookAt(0,1.05,0);preview.scene.add(new C.HemisphereLight('#c9e2f3','#30242a',2));const key=new C.DirectionalLight('#ffe1b2',4);key.position.set(3,5,4);preview.scene.add(key);const rim=new C.DirectionalLight('#79a3c8',2);rim.position.set(-3,2,-2);preview.scene.add(rim);const actor=preview.createActor({id:'preview'},true,{id:profile.classId});actor.mixer.update(.1);syncGear(actor,profile);mesh(new C.CylinderGeometry(.8,.9,.1,32),mat('#25303a'),preview.scene,0,-.05,0);actor.root.rotation.y=-.18;renderer.render(preview.scene,preview.camera);let dragging=false,lastX=0;renderer.domElement.onpointerdown=e=>{dragging=true;lastX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(dragging){actor.root.rotation.y+=(e.clientX-lastX)*.015;lastX=e.clientX;renderer.render(preview.scene,preview.camera);}};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>dragging=false;return()=>{preview.disposeActor(actor);preview.scene.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();};}
 hitLoot(sim,clientX,clientY){let best=null,distance=38;for(const l of sim.loot){if(!l.item||Math.hypot(l.x-sim.player.x,l.y-sim.player.y)>800)continue;const q=this.screenPosition(l.x*.01,l.z*.01+.15,l.y*.01),d=Math.hypot(q.x-clientX,q.y-clientY);if(d<distance){distance=d;best=l.id;}}return best;}
 disposeActor(a){if(a.creature){disposeCreature(a);return;}
  for(const g of [...(a.gearParts||[]),...(a.extraParts||[])])disposeGear(g);this.scene.remove(a.root);if(a.ribbon){this.scene.remove(a.ribbon);a.ribbon.geometry.dispose();a.ribbon.material.dispose();}
  a.mixer.stopAllAction();a.mixer.uncacheRoot(a.model);a.legMixer?.stopAllAction();a.legMixer?.uncacheRoot(a.model);
  const skeletons=new Set();a.model.traverse(o=>{if(o.isSkinnedMesh)skeletons.add(o.skeleton);});skeletons.forEach(s=>s.dispose());
  for(const group of [a.sword,a.second,a.health])if(group)group.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});
  a.materials.forEach(m=>m.dispose());
 }
 reset(){clearEnemyBars(this);this.settlement?.surface.reset();for(const o of this.lootObjects?.values()||[]){o.userData.label?.remove();o.removeFromParent();o.traverse(n=>{if(n.isMesh){n.geometry.dispose();n.material.dispose();}});}this.lootObjects?.clear();for(const o of this.shotPool||[])o.visible=false;for(const a of this.actors.values())this.disposeActor(a);this.actors.clear();for(const e of this.effects){e.object.removeFromParent();e.object.geometry.dispose();e.object.material.dispose();}this.effects=[];this.particles=[];for(const g of this.ghosts){this.scene.remove(g.object);g.material.dispose();}this.ghosts=[];for(const l of this.labels)l.node.remove();this.labels=[];this.focus.set(LEVEL.start.x*.01,.5,LEVEL.start.y*.01);this.cameraRig.reset();}
}
