plugins { id 'com.android.application' }
android {
    namespace 'com.kage.shadowfall'
    compileSdk 35
    defaultConfig {
        applicationId 'com.kage.shadowfall'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        minSdk 26
        targetSdk 35
        versionCode 37
        versionName '0.23.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        debug { applicationIdSuffix '.device'; versionNameSuffix '-test' }
        release { minifyEnabled false }
    }
}
dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
